CREATE TABLE IF NOT EXISTS oauth_states (state TEXT PRIMARY KEY, cookie_hash TEXT NOT NULL, challenge TEXT NOT NULL, client_state TEXT NOT NULL, port INTEGER NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS auth_codes (code_hash TEXT PRIMARY KEY, challenge TEXT NOT NULL, user_id TEXT NOT NULL, username TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL, username TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS submissions (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, username TEXT NOT NULL, kind TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, skin_url TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'open', created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS submission_feed ON submissions(kind,created);
CREATE TABLE IF NOT EXISTS rate_limits (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS notifications (submission_id TEXT PRIMARY KEY, sent INTEGER NOT NULL DEFAULT 0, attempts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS profiles (user_id TEXT PRIMARY KEY, color TEXT NOT NULL DEFAULT '#9bb9ff');
