// Discord credentials and webhook are Worker secrets, never desktop configuration.
const encoder=new TextEncoder();
const now=()=>Math.floor(Date.now()/1000);
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
const hash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value))),b=>b.toString(16).padStart(2,'0')).join('');
const challenge=async value=>btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(value))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
function response(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});}
function fail(message,status=400){throw Object.assign(Error(message),{status});}
async function body(request,max=10000){const reader=request.body?.getReader();if(!reader)fail('Request body required.');let size=0,chunks=[];try{while(true){const{done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();fail('Request is too large.',413);}chunks.push(value);}}finally{reader.releaseLock();}try{return JSON.parse(new TextDecoder().decode(await new Blob(chunks).arrayBuffer()));}catch{fail('Invalid JSON.');}}
function text(value,min,max){if(typeof value!=='string'||value.trim().length<min||value.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value))fail('Check the text length and content.');return value.trim();}
function skinLink(value){if(!value)return'';let url;try{url=new URL(value);}catch{fail('Enter a valid skin download link.');}if(url.protocol!=='https:'||url.username||url.password||value.length>1000)fail('Use an HTTPS download link.');return url.href;}
async function limit(env,key,maximum,seconds){const bucket=key+':'+Math.floor(now()/seconds);const row=await env.DB.prepare('INSERT INTO rate_limits(bucket,count,expires) VALUES(?,1,?) ON CONFLICT(bucket) DO UPDATE SET count=count+1 RETURNING count').bind(bucket,now()+seconds).first();if(row.count>maximum)fail('Too many requests. Please try again later.',429);}
async function identity(request,env){const token=request.headers.get('Authorization')?.match(/^Bearer ([a-f0-9]{64})$/)?.[1];if(!token)fail('Sign in with Discord first.',401);const user=await env.DB.prepare('SELECT user_id,username FROM sessions WHERE token_hash=? AND expires>?').bind(await hash(token),now()).first();if(!user)fail('Your session expired. Sign in again.',401);return{...user,isAdmin:user.user_id===env.DISCORD_OWNER_ID};}
async function remoteJSON(url,options){let r;try{r=await fetch(url,{...options,signal:AbortSignal.timeout(10000),redirect:'manual'});}catch(e){fail('Discord connection failed ('+(e.name==='TypeError'?'request configuration':'network timeout')+'). Please retry.',502);}if(!r.ok)fail('Discord could not complete sign-in. Please retry.',502);return r.json();}
function configured(env){let u;try{u=new URL(env.PUBLIC_ORIGIN);}catch{fail('Community service is not configured.',503);}if(u.protocol!=='https:'||u.origin!==env.PUBLIC_ORIGIN||!/^\d{15,22}$/.test(env.DISCORD_CLIENT_ID||'')||!env.DISCORD_CLIENT_SECRET)fail('Community service is not configured.',503);return u.origin;}
async function notify(env,id){if(!env.DISCORD_WEBHOOK)return;let target;try{target=new URL(env.DISCORD_WEBHOOK);}catch{return;}if(target.origin!=='https://discord.com'||!/^\/api\/webhooks\/\d+\/[\w-]+$/.test(target.pathname))return;
 const row=await env.DB.prepare('SELECT s.* FROM submissions s JOIN notifications n ON n.submission_id=s.id WHERE s.id=? AND n.sent=0 AND n.attempts<5').bind(id).first();if(!row)return;
 // Claim before posting. An ambiguous network response is not automatically resent.
 const claimed=await env.DB.prepare('UPDATE notifications SET sent=2,attempts=attempts+1 WHERE submission_id=? AND sent=0 RETURNING submission_id').bind(id).first();if(!claimed)return;
 try{const r=await fetch(target,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({allowed_mentions:{parse:[]},embeds:[{title:(row.kind==='skin'?'Skin submission: ':'Feature request: ')+row.title,description:row.body.slice(0,2000),color:0x80c9ec,author:{name:row.username},timestamp:new Date(row.created*1000).toISOString(),fields:[{name:'Submission ID',value:row.id},{name:'Status',value:row.status},...(row.skin_url?[{name:'Submitted link — review before opening',value:row.skin_url}]:[])]}]}),signal:AbortSignal.timeout(10000),redirect:'manual'});if(r.ok)await env.DB.prepare('UPDATE notifications SET sent=1 WHERE submission_id=?').bind(id).run();else if(r.status===429)await env.DB.prepare('UPDATE notifications SET sent=0 WHERE submission_id=?').bind(id).run();}catch{/* Preserve uncertain status for owner review; no duplicate auto-post. */}}
async function routes(request,env,ctx){const origin=configured(env),url=new URL(request.url),p=url.pathname;if(request.headers.get('Origin')&&request.headers.get('Origin')!==origin)fail('Origin is not allowed.',403);
 const ip=request.headers.get('CF-Connecting-IP')||'unknown';await limit(env,'ip:'+await hash(ip),90,60);
 if(request.method==='GET'&&p==='/auth/discord'){
  const c=url.searchParams.get('challenge'),state=url.searchParams.get('state'),port=Number(url.searchParams.get('port'));if(!/^[A-Za-z0-9_-]{43}$/.test(c||'')||!/^[a-f0-9]{64}$/.test(state||'')||!Number.isInteger(port)||port<1024||port>65535)fail('Invalid desktop sign-in request.');
  const oauthState=random(),cookie=random();await env.DB.prepare('INSERT INTO oauth_states VALUES(?,?,?,?,?,?)').bind(oauthState,await hash(cookie),c,state,port,now()+300).run();
  const target=new URL('https://discord.com/oauth2/authorize');target.search=new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,response_type:'code',redirect_uri:origin+'/auth/callback',scope:'identify',state:oauthState}).toString();
  return new Response(null,{status:302,headers:{Location:target.href,'Set-Cookie':`oauth=${cookie}; HttpOnly; Secure; SameSite=Lax; Path=/auth; Max-Age=300`,'Cache-Control':'no-store'}});
 }
 if(request.method==='GET'&&p==='/auth/callback'){
  const state=url.searchParams.get('state'),code=url.searchParams.get('code'),cookie=request.headers.get('Cookie')?.match(/(?:^|;\s*)oauth=([a-f0-9]{64})(?:;|$)/)?.[1];if(!/^[a-f0-9]{64}$/.test(state||'')||!cookie||!code||code.length>512)fail('Sign-in was cancelled or expired. Return to the app and try again.');
  const row=await env.DB.prepare('DELETE FROM oauth_states WHERE state=? AND cookie_hash=? AND expires>? RETURNING *').bind(state,await hash(cookie),now()).first().catch(()=>fail('Sign-in storage could not complete. Please retry.',503));if(!row)fail('Sign-in expired. Return to the app and try again.');
  const token=await remoteJSON('https://discord.com/api/v10/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,client_secret:env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code,redirect_uri:origin+'/auth/callback'})});
  const user=await remoteJSON('https://discord.com/api/v10/users/@me',{headers:{Authorization:'Bearer '+token.access_token}});if(!/^\d{15,22}$/.test(user.id))fail('Discord returned an invalid identity.',502);
  const handoff=random();await env.DB.prepare('INSERT INTO auth_codes VALUES(?,?,?,?,?)').bind(await hash(handoff),row.challenge,user.id,text(user.username||user.global_name,1,80),now()+60).run();
  const target=new URL(`http://127.0.0.1:${row.port}/callback`);target.search=new URLSearchParams({code:handoff,state:row.client_state}).toString();return new Response(null,{status:302,headers:{Location:target.href,'Set-Cookie':'oauth=; HttpOnly; Secure; SameSite=Lax; Path=/auth; Max-Age=0','Cache-Control':'no-store','Referrer-Policy':'no-referrer'}});
 }
 if(request.method==='POST'&&p==='/auth/exchange'){
  const input=await body(request);if(!/^[a-f0-9]{64}$/.test(input.code||'')||!/^[A-Za-z0-9_-]{43,128}$/.test(input.verifier||''))fail('Invalid sign-in exchange.');const row=await env.DB.prepare('DELETE FROM auth_codes WHERE code_hash=? AND challenge=? AND expires>? RETURNING *').bind(await hash(input.code),await challenge(input.verifier),now()).first();if(!row)fail('Sign-in expired. Try again.',401);const token=random();await env.DB.prepare('INSERT INTO sessions VALUES(?,?,?,?)').bind(await hash(token),row.user_id,row.username,now()+30*86400).run();return response({token});
 }
 if(request.method==='GET'&&p==='/feed'){const kind=url.searchParams.get('kind')==='skin'?'skin':'feature';const rows=await env.DB.prepare("SELECT s.id,s.username,s.kind,s.title,s.body,s.skin_url,s.status,s.created,p.color FROM submissions s LEFT JOIN profiles p ON p.user_id=s.user_id WHERE s.kind=? AND s.status!='hidden' AND (s.kind!='skin' OR s.status='approved') ORDER BY s.created DESC LIMIT 100").bind(kind).all();return response({items:rows.results});}
 const user=await identity(request,env);
 if(request.method==='POST'&&p==='/profile'){const input=await body(request);if(!/^#[a-f0-9]{6}$/i.test(input.color||''))fail('Choose a valid color.');await env.DB.prepare('INSERT INTO profiles(user_id,color) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET color=excluded.color').bind(user.user_id,input.color).run();return response({ok:true});}
 if(request.method==='GET'&&p==='/me')return response({id:user.user_id,name:user.username,isAdmin:user.isAdmin});
 if(request.method==='POST'&&p==='/logout'){await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(request.headers.get('Authorization').slice(7))).run();return response({ok:true});}
 if(request.method==='POST'&&p==='/submit'){
  const input=await body(request);if(!['feature','skin'].includes(input.kind))fail('Choose a feature request or skin submission.');await limit(env,'submit:'+user.user_id,5,3600);const title=text(input.title,3,100),description=text(input.body,10,2000),link=input.kind==='skin'?skinLink(input.skinUrl):'';if(input.kind==='skin'&&(!link||input.ownsRights!==true))fail('Include your skin link and confirm permission to share it.');
  const id=random(),status=input.kind==='skin'?'pending':'open';await env.DB.batch([env.DB.prepare('INSERT INTO submissions VALUES(?,?,?,?,?,?,?,?,?)').bind(id,user.user_id,user.username,input.kind,title,description,link,status,now()),env.DB.prepare('INSERT INTO notifications(submission_id) VALUES(?)').bind(id)]);ctx.waitUntil(notify(env,id));return response({id,status},201);
 }
 if(request.method==='GET'&&p==='/admin/queue'){if(!user.isAdmin)fail('Owner access required.',403);return response({items:(await env.DB.prepare('SELECT s.*,n.sent AS notification_status FROM submissions s LEFT JOIN notifications n ON n.submission_id=s.id ORDER BY created DESC LIMIT 100').all()).results});}
 if(request.method==='POST'&&p==='/admin/review'){if(!user.isAdmin)fail('Owner access required.',403);const input=await body(request);if(!/^[a-f0-9]{64}$/.test(input.id||'')||!['open','accepted','declined','hidden','approved'].includes(input.status))fail('Invalid review.');const row=await env.DB.prepare('SELECT kind FROM submissions WHERE id=?').bind(input.id).first();if(!row)fail('Submission not found.',404);if(row.kind==='skin'&&!['approved','declined','hidden'].includes(input.status)||row.kind==='feature'&&input.status==='approved')fail('Choose a valid status for this submission.');await env.DB.prepare('UPDATE submissions SET status=? WHERE id=?').bind(input.status,input.id).run();return response({ok:true});}
 fail('Not found.',404);
}
export default{
 async fetch(request,env,ctx){try{return await routes(request,env,ctx);}catch(error){return response({error:error.status?error.message:'Community service is temporarily unavailable.'},error.status||500);}},
 async scheduled(_event,env,ctx){ctx.waitUntil((async()=>{for(const table of ['oauth_states','auth_codes','sessions','rate_limits'])await env.DB.prepare(`DELETE FROM ${table} WHERE expires<?`).bind(now()).run();const rows=await env.DB.prepare('SELECT submission_id FROM notifications WHERE sent=0 AND attempts<5 LIMIT 10').all();for(const row of rows.results)await notify(env,row.submission_id);})());}
};
export{skinLink,text,challenge};
