const test=require('node:test'),assert=require('node:assert/strict');
globalThis.crypto??=require('node:crypto').webcrypto;
const envBase={PUBLIC_ORIGIN:'https://community.example',DISCORD_CLIENT_ID:'123456789012345678',DISCORD_CLIENT_SECRET:'unit-test-placeholder',DISCORD_OWNER_ID:'999999999999999999'};
test('OAuth PKCE uses the standard SHA-256 challenge and rejects unsafe skin schemes',async()=>{const{challenge,skinLink}=await import('../community-server/worker.mjs');assert.equal(await challenge('dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk'),'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM');for(const link of ['javascript:alert(1)','file:///C:/x','https://name:pass@example.com/x'])assert.throws(()=>skinLink(link));assert.equal(skinLink('https://example.com/skin'),'https://example.com/skin');});
test('server rejects cross-origin posts before using identity or database',async()=>{const{default:worker}=await import('../community-server/worker.mjs');const result=await worker.fetch(new Request('https://community.example/submit',{method:'POST',headers:{Origin:'https://evil.example'},body:'{}'}),{...envBase,DB:{prepare:()=>assert.fail('Cross-origin request reached storage')}},{});assert.equal(result.status,403);});
function database(){const inserts=[];return{inserts,prepare(sql){let values;return{bind(...args){values=args;return this;},async first(){if(sql.includes('rate_limits'))return{count:1};if(sql.includes('FROM sessions'))return{user_id:'111111111111111111',username:'Verified Discord Name'};return null;},async run(){inserts.push({sql,values});return{};}};},async batch(statements){return Promise.all(statements.map(s=>s.run()));}};}
test('feature author comes from verified session, not submitted identity',async()=>{const{default:worker}=await import('../community-server/worker.mjs'),db=database();const result=await worker.fetch(new Request('https://community.example/submit',{method:'POST',headers:{Authorization:'Bearer '+'a'.repeat(64),'Content-Type':'application/json'},body:JSON.stringify({kind:'feature',title:'A useful idea',body:'A detailed feature request.',username:'Owner',user_id:envBase.DISCORD_OWNER_ID})}),{...envBase,DB:db},{waitUntil:()=>{}});assert.equal(result.status,201);const insert=db.inserts.find(s=>s.sql.includes('INSERT INTO submissions'));assert.equal(insert.values[1],'111111111111111111');assert.equal(insert.values[2],'Verified Discord Name');});
test('non-owner cannot moderate even with a valid session',async()=>{const{default:worker}=await import('../community-server/worker.mjs'),db=database();const result=await worker.fetch(new Request('https://community.example/admin/review',{method:'POST',headers:{Authorization:'Bearer '+'a'.repeat(64)},body:JSON.stringify({id:'b'.repeat(64),status:'approved',isAdmin:true})}),{...envBase,DB:db},{});assert.equal(result.status,403);assert.equal(db.inserts.length,0);});
test('every navigation highlight is cached and repeating a state never toggles it off',()=>{const{DisplayCache}=require('../src/display-cache.cjs'),calls=[],cache=new DisplayCache('.',()=>assert.fail('Navigation rendered an upload'));cache.config={};cache.som={selectSlot:slot=>calls.push(slot),uploadOverlay:()=>assert.fail('Navigation uploaded')};for(const[name,i]of ['previous','toggle','next','fourth'].map((n,i)=>[n,i]))cache.cache.set('nav:'+name,6+i);for(let n=0;n<20;n++)for(const id of ['previous','toggle','next','fourth']){cache.show({active:true,id});cache.show({active:true,id});}assert.equal(calls.length,80);assert.deepEqual(calls.slice(0,8),[6,7,8,9,6,7,8,9]);});
test('physical sensor mapping identifies L1 and all keys uniquely',()=>{const codes=require('../src/hardware-codes.json');assert.equal(codes.length,68);assert.equal(new Set(codes).size,68);assert.equal(codes[63],59);assert.equal(codes.indexOf(64),60);});
test('localized labels follow remapped key meanings and preserve shortcuts',()=>{const{languageLabel}=require('../src/language-labels.js');const labels=Array(68).fill('');labels[26]='з';assert.equal(languageLabel('Ctrl+P',{id:'00000419',labels}),'Ctrl+з');assert.equal(languageLabel('Ctrl+P',{id:'qwerty',labels}),'Ctrl+P');});
test('L1 transitions are immediate for analog and rapid-trigger reports',()=>{
 const fs=require('node:fs'),vm=require('node:vm'),{EventEmitter}=require('node:events');let handle;
 class FakeHID extends EventEmitter{constructor(){super();handle=this;}write(){}close(){}}
 const box={module:{exports:{}},Buffer,Date,setInterval:()=>1,clearInterval:()=>{},require:name=>name==='./hid.cjs'?{HID:FakeHID,devices:()=>[{vendorId:0x361d,productId:0x200,usagePage:0xff00,usage:1,path:'test'}]}:name==='./hardware-codes.json'?require('../src/hardware-codes.json'):require(name)};
 vm.runInNewContext(fs.readFileSync(require.resolve('../src/keyboard-monitor.cjs'),'utf8'),box);
 const monitor=new box.module.exports.KeyboardMonitor(),changes=[];monitor.on('layer',value=>changes.push(value));monitor.start();
 for(const[type,length]of [[1,6],[3,8]])for(const pressed of [1,1,0]){const packet=Buffer.alloc(64);packet.set([4,length,type,59,pressed]);handle.emit('data',packet);}
 assert.deepEqual(changes,[true,false,true,false]);handle.emit('data',Buffer.from([4,6,1,59,1,0,0,0]));for(const position of [26,55])for(const pressed of [1,0]){handle.emit('data',Buffer.from([4,6,1,require('../src/hardware-codes.json')[position],pressed,0,0,0]));assert.equal(monitor.layer,true);}handle.emit('data',Buffer.from([4,6,1,59,0,0,0,0]));assert.equal(monitor.layer,false);
 handle.emit('data',Buffer.from([4,6,1,59,1,0,0,0]));handle.emit('data',Buffer.from([4,6,1,require('../src/hardware-codes.json')[33],1,0,0,0]));assert.equal(monitor.layer,false);monitor.close();
});
test('USB clients share one reader and closing a settings client leaves monitoring alive',()=>{
 const fs=require('node:fs'),vm=require('node:vm'),{EventEmitter}=require('node:events');let opened=0,closed=0,native;const messages=[];const fakeProcess=new EventEmitter();Object.assign(fakeProcess,{argv:[],connected:true,send:m=>messages.push(m),exit:()=>{}});
 class Native extends EventEmitter{constructor(){super();opened++;native=this;}write(){}close(){closed++;}}
 vm.runInNewContext(fs.readFileSync(require.resolve('../src/hid-worker.cjs'),'utf8'),{process:fakeProcess,require:()=>({HID:Native,devices:()=>[{vendorId:0x361d,productId:0x200,usagePage:0xff00,usage:1,path:'test'}]})});
 for(const key of [1,2])fakeProcess.emit('message',{op:'open',key,path:'test'});assert.equal(opened,1);
 native.emit('data',Buffer.from([4,6,1]));assert.deepEqual(messages.map(m=>m.key),[1,2]);
 fakeProcess.emit('message',{op:'close',key:2});assert.equal(closed,0);messages.length=0;native.emit('data',Buffer.from([4,6,2]));assert.deepEqual(messages.map(m=>m.key),[1]);fakeProcess.emit('disconnect');assert.equal(closed,1);
});
test('an in-flight display query cannot toggle off a newer navigation selection',async()=>{
 const{DisplayCache}=require('../src/display-cache.cjs'),calls=[],cache=new DisplayCache('.',()=>''),responses=[];
 cache.config={};cache.som={selectSlot:slot=>calls.push(slot),currentSlot:()=>new Promise(resolve=>responses.push(resolve))};cache.cache.set('nav:previous',6);cache.cache.set('nav:toggle',7);cache.show({active:true,id:'previous'});cache.selectionAt=0;
 const query=cache.reconcile();cache.show({active:true,id:'toggle'});responses[0](6);await query;assert.deepEqual(calls,[6,7]);
});
test('L1 hint adds P and slash and leaves native function-layer labels untouched',()=>{
 const{configuredSVG}=require('../src/strip.cjs');const svg=configuredSVG('idle',{slots:[null,null,null,null],indicator:{enabled:false,on:'#ffee00'},widget:{type:'off'}},{caps:false,layer:true});assert.match(svg,/>P<\/text>/);assert.match(svg,/>\/<\/text>/);assert.equal((svg.match(/fill-opacity=".65"/g)||[]).length,2);assert.doesNotMatch(svg,/Right Alt|Left Ctrl|>F1<|>Windows</);
});
test('plugin selection takes priority over a delayed L1 sensor release',()=>{const{DisplayCache}=require('../src/display-cache.cjs'),cache=new DisplayCache('.',()=>''),calls=[];cache.config={};cache.som={selectSlot:n=>calls.push(n)};cache.cache.set('layer:0',4);cache.cache.set('nav:previous',6);cache.cache.set('nav:toggle',7);cache.setLayer(true);cache.show({active:true,id:'previous'});cache.show({active:true,id:'toggle'});assert.deepEqual(calls,[4,6,7]);});
