const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
module.exports = async ({ win, state, media }) => {
  const dir = path.join(__dirname, '..', 'verification'); fs.mkdirSync(dir, { recursive: true });
  const js = async expression => {try{return await win.webContents.executeJavaScript(expression);}catch(e){throw Error(`UI check failed: ${expression}: ${e.message}`);}};
  assert.equal(await js('document.title'), 'Plugin library · Centerpiece Companion');
  assert.equal(await js('document.querySelectorAll(".plugin-tile").length'),33);
  await js('document.getElementById("plugin-search").value="no-matching-service"; document.getElementById("plugin-search").dispatchEvent(new Event("input"))');
  assert.equal(await js('document.getElementById("no-results").hidden'),false);
  await js('document.getElementById("clear-search").click()');
  assert.equal(await js('document.querySelectorAll(".plugin-tile").length'),33);
  await js('document.querySelectorAll(".slot")[1].click(); [...document.querySelectorAll(".plugin-tile")].find(e=>e.textContent.includes("YouTube")).click()');
  assert.equal(await js('document.getElementById("chosen-name").textContent'),'YouTube');
  assert.equal(await js('document.getElementById("chosen-position").textContent'),'Position 2');
  fs.writeFileSync(path.join(dir,'library.png'),(await win.webContents.capturePage()).toPNG());
  await js('location.hash="keyboard"');await new Promise(r=>setTimeout(r,100));
  for(let i=0;i<50&&!await js('!!keymap');i++)await new Promise(r=>setTimeout(r,100));
  assert.equal(await js('document.querySelectorAll(".key").length'),68);
  assert.equal(await js('document.getElementById("key-heading").textContent'),'Caps Lock');
  fs.writeFileSync(path.join(dir,'keyboard.png'),(await win.webContents.capturePage()).toPNG());
  await js('location.hash="community"');await new Promise(r=>setTimeout(r,100));
  assert.equal(await js('document.getElementById("discord-signin").disabled'),!state.community.configured);
  fs.writeFileSync(path.join(dir,'community.png'),(await win.webContents.capturePage()).toPNG());
  const unsafe={...state,community:{...state.community,features:[{id:'a'.repeat(64),username:'<img src=x onerror=alert(1)>',title:'<script>bad()</script>',body:'<svg onload=alert(1)>',created:1,status:'open',kind:'feature',color:'#000000'}]}};
  await js('renderCommunity('+JSON.stringify(unsafe)+')');
  assert.equal(await js('document.querySelectorAll("#feature-feed img,#feature-feed script,#feature-feed svg").length'),0);
  assert.equal(await js('document.getElementById("feature-feed").textContent.includes("<svg onload")'),true);
  await js('renderCommunity('+JSON.stringify(state)+')');
  await js('location.hash="widgets"');await new Promise(r=>setTimeout(r,100));
  fs.writeFileSync(path.join(dir,'widgets.png'),(await win.webContents.capturePage()).toPNG());
  await js('location.hash="media"');await new Promise(r=>setTimeout(r,100));
  assert.equal(await js('document.documentElement.scrollWidth <= innerWidth'), true);
  assert.equal(await js('typeof require'), 'undefined');
  assert.equal(await js('[...document.querySelectorAll("button")].every(b => b.textContent.trim() || b.getAttribute("aria-label"))'), true);
  const shortcutsBefore = state.shortcuts;
  await js('window.companion.shortcuts(true)');
  assert.equal(await js('document.getElementById("shortcuts").getAttribute("aria-pressed")'), 'true');
  await js(`window.companion.shortcuts(${shortcutsBefore})`);
  assert.equal(await js('document.getElementById("shortcuts").getAttribute("aria-pressed")'), String(shortcutsBefore));
  await js('window.companion.pluginMode()');
  assert.equal(await js('document.getElementById("plugin-mode").getAttribute("aria-pressed")'), 'true');
  await js('window.companion.pluginMode()');
  assert.equal(await js('document.getElementById("plugin-mode").getAttribute("aria-pressed")'), 'false');
  const actual = JSON.stringify(state);
  await js(`render(${actual})`);
  fs.writeFileSync(path.join(dir, 'desktop.png'), (await win.webContents.capturePage()).toPNG());
  const empty = { ...state, media: { available: false, message: 'Open Spotify and start a track.' }, error: 'Connection interrupted. Retry.' };
  await js(`render(${JSON.stringify(empty)})`);
  assert.equal(await js('[...document.querySelectorAll("[data-action]")].every(b=>b.disabled)'), true);
  assert.match(await js('document.getElementById("feedback").textContent'), /Connection interrupted/);
  await js('document.getElementById("inspect").focus()');
  assert.equal(await js('document.activeElement.id'), 'inspect');
  assert.notEqual(await js('getComputedStyle(document.documentElement).scrollbarColor'), 'auto');
  win.setSize(560, 900);
  const long = { ...state, media: { ...state.media, available: true, title: 'A long track title / 日本語 / café / '.repeat(5), artist: 'Long artist name '.repeat(8), status: 'Paused' } };
  await js(`render(${JSON.stringify(long)})`);
  await new Promise(resolve => setTimeout(resolve, 200));
  assert.equal(await js('document.documentElement.scrollWidth <= innerWidth'), true);
  fs.writeFileSync(path.join(dir, 'narrow.png'), (await win.webContents.capturePage()).toPNG());
  await js('location.hash="library"');await new Promise(r=>setTimeout(r,100));
  assert.equal(await js('document.documentElement.scrollWidth <= innerWidth'),true);
  fs.writeFileSync(path.join(dir,'library-narrow.png'),(await win.webContents.capturePage()).toPNG());
  let pauseVerified = false;
  if (state.media.available && state.media.status === 'Paused') {
    await media.request('pause');
    assert.equal((await media.request('status')).status, 'Paused');
    pauseVerified = true;
  }
  fs.writeFileSync(path.join(dir, 'desktop-checks.json'), JSON.stringify({ passed: true, deviceDetected: !!state.device.keyboard, displayDetected: !!state.device.display, spotifyAvailable: !!state.media.available, idempotentPauseVerified: pauseVerified, controlsNotLiveTested: ['toggle', 'next', 'previous'], displayIntegration: false }, null, 2));
  console.log('Desktop state, isolation, failure, focus, scrollbar and narrow-layout checks passed.');
};
