import {test} from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,sign} from 'node:crypto';import {discordInteraction,approvalButtons} from '../community-server/discord-interactions.mjs';
const keys=generateKeyPairSync('ed25519'),publicHex=keys.publicKey.export({format:'der',type:'spki'}).subarray(-32).toString('hex'),id='a'.repeat(64);
function fixture(){let writes=0,pending=true;const env={DISCORD_PUBLIC_KEY:publicHex,DISCORD_CLIENT_ID:'1486218048095649933',DISCORD_OWNER_ID:'399065450555899905',DB:{prepare(){return{bind(){return{async first(){writes++;if(!pending)return null;pending=false;return{id,title:'Skin'};}};}};}}};return{env,writes:()=>writes};}
function request(event,age=0){const timestamp=String(Math.floor(Date.now()/1000)-age),body=JSON.stringify(event),signature=sign(null,Buffer.from(timestamp+body),keys.privateKey).toString('hex');return new Request('https://community.test/discord/interactions',{method:'POST',headers:{'X-Signature-Timestamp':timestamp,'X-Signature-Ed25519':signature},body});}
const click=owner=>({application_id:'1486218048095649933',type:3,data:{component_type:2,custom_id:'skin:approved:'+id},member:{user:{id:owner}}});
test('signature verification allows Discord ping and rejects tampering or stale requests',async()=>{const f=fixture();assert.deepEqual(await(await discordInteraction(request({application_id:f.env.DISCORD_CLIENT_ID,type:1}),f.env)).json(),{type:1});assert.equal((await discordInteraction(request(click(f.env.DISCORD_OWNER_ID),600),f.env)).status,401);const r=request(click(f.env.DISCORD_OWNER_ID));const bad=new Request(r.url,{method:'POST',headers:r.headers,body:'{}'});assert.equal((await discordInteraction(bad,f.env)).status,401);assert.equal(f.writes(),0);});
test('a valid Discord signature cannot let another user approve',async()=>{const f=fixture(),r=await discordInteraction(request(click('123456789012345678')),f.env);assert.match((await r.json()).data.content,/Only the community owner/);assert.equal(f.writes(),0);});
test('owner approval is atomic and a repeat cannot change it',async()=>{const f=fixture(),r=await discordInteraction(request(click(f.env.DISCORD_OWNER_ID)),f.env);assert.equal((await r.json()).type,7);const again=await discordInteraction(request(click(f.env.DISCORD_OWNER_ID)),f.env);assert.match((await again.json()).data.content,/already reviewed/);});
test('buttons have explicit green and red actions without links or credentials',()=>{const buttons=approvalButtons(id)[0].components;assert.deepEqual(buttons.map(x=>x.style),[3,4]);assert.equal(buttons.every(x=>x.custom_id.length<=100),true);assert.throws(()=>approvalButtons('../x'));});
