const{app,BrowserWindow}=require('electron'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
app.setPath('userData',path.join(app.getPath('temp'),'centerpiece-feature-verification'));
app.whenReady().then(async()=>{try{
 const win=new BrowserWindow({show:false,width:1320,height:920,webPreferences:{backgroundThrottling:false,offscreen:true,preload:path.join(__dirname,'features-preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:false}}),errors=[];
 win.webContents.on('console-message',(_event,level,message)=>{if(level>=3&&!message.includes('Content-Security-Policy'))errors.push(message);});
 await win.loadFile(path.join(__dirname,'../src/index.html'));const js=source=>win.webContents.executeJavaScript(source),wait=()=>new Promise(r=>setTimeout(r,120));const click=async id=>{await js(`document.getElementById(${JSON.stringify(id)}).click()`);await wait();};
 await click('strip-visibility');assert.equal(await js('deskCurrent.desk.config.stripEnabled'),false);assert.equal(await js('document.getElementById("strip-visibility").getAttribute("aria-checked")'),'false');assert.equal(await js('document.getElementById("plugin-mode").disabled'),true);await click('strip-visibility');assert.equal(await js('deskCurrent.desk.config.stripEnabled'),true);await js("location.hash='widgets'");await wait();assert.equal(await js('document.querySelectorAll(".favorite-row").length'),11);
 await js("document.querySelectorAll('.favorite-row input').forEach(i=>i.checked=false);document.getElementById('favorite-clock').checked=true;document.getElementById('favorite-spotify').checked=true;document.querySelector('[aria-label=\"Move Local time up\"]').click()");
 assert.equal(await js('document.activeElement.getAttribute("aria-label")'),'Move Local time up');await click('save-favorites');assert.equal(await js('JSON.stringify(draft.widgetOrder)'),JSON.stringify(['clock','spotify']));
 await js("document.getElementById('timer-minutes').value=1");await click('timer-start');assert.match(await js('document.getElementById("timer-status").textContent'),/Running/);await click('timer-toggle');assert.match(await js('document.getElementById("timer-status").textContent'),/Paused/);await click('timer-show');assert.equal(await js('draft.widget.type'),'timer');
 await js("location.hash='profiles';document.getElementById('profile-new-name').value='Streaming'");await click('profile-create');assert.equal(await js('document.getElementById("profile-name").value'),'Streaming');await click('profile-pick');assert.equal(await js('document.getElementById("profile-app").value'),'obs64.exe');await click('profile-link');await click('profiles-auto');assert.equal(await js('deskCurrent.profiles.enabled'),true);await click('profile-load');assert.equal(await js('deskCurrent.profiles.enabled'),false);
 const dir=path.join(__dirname,'../verification');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'profiles.png'),(await win.webContents.capturePage()).toPNG());
 await click('profile-remove');assert.equal(await js('document.activeElement.id'),'profile-cancel');assert.equal(await js('document.getElementById("profile-confirm").open'),true);await click('profile-cancel');assert.equal(await js('document.activeElement.id'),'profile-remove');
 await js("location.hash='widgets';document.getElementById('widget-type').value='weather';document.getElementById('widget-type').dispatchEvent(new Event('change'));window.weatherNode=document.querySelector('.weather-motion');renderRelease(deskCurrent)");assert.equal(await js("weatherNode===document.querySelector('.weather-motion')"),true);assert.equal(await js("getComputedStyle(weatherNode).fontSize"),'42px');await wait();fs.writeFileSync(path.join(dir,'features-widgets.png'),(await win.webContents.capturePage()).toPNG());
 win.setSize(560,900);for(const page of ['widgets','profiles','library']){await js(`location.hash='${page}'`);await wait();assert.equal(await js('document.documentElement.scrollWidth<=innerWidth'),true,page+' overflow');fs.writeFileSync(path.join(dir,page+'-feature-narrow.png'),(await win.webContents.capturePage()).toPNG());}
 await js("location.hash='profiles'");await click('profile-remove');await click('profile-delete');assert.equal(await js('deskCurrent.profiles.items.length'),0);assert.equal(await js('document.getElementById("profile-confirm").open'),false);
 assert.deepEqual(errors,[]);console.log('Profiles, favorites, timer, weather preview stability, confirmation focus and narrow layouts passed.');win.destroy();app.exit(0);
 }catch(e){console.error(e);app.exit(1);}});
