const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const{Countdown}=require('../src/countdown.cjs'),{validateOrder,nextWidget}=require('../src/widget-cycle.cjs');
const{Profiles,snapshot,merge,appName}=require('../src/profiles.cjs'),{Workspace,defaults}=require('../src/workspace.cjs');
test('favorite rotation validates duplicates, empty choices, and independent cycling',()=>{assert.throws(()=>validateOrder([]));assert.throws(()=>validateOrder(['spotify','spotify']));assert.throws(()=>validateOrder(['follow']));assert.equal(nextWidget('clock',['timer','clock']),'timer');assert.equal(nextWidget('spotify',['weather']),'weather');assert.equal(nextWidget('off'),'spotify');assert.deepEqual(validateOrder(undefined),['spotify','clock','weather','cpu','gpu','mic','twitch','text','off']);});
test('countdown preserves fractional pause time, resumes, expires and resets without actions',()=>{let now=0;const timer=new Countdown(()=>now);timer.command('start',1);now=15250;assert.equal(timer.view().remaining,45);timer.command('toggle');now=100000;assert.equal(timer.view().remaining,45);timer.command('toggle');now+=44750;assert.equal(timer.view().finished,true);assert.equal(timer.view().running,false);timer.command('reset');assert.equal(timer.view().remaining,60);assert.equal(timer.view().running,false);assert.throws(()=>timer.command('start',0));assert.throws(()=>timer.command('start',Infinity));assert.throws(()=>timer.command('unknown'));});
function harness(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'profile-test-'));const w={config:Workspace.prototype.validate(defaults()),validate:Workspace.prototype.validate};let allowed=true,calls=0;const profiles=new Profiles(dir,w,async config=>{calls++;w.config=w.validate(config);},()=>allowed);return{dir,w,profiles,setAllowed:v=>allowed=v,calls:()=>calls,close(){for(const file of fs.readdirSync(dir))fs.unlinkSync(path.join(dir,file));fs.rmdirSync(dir);}};}
test('profiles retain only display preferences and restore default without touching keymap, geometry or connections',async()=>{const h=harness();try{h.w.config.secret='must-not-store';h.w.config.widget.type='spotify';const id=h.profiles.save('Music');h.profiles.link(id,'spotify.exe');h.w.config.widget.type='clock';h.profiles.enable(true);h.setAllowed(false);await h.profiles.tick('spotify.exe');await h.profiles.tick('spotify.exe');assert.equal(h.calls(),0);h.setAllowed(true);await h.profiles.tick('spotify.exe');await h.profiles.tick('spotify.exe');assert.equal(h.w.config.widget.type,'spotify');assert.equal(h.profiles.active,id);await h.profiles.tick('spotify.exe');assert.equal(h.calls(),1);h.w.config.widget.x=1500;await h.profiles.tick('notepad.exe');await h.profiles.tick('notepad.exe');assert.equal(h.w.config.widget.type,'clock');assert.equal(h.w.config.widget.x,1500);assert.equal(h.profiles.active,'default');assert.ok(!fs.readFileSync(h.profiles.file,'utf8').includes('must-not-store'));const reloaded=new Profiles(h.dir,h.w,async()=>{});assert.equal(reloaded.data.enabled,true);assert.equal(reloaded.data.items[0].id,id);await h.profiles.load(id);assert.equal(h.profiles.data.enabled,false);}finally{h.close();}});
test('profile names and app links are bounded and unique; failures stop automatic retry storms',async()=>{const h=harness();try{const one=h.profiles.save('One'),two=h.profiles.save('Two');assert.throws(()=>h.profiles.save('one'));assert.throws(()=>h.profiles.save(''));assert.throws(()=>appName('C:\\path\\app.exe'));h.profiles.link(one,'obs64.exe');assert.throws(()=>h.profiles.link(two,'obs64.exe'));h.profiles.enable(true);h.profiles.apply=async()=>{throw Error('Display unavailable');};await h.profiles.tick('obs64.exe');await h.profiles.tick('obs64.exe');assert.equal(h.profiles.data.enabled,false);assert.match(h.profiles.error,/Display unavailable/);h.profiles.remove(one);assert.equal(h.profiles.data.items.length,1);}finally{h.close();}});
test('weather animation changes gently and static preference freezes SVG frames; Spotify art is larger',()=>{const{weatherIcon,detailSVG}=require('../src/widgets.cjs');for(const kind of ['sun','cloud','rain','snow','storm'])assert.notEqual(weatherIcon(kind,0),weatherIcon(kind,2));const config=Workspace.prototype.validate(defaults());config.widget.type='weather';config.weatherMotion=false;const data={live:{weather:{temperature:20,unit:'°C',label:'Rain',icon:'rain'}}};const original=Date.now;try{Date.now=()=>0;const first=detailSVG(config,data);Date.now=()=>4000;assert.equal(detailSVG(config,data),first);config.weatherMotion=true;assert.notEqual(detailSVG(config,data),first);}finally{Date.now=original;}config.widget.type='spotify';assert.match(detailSVG(config,{media:{art:'data:image/png;base64,AA==',duration:100}}),/width="54" height="54"/);});
test('OBS widget reads both statuses and discards results after disconnect',async()=>{const w=Object.create(Workspace.prototype);w.obs={call:async name=>({outputActive:name==='GetStreamStatus',outputDuration:90000})};await w.sampleObs();assert.equal(w.obsStatus.streaming,true);assert.equal(w.obsStatus.recording,false);assert.equal(w.obsStatus.streamSeconds,90);let done;w.obs={call:()=>new Promise(r=>done=r)};const pending=w.sampleObs();w.obs=null;done({outputActive:false,outputDuration:0});/* first promise is still pending; exercise timeout cleanup on unavailable connection */await pending;assert.equal(w.obsSampling,false);});
