const{test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const{KeyboardSkins}=require('../src/keyboard-skins.cjs');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'skin-switch-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const state={active:4,changed:[],slots:Object.fromEntries([1,2,3,4,5].map(i=>[i,{fileName:'Skin '+i,fileID:'identity-'+i}]))};let match;
 const som={identity:'test-keyboard',close(){},wait(fn,trigger){return new Promise((resolve,reject)=>{match=(c,p)=>{try{const result=fn(c,p);if(result!==undefined)resolve(result);}catch(e){reject(e);}};trigger();});},send(c,p=Buffer.alloc(0)){if(c===48){if(p.length){state.active=p[0];state.changed.push(p[0]);if(state.fail===p[0])return match(c,Buffer.from([p[0],1]));}match(c,Buffer.from([state.active]));}if(c===8)match(c,Buffer.concat([p,Buffer.from(JSON.stringify(state.slots[p[0]]))]));}};
 const service=new KeyboardSkins(dir,()=>som);service.thumbnail=async()=>null;return{service,state,dir};}
test('captures default before switching and returns without replacing skin files',async t=>{const{service,state}=setup(t);const initial=await service.action('read');assert.equal(initial.defaultSlot,4);assert.deepEqual(state.changed,[]);await service.action('select',{slot:1});assert.equal(state.active,1);await service.action('default');assert.equal(state.active,4);assert.deepEqual(state.changed,[1,4]);});
test('refuses an empty slot, an invalid slot and an externally replaced default',async t=>{const{service,state}=setup(t);await service.action('read');state.slots[2]={empty:true};await assert.rejects(service.action('select',{slot:2}),/empty/);await assert.rejects(service.action('select',{slot:6}),/1–5/);state.slots[4].fileID='different-file';await assert.rejects(service.action('default'),/replaced/);assert.deepEqual(state.changed,[]);});
test('failed switch attempts restore the previous active slot',async t=>{const{service,state}=setup(t);await service.action('read');state.fail=1;await assert.rejects(service.action('select',{slot:1}),/could not activate/);assert.equal(state.active,4);});
test('default changes retain original startup identity',async t=>{const{service}=setup(t);await service.action('select',{slot:1});const result=await service.action('set-default');assert.equal(result.defaultSlot,1);assert.equal(result.originalSlot,4);});
test('selected skin persists separately from default and reads never restore default',async t=>{const{service,state,dir}=setup(t);await service.action('select',{slot:2});const files=fs.readdirSync(path.join(dir,'keyboard-skins'));const stored=JSON.parse(fs.readFileSync(path.join(dir,'keyboard-skins',files.find(f=>f.endsWith('.json'))),'utf8'));assert.equal(stored.selected.slot,2);assert.equal(stored.default.slot,4);const later=await service.action('read');assert.equal(later.active,2);assert.equal(later.lastSelectedSlot,2);assert.equal(later.selectionMatches,true);assert.deepEqual(state.changed,[2]);state.active=3;const external=await service.action('read');assert.equal(external.active,3);assert.equal(external.lastSelectedSlot,2);assert.equal(external.selectionMatches,false);assert.deepEqual(state.changed,[2]);});
test('failed selection keeps the last successful selection record',async t=>{const{service,state}=setup(t);await service.action('read');state.fail=1;await assert.rejects(service.action('select',{slot:1}));const result=await service.action('read');assert.equal(result.lastSelectedSlot,4);assert.equal(result.defaultSlot,4);});
