const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),vm=require('node:vm'),{EventEmitter}=require('node:events');
const{collectSetupReport}=require('../src/setup-report.cjs'),{requireCleanSetup,validateResponse}=require('../src/studio-response.cjs');
test('setup check never treats absent, malformed or pending status as permission to write',async()=>{for(const value of [undefined,null,'false',1,true]){const calls=[];await assert.rejects(()=>requireCleanSetup({request:async r=>{calls.push(r);return{keymap:{checkUnsavedChanges:value}};}}));assert.deepEqual(calls,[{keymap:{checkUnsavedChanges:true}}]);}await requireCleanSetup({request:async()=>({keymap:{checkUnsavedChanges:false}})});assert.throws(()=>validateResponse({keymap:{checkUnsavedChanges:true}},{keymap:{getKeymap:{}}}),/unexpected/);assert.throws(()=>validateResponse({keymap:{checkUnsavedChanges:true}},{meta:{simpleError:0}}),/protocol error/);});
test('independent Studio clients have unique IDs and handle out-of-order responses correctly',async()=>{
 const packets=[],handles=[];class Handle extends EventEmitter{constructor(){super();handles.push(this);}write(packet){packets.push(Buffer.from(packet));}close(){}}
 const fakeHid={devices:()=>[{vendorId:0x361d,productId:0x200,usagePage:0xff00,usage:1,path:'test'}],HID:Handle};const box={module:{exports:{}},Buffer,Promise,setTimeout,clearTimeout,__dirname:path.resolve(__dirname,'../src'),require:name=>name==='./hid.cjs'?fakeHid:name==='./studio-response.cjs'?require('../src/studio-response.cjs'):require(name)};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/studio.cjs'),'utf8'),box);const{Studio}=box.module.exports,a=new Studio(),b=new Studio();
 const root=require('protobufjs').loadSync(path.join(__dirname,'../src/proto/studio.proto')),request=root.lookupType('zmk.studio.Request'),response=root.lookupType('zmk.studio.Response');
 function unframe(packet){const out=[];let escape=false;for(const n of packet.subarray(3,3+packet[1]-3)){if(escape){out.push(n);escape=false;}else if(n===0xac)escape=true;else if(![0xab,0xad].includes(n))out.push(n);}return request.decode(Buffer.from(out));}
 function reply(id,value){const bytes=response.encode({requestResponse:{requestId:id,keymap:{checkUnsavedChanges:value}}}).finish(),frame=[0xab];for(const n of bytes){if([0xab,0xac,0xad].includes(n))frame.push(0xac);frame.push(n);}frame.push(0xad);const packet=Buffer.alloc(64);packet[0]=4;packet[1]=frame.length+2;packet[2]=16;Buffer.from(frame).copy(packet,3);for(const h of handles)h.emit('data',packet);}
 try{const pa=a.request({keymap:{checkUnsavedChanges:true}}),pb=b.request({keymap:{checkUnsavedChanges:true}});const ia=unframe(packets[0]).requestId,ib=unframe(packets[1]).requestId;assert.notEqual(ia,ib);reply(ib,true);reply(ia,false);assert.equal((await pa).keymap.checkUnsavedChanges,false);assert.equal((await pb).keymap.checkUnsavedChanges,true);}finally{a.close();b.close();}
});
test('report repeats read-only queries, summarizes stable keymaps, and excludes private fields',async()=>{const requests=[],dir=fs.mkdtempSync(path.join(os.tmpdir(),'setup-report-'));let closed=false;const map={layers:[{id:0,name:'Private name',bindings:Array.from({length:68},()=>({behaviorId:50397,param1:123}))},{id:1,bindings:Array.from({length:68},()=>({behaviorId:60498}))}]};map.layers[0].bindings[63].param1=1;
 class Studio{constructor(){this.serial='PRIVATE-SERIAL';}close(){closed=true;}async request(r){requests.push(r);if(r.keymap.checkUnsavedChanges)return{keymap:{checkUnsavedChanges:true}};if(r.keymap.getKeymap)return{keymap:{getKeymap:map}};if(r.keymap.getPhysicalLayouts)return{keymap:{getPhysicalLayouts:{layouts:[{name:'Private layout',keys:Array(68).fill({})}],activeLayoutIndex:0}}};throw Error('Unexpected request');}}
 try{const result=await collectSetupReport({version:'test',directory:dir,Studio,inspect:async()=>({keyboard:true,display:true,keyboardVersion:'1.2.3',displayVersion:'4.5.6'}),wait:async()=>{}});assert.equal(result.classification,'pending_reported_consistently');assert.equal(result.keymap.stable,true);assert.equal(result.compatibility.layout68,true);assert.equal(result.compatibility.pluginKey,'stock');assert.equal(closed,true);assert.equal(requests.length,6);for(const r of requests)assert.ok(Object.keys(r.keymap).every(k=>['checkUnsavedChanges','getKeymap','getPhysicalLayouts'].includes(k)));assert.doesNotMatch(JSON.stringify(result),/PRIVATE-SERIAL|Private name|Private layout|param1|behaviorId|bindings/);assert.deepEqual(fs.readdirSync(dir),[]);}finally{fs.rmdirSync(dir);}});
test('report separates missing responses from consistently false status',async()=>{for(const pending of [false,undefined]){class Studio{close(){}async request(r){return r.keymap.checkUnsavedChanges?{keymap:{checkUnsavedChanges:pending}}:{};}}const report=await collectSetupReport({version:'test',directory:'missing-setup-report-directory',Studio,inspect:async()=>({}),wait:async()=>{}});assert.equal(report.classification,pending===false?'no_pending_reported':'query_failed');assert.ok(report.queries.some(q=>q.status==='failed'));}});
