const test=require('node:test'),assert=require('node:assert/strict');
test('Discord callback exchanges identity with Workers-compatible requests and rejects redirects',async()=>{
 const {default:worker}=await import('../community-server/worker.mjs');const original=global.fetch;const writes=[];let redirect=false;
 const env={PUBLIC_ORIGIN:'https://community.example',DISCORD_CLIENT_ID:'123456789012345678',DISCORD_CLIENT_SECRET:'placeholder',DB:{prepare(sql){return{bind(...values){this.values=values;return this;},async first(){if(sql.includes('rate_limits'))return{count:1};if(sql.includes('DELETE FROM oauth_states'))return{challenge:'A'.repeat(43),client_state:'b'.repeat(64),port:49152};return null;},async run(){writes.push({sql,values:this.values});}};}}};
 global.fetch=async(url,opts)=>{assert.equal(opts.redirect,'manual');if(redirect)return new Response(null,{status:302,headers:{Location:'https://untrusted.example'}});return Response.json(String(url).endsWith('/oauth2/token')?{access_token:'test-token'}:{id:'111111111111111111',username:'Verified user'});};
 const request=()=>new Request('https://community.example/auth/callback?state='+'a'.repeat(64)+'&code=test-code',{headers:{Cookie:'oauth='+'c'.repeat(64)}});
 try{const ok=await worker.fetch(request(),env,{});assert.equal(ok.status,302);assert.equal(new URL(ok.headers.get('location')).origin,'http://127.0.0.1:49152');assert.equal(writes.length,1);assert.equal(writes[0].values[2],'111111111111111111');redirect=true;assert.equal((await worker.fetch(request(),env,{})).status,502);assert.equal(writes.length,1);}finally{global.fetch=original;}
});
test('installed updater becomes available for checking immediately',()=>{
 const fs=require('node:fs'),vm=require('node:vm'),{EventEmitter}=require('node:events');const fake=new EventEmitter();let checks=0;fake.app={};fake.checkForUpdates=async()=>{checks++;fake.emit('update-not-available');};const box={module:{exports:{}},process:{resourcesPath:'installed'},require:n=>n==='electron-updater'?{NsisUpdater:class{constructor(){return fake;}}}:n==='electron-updater/out/ElectronAppAdapter'?{ElectronAppAdapter:class{}}:n==='./update-storage.cjs'?{updateStorage:()=> 'D:\\Updates'}:n==='fs'?{existsSync:()=>true}:n==='./distribution.json'?{githubOwner:'owner',githubRepo:'repo'}:require(n)};vm.runInNewContext(fs.readFileSync(require.resolve('../src/updates.cjs'),'utf8'),box);const updates=new box.module.exports.Updates({isPackaged:true,getVersion:()=> '0.3.0-preview.2'});updates.start();assert.equal(updates.state.status,'idle');return updates.check().then(()=>{assert.equal(checks,1);assert.equal(updates.state.status,'current');});
});
test('display Apply waits for current live frame and preserves queued ordering',async()=>{const{DisplayTasks}=require('../src/display-tasks.cjs');const cache={updating:true,watching:false},queue=new DisplayTasks(cache),calls=[];const a=queue.run(async()=>{calls.push('clock');});const b=queue.run(async()=>{calls.push('weather');});assert.equal(queue.paused,true);await new Promise(r=>setTimeout(r,25));assert.deepEqual(calls,[]);cache.updating=false;await Promise.all([a,b]);assert.deepEqual(calls,['clock','weather']);assert.equal(queue.paused,false);await assert.rejects(queue.run(()=>{throw Error('failed');}));await queue.run(()=>calls.push('spotify'));assert.equal(queue.paused,false);});
test('invalid submissions do not consume the submission allowance',async()=>{const{default:worker}=await import('../community-server/worker.mjs');let charged=0;const db={prepare(sql){return{bind(...args){this.args=args;return this;},async first(){if(sql.includes('rate_limits')){if(this.args[0].startsWith('submit:'))charged++;return{count:1};}if(sql.includes('FROM sessions'))return{user_id:'111111111111111111',username:'Tester',expires:Math.floor(Date.now()/1000)+30*86400};return null;}};}};const env={PUBLIC_ORIGIN:'https://community.example',DISCORD_CLIENT_ID:'123456789012345678',DISCORD_CLIENT_SECRET:'placeholder',DB:db};for(let i=0;i<7;i++){const r=await worker.fetch(new Request(env.PUBLIC_ORIGIN+'/submit',{method:'POST',headers:{Authorization:'Bearer '+'a'.repeat(64)},body:JSON.stringify({kind:'feature',title:'Valid title',body:'short'})}),env,{});assert.equal(r.status,400);}assert.equal(charged,0);});
test('saved encrypted session restores identity before feeds and survives temporary failures',async()=>{const fs=require('node:fs'),os=require('node:os'),path=require('node:path');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'community-test-'));const original=global.fetch;try{fs.writeFileSync(path.join(dir,'community-session.bin'),Buffer.from('opaque-encrypted-fixture'));const{Community}=require('../src/community.cjs');const client=new Community(dir,{}, {isEncryptionAvailable:()=>true,decryptString:()=> 'a'.repeat(64)});let calls=[];global.fetch=async url=>{calls.push(new URL(url).pathname);return Response.json(new URL(url).pathname==='/me'?{id:'111111111111111111',name:'Tester',isAdmin:false}:{items:[]});};await client.refresh();assert.equal(calls[0],'/me');assert.equal(client.state.user.name,'Tester');global.fetch=async()=>{throw Error('Offline');};await client.refresh();assert.equal(client.state.user.name,'Tester');assert.equal(fs.existsSync(client.file),true);}finally{global.fetch=original;fs.unlinkSync(path.join(dir,'community-session.bin'));fs.rmdirSync(dir);}});
test('active sessions renew and real rate limits include a retry interval',async()=>{const{default:worker}=await import('../community-server/worker.mjs');let renewed=false,blocked=false;const env={PUBLIC_ORIGIN:'https://community.example',DISCORD_CLIENT_ID:'123456789012345678',DISCORD_CLIENT_SECRET:'placeholder',DB:{prepare(sql){return{bind(){return this;},async first(){if(sql.includes('rate_limits'))return{count:blocked?91:1};if(sql.includes('FROM sessions'))return{user_id:'111111111111111111',username:'Tester',expires:Math.floor(Date.now()/1000)+86400};return null;},async run(){if(sql.includes('UPDATE sessions'))renewed=true;}};}}};const req=()=>new Request(env.PUBLIC_ORIGIN+'/me',{headers:{Authorization:'Bearer '+'a'.repeat(64)}});assert.equal((await worker.fetch(req(),env,{})).status,200);assert.equal(renewed,true);blocked=true;const result=await worker.fetch(req(),env,{});assert.equal(result.status,429);assert.ok(Number(result.headers.get('Retry-After'))>0);});
