const test=require('node:test'),assert=require('node:assert/strict');
test('Discord callback exchanges identity with Workers-compatible requests and rejects redirects',async()=>{
 const {default:worker}=await import('../community-server/worker.mjs');const original=global.fetch;const writes=[];let redirect=false;
 const env={PUBLIC_ORIGIN:'https://community.example',DISCORD_CLIENT_ID:'123456789012345678',DISCORD_CLIENT_SECRET:'placeholder',DB:{prepare(sql){return{bind(...values){this.values=values;return this;},async first(){if(sql.includes('rate_limits'))return{count:1};if(sql.includes('DELETE FROM oauth_states'))return{challenge:'A'.repeat(43),client_state:'b'.repeat(64),port:49152};return null;},async run(){writes.push({sql,values:this.values});}};}}};
 global.fetch=async(url,opts)=>{assert.equal(opts.redirect,'manual');if(redirect)return new Response(null,{status:302,headers:{Location:'https://untrusted.example'}});return Response.json(String(url).endsWith('/oauth2/token')?{access_token:'test-token'}:{id:'111111111111111111',username:'Verified user'});};
 const request=()=>new Request('https://community.example/auth/callback?state='+'a'.repeat(64)+'&code=test-code',{headers:{Cookie:'oauth='+'c'.repeat(64)}});
 try{const ok=await worker.fetch(request(),env,{});assert.equal(ok.status,302);assert.equal(new URL(ok.headers.get('location')).origin,'http://127.0.0.1:49152');assert.equal(writes.length,1);assert.equal(writes[0].values[2],'111111111111111111');redirect=true;assert.equal((await worker.fetch(request(),env,{})).status,502);assert.equal(writes.length,1);}finally{global.fetch=original;}
});
test('installed updater becomes available for checking immediately',()=>{
 const fs=require('node:fs'),vm=require('node:vm'),{EventEmitter}=require('node:events');const fake=new EventEmitter();let checks=0;fake.checkForUpdates=async()=>{checks++;fake.emit('update-not-available');};const box={module:{exports:{}},process:{resourcesPath:'installed'},require:n=>n==='electron-updater'?{autoUpdater:fake}:n==='fs'?{existsSync:()=>true}:n==='./distribution.json'?{githubOwner:'owner',githubRepo:'repo'}:require(n)};vm.runInNewContext(fs.readFileSync(require.resolve('../src/updates.cjs'),'utf8'),box);const updates=new box.module.exports.Updates({isPackaged:true,getVersion:()=> '0.3.0-preview.2'});updates.start();assert.equal(updates.state.status,'idle');return updates.check().then(()=>{assert.equal(checks,1);assert.equal(updates.state.status,'current');});
});
test('display Apply waits for current live frame and preserves queued ordering',async()=>{const{DisplayTasks}=require('../src/display-tasks.cjs');const cache={updating:true,watching:false},queue=new DisplayTasks(cache),calls=[];const a=queue.run(async()=>{calls.push('clock');});const b=queue.run(async()=>{calls.push('weather');});assert.equal(queue.paused,true);await new Promise(r=>setTimeout(r,25));assert.deepEqual(calls,[]);cache.updating=false;await Promise.all([a,b]);assert.deepEqual(calls,['clock','weather']);assert.equal(queue.paused,false);await assert.rejects(queue.run(()=>{throw Error('failed');}));await queue.run(()=>calls.push('spotify'));assert.equal(queue.paused,false);});
