const test=require('node:test'),assert=require('node:assert/strict');const {Startup,openCompanion,hideCompanion}=require('../src/startup.cjs');
function startupFixture(t,initial={openAtLogin:false}){const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),directory=fs.mkdtempSync(path.join(os.tmpdir(),'startup-default-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));let setting=initial;const writes=[],app={isPackaged:true,getLoginItemSettings:()=>setting,setLoginItemSettings:value=>{writes.push(value);setting={...value,executableWillLaunchAtLogin:value.openAtLogin};}};return{directory,app,writes,make:()=>new Startup(app,'D:\\Companion.exe',directory),external:value=>setting=value};}
test('first installed launch defaults to quiet startup once and retains an explicit opt out across updates',t=>{const f=startupFixture(t);assert.equal(f.make().initialize().enabled,true);assert.deepEqual(f.writes[0].args,['--background']);assert.equal(f.writes.length,1);f.make().initialize();assert.equal(f.writes.length,1);f.make().set(false);assert.equal(f.make().initialize().enabled,false);assert.equal(f.writes.length,2);});
test('defaults preserve a Windows-disabled existing entry and later external changes',t=>{const f=startupFixture(t,{openAtLogin:true,executableWillLaunchAtLogin:false});assert.equal(f.make().initialize().enabled,false);assert.equal(f.writes.length,0);f.external({openAtLogin:false});f.make().initialize();assert.equal(f.writes.length,0);});
test('development preview never registers startup or writes a default preference',t=>{const f=startupFixture(t);f.app.isPackaged=false;assert.deepEqual(f.make().initialize(),{available:false,enabled:false});assert.equal(f.writes.length,0);assert.deepEqual(require('node:fs').readdirSync(f.directory),[]);});
test('paths with spaces are quoted for Windows readback but not double-quoted when saved',()=>{const exe='D:\\My Apps\\Centerpiece Companion\\Companion.exe';let saved=false;const startup=new Startup({isPackaged:true,setLoginItemSettings:options=>{assert.equal(options.path,exe);saved=options.openAtLogin;},getLoginItemSettings:options=>({openAtLogin:saved,executableWillLaunchAtLogin:saved&&options.path==='"'+exe+'"'})},exe);assert.equal(startup.set(true).enabled,true);assert.equal(startup.read().enabled,true);assert.equal(startup.set(false).enabled,false);});
test('startup toggles use the installed executable with the background argument and read back Windows state',()=>{let setting={openAtLogin:false};const app={isPackaged:true,getLoginItemSettings:o=>{assert.equal(o.path,'"D:\\Apps\\Companion.exe"');assert.deepEqual(o.args,['--background']);return setting;},setLoginItemSettings:o=>{setting=o;}};const startup=new Startup(app,'D:\\Apps\\Companion.exe');assert.equal(startup.read().enabled,false);assert.equal(startup.set(true).enabled,true);assert.equal(startup.set(false).enabled,false);assert.throws(()=>startup.set('yes'));});
test('startup reports Windows-disabled entries and refuses development registrations',()=>{const startup=new Startup({isPackaged:true,getLoginItemSettings:()=>({openAtLogin:true,executableWillLaunchAtLogin:false}),setLoginItemSettings:()=>{}},'D:\\App.exe');assert.equal(startup.read().enabled,false);assert.throws(()=>startup.set(true),/Windows did not enable/);assert.throws(()=>new Startup({isPackaged:false},'dev.exe').set(true),/installed app/);});
test('tray close removes taskbar entry and explicit open restores it',()=>{const calls=[],win=Object.fromEntries(['setSkipTaskbar','show','restore','focus','hide'].map(n=>[n,(...args)=>calls.push([n,...args])]));hideCompanion(win);openCompanion(win);assert.deepEqual(calls,[['hide'],['setSkipTaskbar',true],['setSkipTaskbar',false],['show'],['restore'],['focus']]);});
test('background duplicate launches cannot reveal the window and in-app installation stays silent',()=>{const fs=require('node:fs');assert.match(fs.readFileSync(require.resolve('../src/main.cjs'),'utf8'),/if\(args.includes\('--background'\)\)return;/);assert.match(fs.readFileSync(require.resolve('../src/updates.cjs'),'utf8'),/quitAndInstall\(true,true\)/);const installer=fs.readFileSync(require('node:path').join(__dirname,'../build/installer.nsh'),'utf8').split('!macro customInstall')[1];assert.ok(installer.indexOf('ReadINIStr')<installer.indexOf('StrCpy $UpdateRoot'));});
