'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {validateRuntime}=require('../src/studio-unreal-cook.cjs');
const {UnrealDock}=require('../src/unreal-dock.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'studio-runtime-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.mkdirSync(path.join(dir,'Plugins'),{recursive:true});fs.cpSync(path.join(__dirname,'../sdk/Device/Plugins/SkinApi'),path.join(dir,'Plugins/SkinApi'),{recursive:true});fs.writeFileSync(path.join(dir,'CenterpieceDevice.uproject'),JSON.stringify({Plugins:[{Name:'SkinApi',Enabled:true}]}));return dir;}
test('saved Blueprint project preserves the installed keyboard API contract',t=>{const dir=fixture(t);assert.doesNotThrow(()=>validateRuntime(dir));fs.writeFileSync(path.join(dir,'CenterpieceDevice.uproject'),JSON.stringify({Modules:[{Name:'CustomGame',Type:'Runtime'}]}));assert.throws(()=>validateRuntime(dir),/native game code/);});
test('unknown runtime plugins cannot silently become an unusable keyboard package',t=>{const dir=fixture(t);fs.writeFileSync(path.join(dir,'CenterpieceDevice.uproject'),JSON.stringify({Plugins:[{Name:'CustomRuntime',Enabled:true}]}));assert.throws(()=>validateRuntime(dir),/not established/);});
test('editor docking rejects invalid process and out-of-window bounds before native calls',async()=>{const dock=new UnrealDock(()=>({isDestroyed:()=>false,getContentSize:()=>[1000,700]}));await assert.rejects(dock.attach(0,{x:0,y:0,width:500,height:400}),/saved Unreal/);await assert.rejects(dock.attach(123,{x:900,y:0,width:500,height:400}),/outside/);await assert.rejects(dock.attach(123,{x:NaN,y:0,width:500,height:400}),/Invalid/);await dock.shutdown();await assert.rejects(dock.attach(123,{x:0,y:0,width:500,height:400}),/closing/);});
test('cancelling an active Unreal build signals only that job and keeps its source',t=>{const dir=fixture(t),{UnrealCook}=require('../src/studio-unreal-cook.cjs'),cook=new UnrealCook(dir,{list:()=>[]}),id='11111111-1111-4111-8111-111111111111',controller=new AbortController();cook.jobs.set(id,{id,folder:dir,state:'building',controller});assert.equal(cook.cancel(id).label,'Cancelling Unreal build…');assert.equal(controller.signal.aborted,true);assert.ok(fs.existsSync(path.join(dir,'CenterpieceDevice.uproject')));assert.throws(()=>cook.cancel('unknown'),/active Unreal/);});
