'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {StudioDeviceService}=require('../src/studio-device-service.cjs');
const {metadata,sha}=require('../src/studio-device-loader.cjs');
const code=value=>e=>e.code===value;
function fixture(t,{full=false,trust=false}={}){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'studio-device-service-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const bytes=Buffer.alloc(500,0xa5),file=path.join(dir,'build.pak');fs.writeFileSync(file,bytes);const id=crypto.randomUUID(),sceneSha256='1'.repeat(64),record={id,sceneSha256,file,sha256:sha(bytes),size:bytes.length,target:'Android_ASTC',cooked:true,packageIntegrityVerified:true};
 const slots=Array.from({length:5},(_,i)=>metadata({slot:i+1,fileID:'skin-'+(i+1),fileName:i===3?'Koi':'Skin '+(i+1),fileExtension:'mp4',fileSize:300},i+1)),calls=[],buildCalls=[],control={exclusive:0};
 const builder={artifact(job,scene){buildCalls.push({job,scene});assert.equal(job,id);assert.equal(scene,sceneSha256);return{...record};},status(){return{projectName:'Stillwater · native'};}};
 const loader={async inspect(){assert.equal(control.exclusive,1);calls.push({action:'inspect'});return{active:4,slots,protectedSlots:[4]};},async prepare(input){assert.equal(control.exclusive,1);calls.push({action:'prepare',input});if(full&&!input.slot)throw Object.assign(Error('All five native slots are occupied.'),{code:'STUDIO_SKIN_SLOTS_FULL',slots});return{token:crypto.randomUUID(),slot:input.slot||5,name:input.name,requiresReplacementReview:!!input.backup,returnTo:'Koi'};},async execute(token,options){assert.equal(control.exclusive,1);calls.push({action:'execute',token,options});options.onProgress({stage:'upload',bytesQueued:200,totalBytes:500});return{active:true,transportConfirmed:true,nativeRenderingVerified:false};},async restoreLast(){assert.equal(control.exclusive,1);calls.push({action:'restore'});return{active:4,restored:true};}};
 const backupFile=path.join(dir,'flames.mp4'),backupBytes=Buffer.alloc(300,5);fs.writeFileSync(backupFile,backupBytes);const trusted={slot:5,file:backupFile,sha256:sha(backupBytes),metadata:slots[4],sourceUrl:'https://assets.freethinkerportal.com/video/flames/flames_encode.mp4'};
 const runExclusive=async task=>{control.exclusive++;try{return await task();}finally{control.exclusive--;}};
 const service=new StudioDeviceService(dir,{builder,loader,runExclusive,trustedBackups:trust?[trusted]:[]});const settle=async response=>{await service.jobs.get(response.id).promise;return service.status({id:response.id});};
 return{dir,id,sceneSha256,record,file,bytes,builder,loader,service,settle,calls,buildCalls,slots,trusted,backupBytes,control};
}
test('prepare resolves verified artifact bytes internally and remains read-only inside exclusive queue',async t=>{const f=fixture(t),initial=f.service.request('device-prepare',{id:f.id,sceneSha256:f.sceneSha256});assert.equal(initial.state,'queued');assert.equal(initial.readOnly,true);assert.equal(f.calls.length,0);const done=await f.settle(initial);assert.equal(done.state,'ready');assert.equal(done.result.reviewOnly,true);assert.equal(done.result.buildId,f.id);assert.equal(f.calls[0].input.bytes.equals(f.bytes),true);assert.equal(f.calls[0].input.sha256,f.record.sha256);assert.deepEqual(f.calls.map(v=>v.action),['prepare']);assert.ok(!JSON.stringify(done).includes(f.dir));assert.ok(!JSON.stringify(done).includes('bytes":['));});

test('full slots discover verified restoration copies without uploading or offering protected skins',async t=>{
 const f=fixture(t,{full:true});let inspected;
 f.service.restorationProvider=async slots=>{inspected=slots;return[f.trusted];};
 const result=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256}));
 assert.equal(result.state,'failed');assert.equal(result.error.code,'STUDIO_SKIN_SLOTS_FULL');
 assert.ok(inspected.every(slot=>slot.slot!==4));assert.equal(result.result.slotChoices[4].canReviewReplacement,true);
 assert.ok(!f.calls.some(call=>call.action==='execute'));
 const review=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256,slot:5}));
 assert.equal(review.state,'ready');assert.equal(review.result.requiresReplacementReview,true);
});

test('unbacked slot replacement is explicit, slot-bound and forwarded only to preparation',async t=>{
 const f=fixture(t,{full:true});
 assert.throws(()=>f.service.prepare({id:f.id,sceneSha256:f.sceneSha256,replaceWithoutBackup:true}),code('STUDIO_DEVICE_INPUT'));
 assert.throws(()=>f.service.prepare({id:f.id,sceneSha256:f.sceneSha256,slot:5,replaceWithoutBackup:'yes'}),code('STUDIO_DEVICE_INPUT'));
 const choice=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256}));
 assert.equal(choice.result.slotChoices[4].requiresPermanentReplacement,true);assert.equal(choice.result.slotChoices[4].canReviewReplacement,true);
 assert.equal(choice.result.slotChoices[3].canReviewReplacement,false);
 await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256,slot:5,replaceWithoutBackup:true}));
 assert.equal(f.calls.at(-1).input.replaceWithoutBackup,true);assert.ok(!f.calls.some(call=>call.action==='execute'));
});
test('renderer cannot supply file paths, PAK bytes, backup provenance or unknown options',t=>{const f=fixture(t);for(const extra of [{file:'C:/evil.pak'},{bytes:[1,2]},{backup:f.trusted},{sourceUrl:'https://evil.example'},{protectedSlots:[]},{sha256:'0'.repeat(64)}])assert.throws(()=>f.service.prepare({id:f.id,sceneSha256:f.sceneSha256,...extra}),code('STUDIO_DEVICE_INPUT'));assert.equal(f.buildCalls.length,0);assert.equal(f.calls.length,0);assert.throws(()=>f.service.request('device-restore',{file:f.file}),code('STUDIO_DEVICE_INPUT'));});
test('all occupied slots report precise conflict with only main-process trusted restoration choices',async t=>{const f=fixture(t,{full:true,trust:true});const done=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256}));assert.equal(done.state,'failed');assert.equal(done.error.code,'STUDIO_SKIN_SLOTS_FULL');assert.equal(done.result.slotChoices.length,5);assert.equal(done.result.slotChoices[4].canReviewReplacement,true);assert.equal(done.result.slotChoices[3].protected,true);assert.equal(done.result.slotChoices[3].canReviewReplacement,false);assert.deepEqual(f.calls.map(v=>v.action),['prepare','inspect']);assert.ok(!JSON.stringify(done).includes(f.trusted.file));});
test('selected restoration slot reads only registered local source and stays a review until execute',async t=>{const f=fixture(t,{full:true,trust:true});const done=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256,slot:5}));assert.equal(done.state,'ready');assert.equal(done.result.requiresReplacementReview,true);assert.equal(f.calls[0].input.backup.bytes.equals(f.backupBytes),true);assert.deepEqual(f.calls.map(v=>v.action),['prepare']);const execution=f.service.execute({token:done.result.token,confirmReplacement:true});assert.equal(execution.state,'queued');const result=await f.settle(execution);assert.equal(result.state,'ready');assert.equal(result.readOnly,false);assert.equal(result.progress.bytesQueued,200);assert.equal(result.result.nativeRenderingVerified,false);assert.equal(f.calls[1].options.confirmCatalogReplacement,true);assert.throws(()=>f.service.execute({token:done.result.token,confirmReplacement:true}),code('STUDIO_TEST_EXPIRED'));});
test('missing or changed trusted restoration copies cannot become offered replacements',async t=>{const f=fixture(t,{full:true,trust:true});fs.appendFileSync(f.trusted.file,'changed');let done=await f.settle(f.service.readiness());assert.equal(done.result.slotChoices[4].restorationAvailable,false);done=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256,slot:5}));assert.equal(done.error.code,'STUDIO_BACKUP_UNAVAILABLE');assert.ok(!f.calls.some(v=>v.action==='prepare'||v.action==='execute'));});
test('changed built package is rejected before preparation or execution',async t=>{const f=fixture(t);const r=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256}));fs.appendFileSync(f.file,'changed');const done=await f.settle(f.service.execute({token:r.result.token}));assert.equal(done.error.code,'STUDIO_BUILD_CHANGED');assert.ok(!f.calls.some(v=>v.action==='execute'));});
test('incomplete, wrong-target or unverified builder artifacts never reach loader',async t=>{const f=fixture(t);f.record.packageIntegrityVerified=false;let done=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256}));assert.equal(done.error.code,'STUDIO_BUILD_NOT_READY');f.record.packageIntegrityVerified=true;f.record.target='Windows';done=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256}));assert.equal(done.error.code,'STUDIO_BUILD_NOT_READY');assert.equal(f.calls.length,0);});
test('long-running execute immediately returns a pollable job and preserves progress without request blocking',async t=>{const f=fixture(t),r=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256}));let release;f.loader.execute=async(token,options)=>{options.onProgress({stage:'upload',bytesQueued:499,totalBytes:500});return new Promise(resolve=>{release=resolve;});};const initial=f.service.execute({token:r.result.token});assert.equal(initial.state,'queued');await new Promise(resolve=>setImmediate(resolve));const status=f.service.status({id:initial.id});assert.equal(status.state,'running');assert.equal(status.progress.bytesQueued,499);assert.throws(()=>f.service.readiness(),code('STUDIO_DEVICE_BUSY'));release({transportConfirmed:true});assert.equal((await f.settle(initial)).state,'ready');});
test('busy rejection does not consume an otherwise valid prepared review',async t=>{const f=fixture(t),r=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256}));let release;f.loader.inspect=()=>new Promise(resolve=>{release=()=>resolve({active:4,slots:f.slots,protectedSlots:[4]});});const busy=f.service.readiness();await new Promise(resolve=>setImmediate(resolve));assert.throws(()=>f.service.execute({token:r.result.token}),code('STUDIO_DEVICE_BUSY'));release();await f.settle(busy);assert.equal((await f.settle(f.service.execute({token:r.result.token}))).state,'ready');});
test('restore remains available without a live build or review and delegates durable baseline recovery',async t=>{const f=fixture(t);f.builder.artifact=()=>{throw Error('No build');};const done=await f.settle(f.service.request('device-restore',{}));assert.equal(done.state,'ready');assert.equal(done.readOnly,false);assert.equal(done.result.active,4);assert.deepEqual(f.calls.map(v=>v.action),['restore']);});
test('public failures retain precise known error codes but remove raw filesystem details',async t=>{const f=fixture(t);f.loader.prepare=async()=>{throw Error('EPERM C:\\private\\secret-folder');};let done=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256}));assert.equal(done.error.code,'STUDIO_DEVICE_FAILED');assert.ok(!done.error.message.includes('private'));f.loader.prepare=async()=>{throw Object.assign(Error('Original skin is selected; restoration needs attention.'),{code:'STUDIO_UPLOAD_REJECTED',previousSkinRestored:false,previousSkinSelected:true});};done=await f.settle(f.service.prepare({id:f.id,sceneSha256:f.sceneSha256}));assert.equal(done.error.code,'STUDIO_UPLOAD_REJECTED');assert.equal(done.error.previousSkinSelected,true);});
test('status snapshots are immutable to the renderer and completed job memory stays bounded',async t=>{const f=fixture(t);let response;for(let i=0;i<27;i++)response=await f.settle(f.service.readiness());assert.equal(f.service.jobs.size,24);response.result.slotChoices[3].protected=false;assert.equal(f.service.status({id:response.id}).result.slotChoices[3].protected,true);assert.throws(()=>f.service.status({id:crypto.randomUUID()}),code('STUDIO_DEVICE_JOB_MISSING'));});
test('service requires trusted build service and explicit exclusive hardware orchestration',t=>{const f=fixture(t);assert.throws(()=>new StudioDeviceService(f.dir,{builder:f.builder}),code('STUDIO_DEVICE_CONFIG'));assert.throws(()=>new StudioDeviceService(f.dir,{runExclusive:async task=>task()}),code('STUDIO_DEVICE_CONFIG'));assert.throws(()=>new StudioDeviceService(f.dir,{builder:f.builder,runExclusive:async task=>task(),trustedBackups:[{...f.trusted,file:'relative.mp4'}]}),code('STUDIO_DEVICE_CONFIG'));});
test('queued actions capture reviewed inputs before the caller can mutate its object',async t=>{const f=fixture(t),input={id:f.id,sceneSha256:f.sceneSha256,slot:5},prepare=f.service.prepare(input);input.slot=4;const review=await f.settle(prepare);assert.equal(f.calls[0].input.slot,5);const confirmation={token:review.result.token,confirmReplacement:false},execute=f.service.execute(confirmation);confirmation.confirmReplacement=true;confirmation.token=crypto.randomUUID();await f.settle(execute);const sent=f.calls.find(v=>v.action==='execute');assert.equal(sent.token,review.result.token);assert.equal(sent.options.confirmCatalogReplacement,false);});
