'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const M=require('../studio/model.js'),P=require('../studio/collection-presets.js'),C=require('../studio/collection-effects.js'),R=require('../studio/render.js');
const legacy=P.list.filter(p=>p.id!=='storm-meadow');
function trace(project,time=2.5,events=[]){const calls=[],stack=[],state={globalAlpha:1},target={globalAlpha:1};for(const m of ['beginPath','closePath','moveTo','lineTo','fill','stroke','fillRect','ellipse','arc','translate','rotate','scale','drawImage','fillText'])target[m]=(...v)=>{assert.ok(v.every(x=>typeof x!=='number'||Number.isFinite(x)),m);calls.push([m,...v]);};for(const m of ['createRadialGradient','createLinearGradient'])target[m]=(...v)=>{assert.ok(v.every(Number.isFinite));const id=calls.length;calls.push([m,...v]);return{addColorStop(at,color){assert.ok(at>=0&&at<=1);assert.ok(!/NaN|Infinity/.test(color));calls.push(['stop',id,at,color]);}};};target.save=()=>{stack.push({...state});calls.push(['save']);};target.restore=()=>{assert.ok(stack.length);Object.assign(state,stack.pop());calls.push(['restore']);};const ctx=new Proxy(target,{get(t,k){return k in state?state[k]:t[k];},set(t,k,v){state[k]=v;calls.push(['set',k,typeof v==='object'?'gradient':v]);return true;}}),layer=project.layers.find(l=>l.type==='collection'),effects=R.activeRules(project,R.eventsAt(events,time),time);C.draw(ctx,layer,time,effects);assert.equal(stack.length,0);return calls;}
test('collection has 21 distinct animated scenes and three playable games',()=>{assert.equal(P.list.length,25);assert.equal(new Set(P.list.map(p=>p.id)).size,25);assert.equal(P.list.filter(p=>p.style==='Animated').length,12);assert.equal(P.list.filter(p=>p.style==='Realistic').length,5);assert.equal(P.list.filter(p=>p.style==='Realistic rocket').length,1);assert.deepEqual([...C.ids].sort(),legacy.map(p=>p.id).sort());});
test('download artifacts validate and include real embedded images below one MB each',()=>{for(const entry of P.list){const p=entry.create(),disk=M.validate(JSON.parse(fs.readFileSync(path.join(__dirname,'../studio/examples/community-collection',entry.id+'.cpskin'),'utf8')));assert.equal(p.id,disk.id);assert.ok(p.rules.length>=2);assert.ok(Buffer.byteLength(JSON.stringify(p))<900000);if(['Realistic','Realistic rocket','Photorealistic'].includes(entry.style)){assert.ok(p.layers.some(l=>l.type==='image'&&l.image.startsWith('data:image/jpeg;base64,')));assert.equal(M.rasterInfo(p.layers[0].image).width,1920);assert.equal(M.rasterInfo(p.layers[0].image).height,550);}assert.equal(entry.nativeVerified,false);}});
test('every scene renders finite, deterministic geometry and responds to physical keys',()=>{const fingerprints=new Set();for(const entry of legacy.filter(e=>e.style!=='Game')){const p=entry.create(),key=entry.id==='atlas-launch'?'Space':'KeyA',event={type:'keyDown',key,time:2,x:840,y:320,strength:1},base=trace(p);assert.deepEqual(base,trace(p));assert.notDeepEqual(base,trace(p,2.5,[event]),entry.id+' has a visible reaction');fingerprints.add(JSON.stringify(base));for(const at of [0,.1,1,8,23.99])trace(p,at,[{...event,time:0}]);}assert.equal(fingerprints.size,21);});
test('scene speed zero freezes ambient animation, while rules still respond',()=>{for(const entry of legacy){const p=entry.create();p.layers.find(l=>l.type==='collection').speed=0;assert.deepEqual(trace(p,1),trace(p,8),entry.id);}});
test('all scenes and game title screens visibly animate before a key is pressed',()=>{for(const entry of legacy){const p=entry.create();assert.notDeepEqual(trace(p,2.5),trace(p,3.5),entry.id+' must contain ambient animation');}});
test('zero reactivity suppresses collection reactions without stopping ambient animation',()=>{for(const entry of legacy){const p=entry.create();p.layers.find(l=>l.type==='collection').reactivity=0;const event={type:'keyDown',key:entry.id==='atlas-launch'?'Space':'KeyA',time:2,x:840,y:320,strength:1};assert.deepEqual(trace(p,2.5),trace(p,2.5,[event]),entry.id);}});
test('browser loader uses approved host bridge and validates selected identity',async()=>{const sandbox={StudioModel:M,studioHost:{send:async(action,id)=>{assert.equal(action,'collection');return P.list.find(p=>p.id===id).create();}}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../studio/collection-presets.js'),'utf8'),sandbox);const loaded=await sandbox.StudioCollectionPresets.list.find(p=>p.id==='atlas-launch').createAsync();assert.ok(loaded.layers.every(l=>l.image));loaded.name='Changed';const again=await sandbox.StudioCollectionPresets.load('atlas-launch');assert.notEqual(again.name,'Changed');await assert.rejects(sandbox.StudioCollectionPresets.load('../secret'),/Choose a collection/);});
test('failed bridge request never substitutes a missing photographic project',async()=>{const sandbox={StudioModel:M,studioHost:{send:async()=>{throw Error('Disconnected');}}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../studio/collection-presets.js'),'utf8'),sandbox);await assert.rejects(sandbox.StudioCollectionPresets.load('storm-window'),/Disconnected/);sandbox.studioHost.send=async()=>P.list[0].create();await assert.rejects(sandbox.StudioCollectionPresets.load('storm-window'),/did not match/);});
