const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const{TwitchConnection,channelName}=require('../src/twitch-auth.cjs');
const id='exampleclient1234567890',access='a'.repeat(30),refresh='refresh-with/symbols%and=values';
function fixture(t,fetch){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'twitch-test-')),opened=[],connections=[];const storage={isEncryptionAvailable:()=>true,encryptString:s=>Buffer.from(Buffer.from(s).toString('base64')),decryptString:b=>Buffer.from(b.toString(),'base64').toString()};const chat={state:{connected:false},close(){this.state={connected:false};},async connect(...args){connections.push(args);this.state={connected:true,channel:args[1]};}};const client=new TwitchConnection(directory,{openExternal:async url=>opened.push(url)},storage,chat,id,{fetch,sleep:async()=>{}});t.after(()=>{client.close();for(const f of ['twitch-session.bin','twitch-session.bin.tmp']){const file=path.join(directory,f);if(fs.existsSync(file))fs.unlinkSync(file);}fs.rmdirSync(directory);});return{client,chat,opened,connections,directory,storage};}
const approved=()=>({access_token:access,refresh_token:refresh,expires_in:14400,scope:['chat:read']});
const device=()=>({device_code:'d'.repeat(32),user_code:'ABCD1234',verification_uri:'https://www.twitch.tv/activate?public=true&device-code=ABCD1234',expires_in:1800,interval:5});
test('channel links normalize and reject non-Twitch or malformed destinations',()=>{assert.equal(channelName('https://www.twitch.tv/TwitchDev/'),'twitchdev');assert.equal(channelName('#Some_User'),'some_user');for(const input of ['https://twitch.tv.evil.test/test','https://user@twitch.tv/test','https://twitch.tv/videos/123','x\r\nJOIN #other','file:///test'])assert.throws(()=>channelName(input));});
test('browser approval requests read-only access, waits, validates and saves without exposing tokens',async t=>{let polls=0;const f=fixture(t,async(url,o)=>{const p=new URLSearchParams(o.body);assert.equal(o.redirect,'error');assert.equal(p.has('client_secret'),false);if(url.endsWith('/device')){assert.equal(p.get('scopes'),'chat:read');return Response.json(device());}if(url.endsWith('/token'))return ++polls===1?Response.json({message:'authorization_pending'},{status:400}):Response.json(approved());assert.equal(o.headers.Authorization,'OAuth '+access);return Response.json({client_id:id,login:'reader',scopes:['chat:read']});});await f.client.authorize('twitchdev',new AbortController().signal);assert.equal(f.opened.length,1);assert.equal(polls,2);assert.deepEqual(f.connections,[['reader','twitchdev',access]]);assert.equal(fs.readFileSync(f.client.file).includes(Buffer.from(access)),false);assert.equal(JSON.stringify(f.client.state).includes(access),false);});
test('untrusted approval URLs never open the browser',async t=>{const f=fixture(t,async()=>Response.json({...device(),verification_uri:'https://evil.test/activate'}));await assert.rejects(f.client.authorize('twitchdev',new AbortController().signal),/Invalid Twitch/);assert.equal(f.opened.length,0);});
test('restored connection refreshes directly, preserves symbols and rotates saved credentials',async t=>{const f=fixture(t,async(url,o)=>{if(url.endsWith('/token')){assert.equal(new URLSearchParams(o.body).get('refresh_token'),refresh);return Response.json({...approved(),refresh_token:refresh+'new'});}return Response.json({client_id:id,login:'reader',scopes:['chat:read']});});f.client.accept(approved(),'twitchdev');f.client.session.expiresAt=0;f.client.save();const restored=new TwitchConnection(f.directory,{},f.storage,f.chat,id,{fetch:f.client.fetch});t.after(()=>restored.close());await restored.restore();assert.equal(restored.session.refreshToken,refresh+'new');assert.equal(f.chat.state.connected,true);});
test('revoked authorization removes saved tokens and disconnects chat',async t=>{const f=fixture(t,async()=>Response.json({message:'invalid'},{status:401}));f.client.accept(approved(),'twitchdev');await assert.rejects(f.client.validate(),/revoked/);assert.equal(f.client.session,null);assert.equal(fs.existsSync(f.client.file),false);assert.equal(f.chat.state.connected,false);});
test('cancellation during device request cannot open browser or persist a late result',async t=>{const controller=new AbortController();const f=fixture(t,async()=>{controller.abort();return Response.json(device());});await assert.rejects(f.client.authorize('twitchdev',controller.signal),/Cancelled/);assert.equal(f.opened.length,0);assert.equal(fs.existsSync(f.client.file),false);});
test('disconnect removes encrypted connection even if revocation is offline',async t=>{const f=fixture(t,async()=>{throw Error('Offline');});f.client.accept(approved(),'twitchdev');await f.client.disconnect();assert.equal(fs.existsSync(f.client.file),false);assert.equal(f.client.session,null);});
