(() => {
 'use strict';
 const M=window.StudioModel,R=window.StudioRender,P={list:[...(window.StudioCollectionPresets?.list||[]),...(window.StudioPondPresets?.list||[]),...window.StudioPresets.list]},$=id=>document.getElementById(id);
 const title=s=>s.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/[-_]/g,' ').replace(/^./,c=>c.toUpperCase());
 const DRAFT_KEY='centerpiece-skin-studio-draft';
 const creatorSetup=StudioUnrealSetup.creationSession(document);
 function beginCreation(){creatorSetup.start();void refreshTools();}
 let eventSequence=0;let inspectorMode='layer';const selectedKeys=new Set();let keyDrag=null,pointerTestKey=null;let activeRule=null;
 let loaded=null,loadError='',draftSnapshot=null,draftConflict=false;try{draftSnapshot=localStorage.getItem(DRAFT_KEY);loaded=StudioStorage.load(localStorage);}catch(e){loadError=e.message;}
 const history=new StudioHistory.History(loaded||P.list[0].create());
 let project=history.current,selected=project.layers.findLast(l=>!l.locked)?.id||project.layers.at(-1)?.id||null,mode='edit',playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,time=0,clock=0,lastTick=0,lastPaint=0,events=[],toggleBase=Object.create(null),saveTimer,unsaved=false,drag=null,layout=[],route='design',busy=false;
 const projectLoader=new StudioProjectLoader.Coordinator(()=>JSON.stringify(project));
 async function loadProject(create,commit){const result=await projectLoader.load(create,R.prepareImages,commit);if(result.status==='edited')notify('Project opening was cancelled because you edited the current design. Your edits are safe.');return result;}
 const canvas=$('scene-canvas'),ctx=canvas.getContext('2d'),frame=$('stage-frame');
 const physical=['Esc','1','2','3','4','5','6','7','8','9','0','-','=','⌫','⏮','⏭','Tab','Q','W','E','R','T','Y','U','I','O','P','[',']','\\','⏯','Vol','Caps','A','S','D','F','G','H','J','K','L',';',"'",'Enter','Shift','Z','X','C','V','B','N','M',',','.','/','Shift','↑','Ctrl','Win','Alt','Space','Alt','L1','Ctrl','←','↓','→'];
 const codes=['Escape',...Array.from({length:10},(_,i)=>'Digit'+((i+1)%10)),'Minus','Equal','Backspace','MediaTrackPrevious','MediaTrackNext','Tab',...'QWERTYUIOP'.split('').map(c=>'Key'+c),'BracketLeft','BracketRight','Backslash','MediaPlayPause','AudioVolumeMute','CapsLock',...'ASDFGHJKL'.split('').map(c=>'Key'+c),'Semicolon','Quote','Enter','ShiftLeft',...'ZXCVBNM'.split('').map(c=>'Key'+c),'Comma','Period','Slash','ShiftRight','ArrowUp','ControlLeft','MetaLeft','AltLeft','Space','AltRight','ContextMenu','ControlRight','ArrowLeft','ArrowDown','ArrowRight'];
 const on=(id,event,fn)=>{const element=$(id);element.addEventListener(event,fn);if(event==='click'&&element.tagName==='BUTTON')element.disabled=false;};
 let guideOpener=null;on('studio-help','click',()=>{guideOpener=document.activeElement;$('studio-guide').showModal();$('studio-guide-title').focus();});on('close-studio-guide','click',()=>$('studio-guide').close());$('studio-guide').addEventListener('close',()=>guideOpener?.focus());
 function node(tag,props={},children=[]){const n=document.createElement(tag);for(const[k,v]of Object.entries(props)){if(k==='text')n.textContent=v;else if(k==='class')n.className=v;else if(k==='value')n.value=v;else if(k==='checked')n.checked=v;else n.setAttribute(k,v);}for(const child of children)n.append(child);return n;}
 function notify(message,error=false){$('studio-status').textContent=message;$('studio-status').classList.toggle('error-text',error);}
 function options(select,values){select.replaceChildren(...values.map(v=>node('option',{value:typeof v==='string'?v:v.value,text:typeof v==='string'?title(v):v.label})));}
 function clearReactions(){R.resetGames?.();events=[];toggleBase=Object.create(null);$('event-count').textContent='0 events';}
 function selectedLayer(){return project.layers.find(l=>l.id===selected)||null;}
 function safeName(){return(project.name||'skin').replace(/[^\p{L}\p{N} _-]/gu,'').trim().slice(0,70)||'skin';}
 function download(blob,name){const url=URL.createObjectURL(blob),a=node('a',{href:url,download:name});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 function showDraftConflict(){draftConflict=true;clearTimeout(saveTimer);saveTimer=null;unsaved=true;$('draft-conflict').hidden=false;$('save-state').textContent='Draft changed in another tab';$('save-state').classList.add('danger-text');}
 function saveDraft(){clearTimeout(saveTimer);saveTimer=null;try{if(draftConflict||localStorage.getItem(DRAFT_KEY)!==draftSnapshot){showDraftConflict();return;}StudioStorage.save(localStorage,project);draftSnapshot=localStorage.getItem(DRAFT_KEY);unsaved=false;$('save-state').textContent='Draft saved on this PC';$('save-state').classList.remove('danger-text');}catch(e){unsaved=true;$('save-state').textContent='Draft not saved · export a copy';$('save-state').classList.add('danger-text');notify(e.message,true);}}
 function scheduleSave(){unsaved=true;clearTimeout(saveTimer);if(draftConflict){showDraftConflict();return;}$('save-state').textContent='Saving local draft…';saveTimer=setTimeout(saveDraft,400);}
 function mutate(change,{inspector=true,rules=true,message=''}={}){
  const next=M.clone(project);try{change(next);const rulesChanged=JSON.stringify(next.rules)!==JSON.stringify(project.rules);project=history.commit(next);if(rulesChanged)clearReactions();if(!project.layers.some(l=>l.id===selected))selected=project.layers.findLast(l=>!l.locked)?.id||project.layers.at(-1)?.id||null;scheduleSave();renderAll({inspector,rules});if(message)notify(message);return true;}catch(e){notify(e.message,true);return false;}
 }
 function replace(next,message){try{beginCreation();project=history.commit(next);showDesign();selected=project.layers.findLast(l=>!l.locked)?.id||project.layers.at(-1)?.id||null;clearReactions();time=0;clock=0;scheduleSave();renderAll();notify(message);}catch(e){notify(e.message,true);}}
 function renderAll({inspector=true,rules=true}={}){renderLayers();if(inspector)renderInspector();if(rules)renderRules();renderProject();renderKeyframes();renderSelection();paint();}
 function renderProject(){if($('back-to-scene').hidden)$('preview-source-label').textContent='Editing: '+project.name;for(const[id,value]of [['project-name',project.name],['project-description',project.description],['project-duration',project.duration],['project-fps',project.fps],['canvas-background',project.canvas.background],['engine-target',project.engineTarget]])if(document.activeElement!==$(id))$(id).value=value;
  $('undo').disabled=!history.canUndo;$('redo').disabled=!history.canRedo;$('timeline').max=project.duration;$('timeline-ruler').replaceChildren(...Array.from({length:7},(_,i)=>node('span',{text:(i*project.duration/6).toFixed(1)+'s'})));document.title=project.name+' · Skin Studio';renderTransport();
 }
 function renderLayers(){const active=document.activeElement?.id;$('layer-count').textContent=project.layers.length+'/48';$('layer-list').replaceChildren();for(const layer of [...project.layers].reverse()){
   const row=node('div',{class:'layer-row'+(layer.id===selected?' selected':'')});const chip=node('span',{class:'layer-chip'});chip.style.background=layer.color;
   const select=node('button',{class:'layer-select',id:'select-'+layer.id,'aria-pressed':String(layer.id===selected),title:layer.name},[chip,node('span',{class:'layer-name',text:layer.name})]);select.addEventListener('click',()=>{selected=layer.id;renderLayers();renderInspector();renderKeyframes();renderSelection();});
   const visibility=node('button',{class:'icon-button',text:layer.visible?'●':'○',title:layer.visible?'Hide layer':'Show layer','aria-label':(layer.visible?'Hide ':'Show ')+layer.name,id:'visible-'+layer.id});visibility.addEventListener('click',()=>mutate(p=>{p.layers.find(l=>l.id===layer.id).visible=!layer.visible;},{message:layer.visible?'Layer hidden.':'Layer visible.'}));
   const lock=node('button',{class:'icon-button',text:layer.locked?'▣':'▫',title:layer.locked?'Unlock layer':'Lock layer','aria-label':(layer.locked?'Unlock ':'Lock ')+layer.name,id:'lock-'+layer.id});lock.addEventListener('click',()=>mutate(p=>{p.layers.find(l=>l.id===layer.id).locked=!layer.locked;}));row.append(select,visibility,lock);$('layer-list').append(row);
  }if(!project.layers.length)$('layer-list').append(node('p',{class:'panel-note',text:'Your canvas is empty. Add an effect or open the preset library.'}));
  const layer=selectedLayer(),index=project.layers.findIndex(l=>l.id===selected);for(const id of ['duplicate-layer','delete-layer'])$(id).disabled=!layer;$('layer-up').disabled=!layer||index>=project.layers.length-1;$('layer-down').disabled=!layer||index<=0;if(active?.startsWith('select-')||active?.startsWith('visible-')||active?.startsWith('lock-'))$(active)?.focus({preventScroll:true});
 }
 function movementForm(){
  const group=node('details',{class:'object-movement',id:'object-movement'},[node('summary',{text:'Movement & nearby reactions'})]);
  group.append(node('p',{class:'panel-note',text:'Animate this layer as one object. Use separate fish or transparent images for objects that move independently.'}));
  const choices=[{value:'none',label:'Still'},{value:'drift',label:'Drift'},{value:'swim',label:'Swim'},{value:'orbit',label:'Orbit'}];
  const mode=optionField('Idle movement','motion-type','none',choices),speed=inputField('Movement speed','motion-speed',1,'number',{min:0,max:4,step:.1}),distance=inputField('Movement range · px','motion-distance',80,'number',{min:0,max:600,step:5});
  const turn=node('input',{id:'motion-turn',type:'checkbox'}),turnLabel=node('label',{class:'inline-check',for:'motion-turn'},[turn,node('span',{text:'Face the direction of movement'})]);
  const fields=node('div',{class:'movement-fields'},[mode.label,speed.label,distance.label,turnLabel]);
  const add=node('button',{id:'add-nearby-reactions',type:'button',class:'button compact',text:'＋ Add ripple + move away',disabled:''});
  group.append(fields,add,node('p',{class:'panel-note',text:'Adds reactions to this object. Select keys first to limit the keys used. Adjust distance and strength in Interactions.'}));$('layer-form').querySelector('hr').before(group);
  for(const [key,control]of [['type',mode.control],['speed',speed.control],['distance',distance.control],['turn',turn]])control.addEventListener('change',()=>{const l=selectedLayer();if(!l||l.locked)return;const value=key==='type'?control.value:key==='turn'?control.checked:Number(control.value);if(mutate(p=>{const item=p.layers.find(v=>v.id===l.id);item.motion={type:'none',speed:1,distance:80,turn:true,...item.motion,[key]:value};},{rules:false,inspector:false})){clearReactions();control.setAttribute('aria-invalid','false');paint();}else control.setAttribute('aria-invalid','true');});
  on('add-nearby-reactions','click',()=>{const l=selectedLayer();if(!l||l.locked)return;const keys=StudioInteractions.selectedKeyCodes(selectedKeys,codes,M.validKey),scope=keys.length?{keys}:{};
   const flee=M.createRule({effect:'flee',target:l.id,duration:2.8,...scope}),ripple=M.createRule({effect:'ripple',color:'#a2dfdc',duration:2,...scope});
   activeRule=flee.id;if(mutate(p=>p.rules.push(ripple,flee),{message:'Ripples and nearby movement added. Test with your keys, then adjust the reaction distance.'})){inspect('interactions');}
  });
 }
 movementForm();
 function renderInspector(){const l=selectedLayer();$('inspector-empty').hidden=!!l||inspectorMode==='interactions';$('layer-form').hidden=!l;$('layer-kind').textContent=l?title(l.type):'';if(!l)return;
  for(const input of document.querySelectorAll('[data-layer]')){const key=input.dataset.layer;if(document.activeElement!==input)input.value=l[key];input.disabled=l.locked;const out=document.querySelector('[data-value="'+key+'"]');if(out)out.textContent=key==='opacity'?Math.round(l[key]*100)+'%':Number(l[key]).toFixed(key==='speed'||key==='reactivity'?2:0);}
  const motion={type:'none',speed:1,distance:80,turn:true,...l.motion};for(const key of ['type','speed','distance','turn']){const input=$('motion-'+key);if(document.activeElement!==input){if(key==='turn')input.checked=motion[key];else input.value=motion[key];}input.disabled=l.locked;} $('add-nearby-reactions').disabled=l.locked;
  for(const button of document.querySelectorAll('[data-place],#place-on-key'))button.disabled=l.locked; $('text-properties').hidden=l.type!=='text';$('field-error').textContent=l.locked?'Layer is locked. Unlock it in the layer list to edit.':'';
 }
 function renderSelection(){const l=selectedLayer(),box=$('selection-box');box.hidden=!l||!l.visible||mode!=='edit'||!$('back-to-scene').hidden;if(box.hidden)return;const p=R.renderLayerAt(l,time,previewEvents(),motionOptions());box.style.left=(p.x/1920*100)+'%';box.style.top=(p.y/550*100)+'%';box.style.width=(p.width/1920*100)+'%';box.style.height=(p.height/550*100)+'%';box.style.transform='rotate('+p.rotation+'deg)';$('selection-name').textContent=l.name;$('resize-layer').disabled=l.locked;}
 function renderTransport(){ $('play-toggle').textContent=playing?'Ⅱ Pause':'▶ Play';$('play-toggle').setAttribute('aria-label',playing?'Pause preview':'Play preview');$('time-readout').textContent=time.toFixed(2)+' / '+project.duration.toFixed(2)+' s';if(document.activeElement!==$('timeline'))$('timeline').value=time; }
 function previewEvents(){return events.map(e=>({...e,time:time-(clock-e.clock)}));}
 function motionOptions(){return{rules:project.rules,motionTime:clock,duration:project.duration,loop:$('loop-preview').checked};}
 function paint(){try{ctx.setTransform(1,0,0,1,0,0);R.draw(ctx,project,time,previewEvents(),{...motionOptions(),toggleBase,gameTime:clock,gameEvents:events.filter(e=>!e.ruleId).map(e=>({...e,time:e.clock}))});renderSelection();}catch(e){playing=false;notify('Preview stopped: '+e.message,true);renderTransport();}}
 function tick(now){if(!lastTick)lastTick=now;const dt=Math.min(.1,(now-lastTick)/1000);lastTick=now;if(playing&&document.visibilityState==='visible'){clock+=dt;time+=dt;if(time>project.duration){if($('loop-preview').checked)time%=project.duration;else{time=project.duration;playing=false;}}}if(now-lastPaint>=1000/project.fps&&route==='design'){paint();renderTransport();lastPaint=now;}requestAnimationFrame(tick);}
 function renderKeyframes(){const l=selectedLayer();$('add-keyframe').disabled=!l||l.locked;$('keyframe-list').replaceChildren();if(!l?.keyframes.length){$('keyframe-list').append(node('p',{class:'keyframe-empty',text:l?'Animate a property at two different times to create movement.':'Select a layer to animate.'}));return;}
  for(const k of l.keyframes){const item=node('div',{class:'keyframe-item'}),go=node('button',{text:k.time.toFixed(2)+'s · '+title(k.property)+' '+k.value,title:'Go to keyframe'}),remove=node('button',{text:'×','aria-label':'Delete '+k.property+' keyframe at '+k.time+' seconds'});go.addEventListener('click',()=>{playing=false;time=k.time;clock=time;clearReactions();$('keyframe-property').value=k.property;$('keyframe-value').value=k.value;$('keyframe-easing').value=k.easing;renderTransport();paint();});remove.disabled=l.locked;remove.addEventListener('click',()=>mutate(p=>{p.layers.find(x=>x.id===l.id).keyframes=p.layers.find(x=>x.id===l.id).keyframes.filter(x=>x.id!==k.id);},{message:'Keyframe removed. Undo is available.'}));item.append(go,remove);$('keyframe-list').append(item);}
 }
 function optionField(label,id,value,items){const select=node('select',{id});options(select,items);select.value=value;return{control:select,label:node('label',{for:id,text:label},[select])};}
 function inputField(label,id,value,type='text',extra={}){const input=node('input',{id,type,value,...extra});return{control:input,label:node('label',{for:id,text:label},[input])};}
 function renderRules(){
  const I=StudioInteractions,focus=document.activeElement?.id,list=$('rules-list'),settings=$('rule-settings');list.replaceChildren();settings.replaceChildren();
  if(!project.rules.some(r=>r.id===activeRule))activeRule=null;
  $('rules-empty').hidden=project.rules.length>0;settings.hidden=!activeRule;
  for(const rule of project.rules){
   const row=node('div',{class:'interaction-row',role:'listitem'}),select=node('button',{id:'rule-'+rule.id+'-select',class:'interaction-select','aria-pressed':String(activeRule===rule.id),'aria-expanded':String(activeRule===rule.id),'aria-controls':'rule-settings'},[node('span',{class:'interaction-symbol',text:I.effects.find(e=>e.id===rule.effect)?.icon||'✦'}),node('span',{},[node('strong',{text:I.name(rule.effect)}),node('small',{text:(rule.trigger==='beat'?'Whole target':I.keySummary(rule))+' · '+(I.triggers.find(t=>t.value===rule.trigger)?.label||rule.trigger)})])]);
   select.querySelector('.interaction-symbol').style.color=rule.color;
   select.addEventListener('click',()=>{activeRule=activeRule===rule.id?null:rule.id;renderRules();});
   const test=node('button',{class:'button compact interaction-test',text:'▶','aria-label':'Test '+I.name(rule.effect),title:'Test '+I.name(rule.effect)});
   test.addEventListener('click',()=>{const current=project.rules.find(r=>r.id===rule.id);if(current){showDesign();playing=true;emit(current.trigger,current.keys?.[0]||(current.key==='any'?'KeyA':current.key),undefined,current.id);notify(I.name(current.effect)+' sent to the preview.');}});
   row.append(select,test);list.append(row);
  }
  const rule=project.rules.find(r=>r.id===activeRule);if(rule){
   const heading=node('div',{class:'interaction-settings-heading'},[node('h3',{text:I.name(rule.effect)})]),close=node('button',{class:'button compact',text:'×','aria-label':'Close interaction settings'});close.addEventListener('click',()=>{activeRule=null;renderRules();});heading.append(close);settings.append(heading);
   const selection=node('div',{class:'interaction-key-actions'}),pick=node('button',{class:'button compact',text:'⌨ Choose keys'}),apply=node('button',{class:'button compact primary',text:'Use highlighted keys'}),all=node('button',{class:'button compact',text:'All keys'});
   pick.addEventListener('click',()=>{selectedKeys.clear();codes.forEach((k,i)=>{if(rule.keys?rule.keys.includes(k):rule.key==='any'||rule.key===k)selectedKeys.add(i);});setMode('keys');$('show-keys').checked=true;$('key-guides').hidden=false;renderKeySelection();frame.scrollIntoView({block:'center',behavior:'instant'});notify('Highlight the keys you want, then choose Use highlighted keys.');});
   apply.addEventListener('click',()=>{const keys=I.selectedKeyCodes(selectedKeys,codes,M.validKey);if(!keys.length){notify('Highlight at least one supported key on the keyboard preview.',true);return;}mutate(p=>{const r=p.rules.find(v=>v.id===rule.id);r.keys=keys;r.key='any';},{message:'Interaction now uses '+keys.length+' highlighted keys.'});});
   all.addEventListener('click',()=>mutate(p=>{const r=p.rules.find(v=>v.id===rule.id);delete r.keys;r.key='any';},{message:'Interaction now uses all keys.'}));selection.append(pick,apply,all);if(rule.trigger!=='beat')settings.append(node('p',{class:'panel-note',text:'Assigned to '+I.keySummary(rule)}),selection);else settings.append(node('p',{class:'panel-note',text:'Test beat affects its target layer independently of keyboard selection.'}));
   const grid=node('div',{class:'interaction-fields'}),advanced=node('details',{class:'interaction-advanced'},[node('summary',{text:'Timing, trigger & target layer'})]),advancedFields=node('div',{class:'interaction-fields'});
   const fields={effect:optionField('Effect','rule-'+rule.id+'-effect',rule.effect,I.effects.map(e=>({value:e.id,label:e.name}))),color:inputField('Color','rule-'+rule.id+'-color',rule.color,'color'),strength:inputField('Strength','rule-'+rule.id+'-strength',rule.strength,'number',{min:0,max:4,step:.1}),duration:inputField('Duration · seconds','rule-'+rule.id+'-duration',rule.duration,'number',{min:.05,max:30,step:.05}),trigger:optionField('When it runs','rule-'+rule.id+'-trigger',rule.trigger,I.triggers),target:optionField('Where it appears','rule-'+rule.id+'-target',rule.target,[{value:'all',label:'Whole scene'},...project.layers.map(l=>({value:l.id,label:l.name}))]),key:optionField('Single key · optional','rule-'+rule.id+'-key',rule.key,[{value:'any',label:rule.keys?'Keep highlighted key group':'All keys'},...codes.filter(M.validKey).map(c=>({value:c,label:I.keyName(c)}))])};
   if(rule.effect==='flee'){fields.radius=inputField('Nearby distance · px','rule-'+rule.id+'-radius',rule.radius,'number',{min:20,max:1000,step:10});fields.distance=inputField('Move away · px','rule-'+rule.id+'-distance',rule.distance,'number',{min:0,max:600,step:10});settings.append(node('p',{class:'panel-note',text:'Only objects within this distance when the key is pressed move away. Whole scene targets moving objects and fish; choose a layer to move another object.'}));}
   for(const[key,field]of Object.entries(fields)){if(key==='key'&&rule.trigger==='beat')continue;field.control.addEventListener('change',()=>{const value=['strength','duration','radius','distance'].includes(key)?Number(field.control.value):field.control.value;const ok=mutate(p=>{const r=p.rules.find(r=>r.id===rule.id);r[key]=value;if(key==='key')delete r.keys;if(key==='trigger'&&value==='beat'){delete r.keys;r.key='any';}},{rules:false,inspector:false});field.control.setAttribute('aria-invalid',String(!ok));if(ok){const wasOpen=advanced.open;renderRules();const next=$('rule-settings').querySelector('details');if(next)next.open=wasOpen;}});(['trigger','target','key'].includes(key)?advancedFields:grid).append(field.label);}
   advanced.append(node('p',{class:'panel-note',text:'Key press is the default. Preview click, key release, Caps Lock and manual test beat remain available here.'}),advancedFields);settings.append(grid,advanced);
   const actions=node('div',{class:'interaction-manage'}),duplicate=node('button',{class:'button compact',text:'Duplicate'}),remove=node('button',{class:'button compact danger-text',text:'Remove interaction'});
   duplicate.addEventListener('click',()=>{const copy=M.createRule({...rule,id:M.uid()});activeRule=copy.id;mutate(p=>p.rules.push(copy),{message:'Interaction duplicated.'});});remove.addEventListener('click',()=>{activeRule=null;mutate(p=>{p.rules=p.rules.filter(r=>r.id!==rule.id);},{message:'Interaction removed. Undo restores it.'});$('add-rule').focus();});actions.append(duplicate,remove);settings.append(actions);
  }
  if(focus?.startsWith('rule-'))$(focus)?.focus({preventScroll:true});
 }
 function addInteraction(effect){const keys=StudioInteractions.selectedKeyCodes(selectedKeys,codes,M.validKey),rule=M.createRule({effect,...(effect==='flee'&&selectedLayer()?{target:selectedLayer().id,duration:2.8}:{}),...(keys.length?{keys}:{})});activeRule=rule.id;if(mutate(p=>p.rules.push(rule),{message:StudioInteractions.name(effect)+' added to '+(keys.length?keys.length+' highlighted keys':'all keys')+'.'})){$('effect-picker').hidden=true;$('add-rule').setAttribute('aria-expanded','false');inspect('interactions');}}
 function renderPresets(){const q=$('preset-search').value.trim().toLowerCase(),category=$('preset-category').value;const list=P.list.filter(p=>(category==='all'||p.category===category||(p.tags||[]).includes(category)||(category==='Community skins'&&window.StudioCollectionPresets?.list.some(v=>v.id===p.id)))&&(!q||(p.name+' '+p.description+' '+p.category).toLowerCase().includes(q)));$('preset-count').textContent=P.list.length+' editable skins';$('clear-search').hidden=!q;$('preset-empty').hidden=list.length>0;$('preset-grid').replaceChildren();for(const preset of list){
   const card=node('article',{class:'preset-card'}),preview=node('canvas',{width:640,height:184,'aria-label':preset.name+' preview'}),c=preview.getContext('2d');c.scale(640/1920,184/550);if(!preset.preview)R.draw(c,preset.create(),2.3,[]);const body=node('div',{class:'preset-card-body'}),actions=node('div',{class:'preset-actions'}),use=node('button',{class:'button compact primary',text:'Use skin'}),add=node('button',{class:'button compact',text:'Test preview',title:'Add this skin’s layers and interactions to your current design'});
   use.addEventListener('click',()=>task(use,async()=>{await loadProject(()=>preset.createAsync?preset.createAsync():preset.create(),p=>{replace(p,preset.name+' opened. Preparing the keyboard skin.');navigate('design');});await nativeBuildUI.openForProject(true);}));add.addEventListener('click',()=>task(add,()=>loadProject(()=>preset.createAsync?preset.createAsync():preset.create(),p=>{replace(p,preset.name+' · preview only. Choose Use on my keyboard to upload.');navigate('design');setMode('test');playing=true;renderTransport();paint();})));actions.append(use,add);body.append(node('span',{class:'preset-category',text:preset.testSkin?'Test skin · '+preset.category:preset.category}),node('h2',{text:preset.name}),node('p',{text:preset.description}),...(preset.testSkin?[node('p',{class:'panel-note',text:'Make it yours: edit layers and reactions, then save your own copy. Keyboard builds for this test skin are coming later.'})]:[]),actions);if(preset.preview){const photo=node('img',{src:'../studio/examples/community-collection/previews/'+preset.id+'.png',alt:preset.name+' preview',loading:'lazy',width:640,height:184});photo.className='preset-photo';card.append(photo,body);}else card.append(preview,body);$('preset-grid').append(card);
  }
 }
 function navigate(next){if(next==='export'){navigate('design');openExport();return;}if(next==='interactions'){next='design';inspect('interactions');}if(!['design','presets','export'].includes(next))next='design';route=next;if(next!=='design')creatorSetup.exit();for(const section of document.querySelectorAll('[data-page]'))section.hidden=section.dataset.page!==next;for(const link of document.querySelectorAll('[data-route]')){if(link.dataset.route===next)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');}if(location.hash!=='#'+next)window.history.replaceState(null,'','#'+next);if(next==='presets')renderPresets();if(window.studioHost)window.studioHost.routeChanged(next);document.querySelector('[data-page="'+next+'"] h1').focus({preventScroll:true});document.documentElement.scrollTop=0;}
 function gameInstructions(){const id=project.layers.find(l=>l.visible&&l.type==='collection'&&['cloud-courier','prism-breaker','dune-runner'].includes(l.text))?.text;return id==='prism-breaker'?'Space: start / launch · ← → or A / D: move paddle · R: restart':id==='cloud-courier'?'Space or ↑: flap · R: restart':id==='dune-runner'?'Space or ↑: jump · R: restart':'';}
 function setMode(next){showDesign();mode=next;frame.classList.toggle('test-mode',mode==='test');frame.classList.toggle('key-select-mode',mode==='keys');$('mode-keys').setAttribute('aria-pressed',String(mode==='keys'));$('key-selection-help').hidden=mode!=='keys';$('mode-edit').setAttribute('aria-pressed',String(next==='edit'));$('mode-test').setAttribute('aria-pressed',String(next==='test'));$('mode-hint').textContent=next==='test'?gameInstructions()||'Press keys or click this preview. Reactions appear here in the app.':'Click a layer to select it. Drag to move, or use the position fields.';renderSelection();$('preview-test-status').hidden=next!=='test';if(next==='test'){ $('preview-test-status').textContent='Ready for your keys · click the keyboard preview or press a key. This tests the app preview, not the physical screen.';frame.focus({preventScroll:true});}}
 function coords(event){const rect=frame.getBoundingClientRect();return{x:(event.clientX-rect.left)/rect.width*1920,y:(event.clientY-rect.top)/rect.height*550};}
 function eventLocation(code){const key=layout[codes.indexOf(code)];return key?{x:((key.x||0)+key.width/2)*1920/1800,y:((key.y||0)+key.height/2)*550/500}:{x:960,y:275};}
 function emit(type,key='KeyA',position=eventLocation(key),ruleId){const origins=R.captureMotionOrigins(project,time,previewEvents(),motionOptions());events.push({id:++eventSequence,type,key,...position,clock,timelineTime:time,origins,strength:1,...(ruleId?{ruleId}:{})});if(events.length>256){const old=events.shift();for(const rule of project.rules)if(rule.effect==='toggle'&&rule.strength>0&&R.matches(rule,old))toggleBase[rule.id]=!toggleBase[rule.id];}$('event-count').textContent=events.length+' events';if(mode==='test')$('preview-test-status').textContent='Received '+title(key.replace(/^Key|^Digit/,''))+' · '+title(type)+' · '+events.length+' events in the app preview';paint();}
 function resetPreview(){time=0;clock=0;clearReactions();$('event-count').textContent='0 events';renderTransport();paint();}
 async function chooseDialog(titleText,description,accept='Continue',cancel='Cancel'){const dialog=$('studio-dialog'),origin=document.activeElement;$('dialog-title').textContent=titleText;$('dialog-description').textContent=description;$('dialog-accept').textContent=accept;$('dialog-cancel').textContent=cancel;$('dialog-accept').disabled=false;$('dialog-cancel').disabled=false;dialog.showModal();$('dialog-cancel').focus();return new Promise(resolve=>{function done(value){dialog.close();$('dialog-accept').removeEventListener('click',yes);$('dialog-cancel').removeEventListener('click',no);dialog.removeEventListener('cancel',esc);origin?.focus();resolve(value);}const yes=()=>done(true),no=()=>done(false),esc=e=>{e.preventDefault();done(false);};$('dialog-accept').addEventListener('click',yes);$('dialog-cancel').addEventListener('click',no);dialog.addEventListener('cancel',esc);});}
 async function request(url,options){if(window.studioHost){const result=await window.studioHost.request(url,options);return new Response(result.body,{status:200,headers:{'Content-Type':result.type}});}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{return await fetch(url,{...options,signal:controller.signal});}catch(e){throw Error(e.name==='AbortError'?'The local operation timed out. Your project is safe; try again.':'The local service could not be reached. Keep this editor open and try again.');}finally{clearTimeout(timer);}}
 async function task(button,fn){if(busy)return;busy=true;button.disabled=true;button.setAttribute('aria-busy','true');try{await fn();}catch(e){notify(e.message,true);if(button.id==='export-unreal')$('export-result').textContent=e.message;}finally{busy=false;button.disabled=false;button.removeAttribute('aria-busy');}}
 function exportProject(){try{const value=M.validate(project);download(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),safeName()+'.cpskin');notify('Editable project exported. Your local draft remains available.');}catch(e){notify(e.message,true);}}
 async function importRaster(file){if(!file)return;const loadToken=projectLoader.begin();if(!/\.(png|jpe?g|webp)$/i.test(file.name)||file.size>8*1024*1024)throw Error('Choose a PNG, JPEG or WebP image up to 8 MB.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('The image could not be read.'));reader.readAsDataURL(file);});const info=M.rasterInfo(data);const image=await createImageBitmap(file);image.close();const w=Math.min(info.width,1920),h=Math.min(info.height,550),ratio=Math.min(w/info.width,h/info.height,1);const layer=M.createLayer('image',{name:file.name.replace(/\.[^.]+$/,''),image:data,width:Math.round(info.width*ratio),height:Math.round(info.height*ratio)});if(!projectLoader.current(loadToken)){notify('Image import was cancelled because the active design changed.');return false;}if(mutate(p=>p.layers.push(layer),{message:'Image added as an editable layer.'})){selected=layer.id;renderAll();return true;}return false;}
 options($('layer-type'),M.types);options($('keyframe-property'),M.properties);options($('preset-category'),[{value:'all',label:'All categories'},...[...new Set(['Community skins','Nature','Space','Ocean & water','Weather','City & machines','Abstract','Games',...P.list.map(p=>p.category),...P.list.flatMap(p=>p.tags||[])])].map(c=>({value:c,label:c}))]);
 on('new-project','click',()=>{navigate('design');replace(M.createProject('Untitled skin'),'New canvas created. Undo restores the previous scene.');});
 for(const id of ['save-project','export-project'])on(id,'click',exportProject);on('open-project','click',()=>$('project-file').click());
 on('project-file','change',async()=>{const file=$('project-file').files[0];$('project-file').value='';if(!file)return;try{if(file.size>32*1024*1024)throw Error('Project files must be 32 MB or smaller.');await loadProject(async()=>M.validate(JSON.parse(await file.text())),next=>{replace(next,'Project opened. Undo restores the previous scene.');navigate('design');});}catch(e){notify('Could not open project: '+e.message,true);}});
 on('project-name','change',()=>mutate(p=>{p.name=$('project-name').value.trim()||'Untitled skin';}));on('project-description','change',()=>mutate(p=>{p.description=$('project-description').value;},{inspector:false,rules:false}));on('project-duration','change',()=>{const duration=Number($('project-duration').value);if(project.layers.some(l=>l.keyframes.some(k=>k.time>duration))){notify('Move or remove keyframes beyond the new duration first.',true);$('project-duration').value=project.duration;return;}if(mutate(p=>p.duration=duration))time=Math.min(time,duration);});on('project-fps','change',()=>mutate(p=>p.fps=Number($('project-fps').value)));on('canvas-background','change',()=>mutate(p=>p.canvas.background=$('canvas-background').value));on('engine-target','change',()=>mutate(p=>p.engineTarget=$('engine-target').value));
 on('undo','click',()=>{project=history.undo();selected=project.layers.some(l=>l.id===selected)?selected:project.layers.at(-1)?.id;clearReactions();scheduleSave();renderAll();notify('Undone.');});on('redo','click',()=>{project=history.redo();clearReactions();selected=project.layers.some(l=>l.id===selected)?selected:project.layers.at(-1)?.id;scheduleSave();renderAll();notify('Redone.');});
 on('add-layer','click',()=>{const layer=M.createLayer($('layer-type').value,$('layer-type').value==='text'?{text:'Your words',width:800,height:180,x:560,y:185}:{});if(mutate(p=>p.layers.push(layer),{message:layer.name+' layer added.'})){selected=layer.id;renderAll();}});
 on('duplicate-layer','click',()=>{const layer=selectedLayer();if(!layer)return;const copy=M.clone(layer);copy.id=M.uid();copy.name=layer.name+' copy';copy.locked=false;copy.x+=20;copy.y+=20;if(mutate(p=>p.layers.push(copy),{message:'Layer duplicated.'})){selected=copy.id;renderAll();}});
 on('delete-layer','click',()=>{if(selected)mutate(p=>{p.layers=p.layers.filter(l=>l.id!==selected);p.rules=p.rules.filter(r=>r.target!==selected);},{message:'Layer and its targeted rules removed. Undo is available.'});});
 for(const[id,delta]of [['layer-up',1],['layer-down',-1]])on(id,'click',()=>mutate(p=>{const i=p.layers.findIndex(l=>l.id===selected);if(i>=0&&i+delta>=0&&i+delta<p.layers.length)[p.layers[i],p.layers[i+delta]]=[p.layers[i+delta],p.layers[i]];}));
 for(const input of document.querySelectorAll('[data-layer]')){input.addEventListener('input',()=>{const layer=selectedLayer(),key=input.dataset.layer;if(layer&&!layer.locked&&['range','color'].includes(input.type)){try{const next=M.clone(project);next.layers.find(l=>l.id===selected)[key]=input.type==='color'?input.value:Number(input.value);project=M.validate(next);paint();}catch{}}const out=document.querySelector('[data-value="'+input.dataset.layer+'"]');if(out)out.textContent=input.dataset.layer==='opacity'?Math.round(Number(input.value)*100)+'%':input.value;});input.addEventListener('change',()=>{const layer=selectedLayer();if(!layer||layer.locked)return;const key=input.dataset.layer,value=['text','name','color','color2','blend','font','fontWeight','textAlign','textVertical'].includes(key)?input.value:Number(input.value);if(mutate(p=>{p.layers.find(l=>l.id===selected)[key]=value;},{inspector:false,rules:key==='name'})){input.setAttribute('aria-invalid','false');$('field-error').textContent='';}else{input.setAttribute('aria-invalid','true');input.setAttribute('aria-describedby','field-error');$('field-error').textContent=$('studio-status').textContent;}});}
 function place(operation,region){const layer=selectedLayer();if(!layer)return;mutate(p=>{const index=p.layers.findIndex(l=>l.id===selected);p.layers[index]=M.placeLayer(p.layers[index],operation,region);},{message:'Layer positioned. Undo is available.'});}
 for(const button of document.querySelectorAll('[data-place]')){button.disabled=false;button.addEventListener('click',()=>place(button.dataset.place));}
 on('place-on-key','click',()=>{const value=$('placement-key').value,k=value!==''?layout[Number(value)]:null;if(!k){notify('Choose a keyboard key first.',true);return;}place('fill',{x:(k.x||0)*1920/1800+5,y:(k.y||0)*550/500+5,width:k.width*1920/1800-10,height:k.height*550/500-10});});
 window.StudioImageConverter.mount({importRaster,download});
 async function creatorRequest(action,input){if(window.studioHost)return window.studioHost.send(action,input);const response=await request('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Request':action},body:JSON.stringify(input)});const value=await response.json();if(!response.ok)throw Error(value.error||'The creator action failed.');return value;}
 window.StudioMotionPath.mount({selected:selectedLayer,project:()=>project,notify,commit:(id,frames)=>mutate(p=>{const l=p.layers.find(v=>v.id===id);l.keyframes=l.keyframes.filter(f=>!['x','y'].includes(f.property)).concat(frames.map(f=>({...f,id:M.uid()})));l.motion={type:'none',speed:1,distance:0,turn:false};},{message:'Motion path added. Edit its points and timing in Animation keyframes.'})});
 window.StudioUnrealDockUI.mount({request:creatorRequest});
 window.StudioUnrealCookUI.mount({request:creatorRequest,notify});
 window.StudioPhotoUI.mount({request:creatorRequest,notify,addSubject:async(result,settings)=>{
  const layer=M.createLayer('image',{name:settings.name.slice(0,80),image:result.image,x:(1920-result.width)/2,y:(550-result.height)/2,width:result.width,height:result.height,motion:{type:settings.motion,speed:settings.speed,distance:settings.distance,turn:settings.motion==='swim'}});
  const loadToken=projectLoader.begin();await R.prepareImages({layers:[layer]});if(!projectLoader.current(loadToken))throw Error('The design changed while the subject was loading. Try adding it again.');
  const accepted=mutate(p=>{p.layers.push(layer);if(settings.effect!=='none')p.rules.push(M.createRule({target:layer.id,effect:settings.effect,strength:1.2,duration:1.4}));},{message:'Animated subject added. Select its layer to edit motion, placement and key reactions.'});if(accepted){selected=layer.id;renderAll();}return accepted;
 }});
 async function refreshUnrealWorkspaces(selectedId=$('unreal-workspace-list').value){const items=await creatorRequest('unreal-list',null);options($('unreal-workspace-list'),[{value:'',label:items.length?'Choose a local Unreal project':'No Unreal projects yet'},...items.map(item=>({value:item.id,label:item.name+' · '+item.engineTarget+' · '+new Date(item.createdAt).toLocaleDateString()}))]);if(items.some(item=>item.id===selectedId))$('unreal-workspace-list').value=selectedId;$('unreal-workspace-open').disabled=!$('unreal-workspace-list').value;}
 on('unreal-workspace-refresh','click',()=>task($('unreal-workspace-refresh'),refreshUnrealWorkspaces));
 on('unreal-workspace-open','click',()=>task($('unreal-workspace-open'),async()=>{await creatorRequest('unreal-open',{id:$('unreal-workspace-list').value});$('export-result').textContent='Saved Unreal project opened.';}));$('unreal-workspace-open').disabled=true;$('unreal-workspace-list').addEventListener('change',()=>{$('unreal-workspace-open').disabled=!$('unreal-workspace-list').value;});
 on('open-full-unreal','click',()=>task($('open-full-unreal'),async()=>{const sourceProject=M.validate(project);$('export-result').textContent='Preparing your design for Unreal editing. This step does not upload to the keyboard.';await nativeBuildUI.prepareForEditor(async()=>{try{const workspace=await creatorRequest('unreal-create',sourceProject);await refreshUnrealWorkspaces(workspace.id);$('export-result').textContent='Editable project saved. Opening the editor inside Companion…';await window.StudioEditorDockOpen(workspace.id);}catch(error){$('export-result').textContent=error.message;notify(error.message,true);}});}));
 on('layer-form','submit',e=>e.preventDefault());on('import-image','click',()=>$('image-file').click());on('image-file','change',async()=>{const file=$('image-file').files[0];$('image-file').value='';try{await importRaster(file);}catch(e){notify(e.message,true);}});
 frame.addEventListener('dragover',e=>{e.preventDefault();frame.classList.add('drop-active');});frame.addEventListener('dragleave',()=>frame.classList.remove('drop-active'));frame.addEventListener('drop',async e=>{e.preventDefault();frame.classList.remove('drop-active');try{if(e.dataTransfer.files.length!==1)throw Error('Drop one image at a time.');await importRaster(e.dataTransfer.files[0]);}catch(error){notify(error.message,true);}});
 frame.addEventListener('pointerdown',e=>{if(e.button!==0)return;const point=coords(e);if(mode==='keys'){const index=keyAt(point);keyDrag={add:!selectedKeys.has(index),seen:new Set()};selectKey(index);frame.setPointerCapture(e.pointerId);return;}if(mode==='test'){frame.focus();const index=keyAt(point);if(index>=0){pointerTestKey=codes[index];emit('keyDown',codes[index],point);}emit('pointer',index>=0?codes[index]:'any',point);frame.setPointerCapture(e.pointerId);return;}const l=e.target===$('resize-layer')?selectedLayer():R.hitTest(project,point.x,point.y,time,previewEvents(),motionOptions());selected=l?.id||null;renderLayers();renderInspector();renderKeyframes();renderSelection();if(!l||l.locked)return;if(l.keyframes.some(k=>['x','y','width','height'].includes(k.property))){notify('This layer has animated geometry. Edit its keyframes or position fields to change it.');return;}drag={start:point,original:M.clone(project),layer:M.clone(l),resize:e.target===$('resize-layer'),moved:false};frame.setPointerCapture(e.pointerId);});
 frame.addEventListener('pointermove',e=>{if(keyDrag){selectKey(keyAt(coords(e)));return;}if(!drag)return;const point=coords(e),l=project.layers.find(l=>l.id===drag.layer.id),snap=$('snap-grid').checked?10:1,round=v=>Math.round(v/snap)*snap;const dx=point.x-drag.start.x,dy=point.y-drag.start.y;drag.moved ||=Math.abs(dx)+Math.abs(dy)>2;if(drag.resize){l.width=Math.max(1,Math.min(7680,round(drag.layer.width+dx)));l.height=Math.max(1,Math.min(2200,round(drag.layer.height+dy)));}else{l.x=Math.max(-7680,Math.min(7680,round(drag.layer.x+dx)));l.y=Math.max(-2200,Math.min(2200,round(drag.layer.y+dy)));}paint();renderInspector();});
 function endDrag(cancel=false){if(!drag)return;const transaction=drag;drag=null;if(cancel){project=transaction.original;renderAll();return;}if(transaction.moved){try{project=history.commit(project);scheduleSave();renderAll();}catch(e){project=transaction.original;renderAll();notify(e.message,true);}}}
 frame.addEventListener('pointerup',()=>{if(pointerTestKey){emit('keyUp',pointerTestKey);pointerTestKey=null;}keyDrag=null;endDrag();});frame.addEventListener('pointercancel',()=>{pointerTestKey=null;keyDrag=null;endDrag(true);});
 function keyAt(point){return layout.findIndex(k=>point.x>=(k.x||0)*1920/1800&&point.x<=((k.x||0)+k.width)*1920/1800&&point.y>=(k.y||0)*550/500&&point.y<=((k.y||0)+k.height)*550/500);}
 function renderKeySelection(){for(const g of $('key-guides').children)g.classList.toggle('key-selected',selectedKeys.has(Number(g.dataset.keyIndex)));$('selected-keys-count').textContent=selectedKeys.size?selectedKeys.size+' keys selected':'No keys selected';$('interaction-selection-summary').textContent=selectedKeys.size?'New interactions will use '+selectedKeys.size+' highlighted keys.':'New interactions apply to all keys.';}
 function selectKey(index){if(index<0||!keyDrag||keyDrag.seen.has(index))return;keyDrag.seen.add(index);keyDrag.add?selectedKeys.add(index):selectedKeys.delete(index);renderKeySelection();}
 function showDesign(){if(!$('back-to-scene'))return;$('installed-skin-preview').hidden=true;$('installed-skin-empty').hidden=true;$('back-to-scene').hidden=true;$('preview-source-label').textContent='Editing: '+(project?.name||'Companion project');$('preview-kind').textContent='App preview';}
 function setExpanded(expanded){$('studio-main').classList.toggle('preview-expanded',expanded);$('expand-preview').setAttribute('aria-pressed',String(expanded));$('expand-preview').textContent=expanded?'↙ Back to editor':'⛶ Large preview';$('expand-preview').classList.toggle('return-to-editor',expanded);}
 function startTest(demo=true){navigate('design');setMode('test');setExpanded(true);playing=true;renderTransport();frame.scrollIntoView({block:'center',behavior:'instant'});frame.focus({preventScroll:true});if(demo){const rule=project.rules.find(r=>['keyDown','pointer','beat','caps'].includes(r.trigger));if(rule)emit(rule.trigger,rule.keys?.[0]||(rule.key==='any'?'Space':rule.key));else notify('This project has no interactions yet. Add one in the Interactions panel.');}notify('Preview test is running. Press keys or click the in-app keyboard; use Back to editor to keep editing.');}
 on('expand-preview','click',()=>{const expanded=!$('studio-main').classList.contains('preview-expanded');setExpanded(expanded);if(expanded)frame.scrollIntoView({block:'center',behavior:'instant'});else{setMode('edit');notify('Editing controls are back. Select a layer or key to keep designing.');}});
 on('mode-keys','click',()=>{setMode(mode==='keys'?'edit':'keys');$('show-keys').checked=true;$('key-guides').hidden=false;});on('select-all-keys','click',()=>{setMode('keys');$('show-keys').checked=true;$('key-guides').hidden=false;layout.forEach((_,i)=>selectedKeys.add(i));renderKeySelection();});on('clear-selected-keys','click',()=>{selectedKeys.clear();renderKeySelection();});
 on('mask-layer','click',()=>{const l=selectedLayer();if(!l||l.locked||!selectedKeys.size){notify('Select an unlocked layer and the keys to edit first.',true);return;}mutate(p=>p.layers.find(v=>v.id===l.id).keyMask=[...selectedKeys],{message:'This layer now appears only inside the selected keys.'});});on('unmask-layer','click',()=>{const l=selectedLayer();if(l&&!l.locked)mutate(p=>{delete p.layers.find(v=>v.id===l.id).keyMask;},{message:'Layer key mask removed.'});});
 let overlayBusy=false,toolsBusy=false;
 async function refreshOverlay(){if(!window.studioHost||overlayBusy||document.hidden||route!=='design'||!$('show-companion').checked)return;overlayBusy=true;try{const result=await window.studioHost.send('overlay',null);if(!$('show-companion').checked||route!=='design')return;$('companion-overlay').src=result.image;$('companion-overlay').hidden=false;$('companion-overlay').title=result.sample?'Your saved layout · sample readings in this test build':'Your current Companion display';}catch{$('companion-overlay').hidden=true;}finally{overlayBusy=false;}}
 on('show-companion','change',()=>{$('companion-overlay').hidden=!$('show-companion').checked;void refreshOverlay();});setInterval(refreshOverlay,1500);
 async function refreshTools(){if(!window.studioHost||toolsBusy||document.hidden||route!=='design')return;toolsBusy=true;try{const info=await window.studioHost.send('tools',null);creatorSetup.update(info);}catch{$('native-tools-status').textContent='Could not check installed tools. Retrying automatically.';}finally{toolsBusy=false;}}
 setInterval(refreshTools,5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refreshTools();});window.addEventListener('focus',()=>void refreshTools());on('unreal-setup-link','click',async()=>{try{await window.studioHost.send('unreal-setup',null);$('native-tools-status').textContent='Epic setup opened. Install 4.27 from Unreal Engine → Library. Companion will detect it automatically.';}catch(e){$('native-tools-status').textContent='Could not open Epic automatically. Use Download Epic / Unreal beside this button.';}});
 const nativeBuildUI=window.StudioBuildUI.setup({button:$('test-physical'),project:()=>project,request:async(action,input)=>{if(window.studioHost)return window.studioHost.send(action,input);const response=await request('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Request':action},body:JSON.stringify(input)});return action==='build-download'?new Uint8Array(await response.arrayBuffer()):response.json();},openTools:()=>{openExport();$('unreal-tools-details').open=true;},notify});
 function openExport(){$('project-export-dialog').showModal();void refreshTools();$('close-export').focus();}
 on('show-unreal-tools','click',()=>{openExport();$('unreal-tools-details').open=true;requestAnimationFrame(()=>{$('open-full-unreal').scrollIntoView({block:'center',behavior:'instant'});$('open-full-unreal').focus({preventScroll:true});});});
 on('close-export','click',()=>{$('project-export-dialog').close();$('show-unreal-tools').focus();});on('creator-setup-open','click',()=>{openExport();$('unreal-tools-details').open=true;$('native-tools-status').scrollIntoView({block:'center'});});
 window.StudioReactionPresetUI.setup({host:document.querySelector('.interaction-add-row'),context:()=>({project,layer:selectedLayer(),keys:StudioInteractions.selectedKeyCodes(selectedKeys,codes,M.validKey)}),apply:result=>{activeRule=result.ruleIds[0];if(mutate(p=>{p.rules=result.project.rules;},{message:result.preset.name+' added. Adjust its keys, colors and strength below.'}))inspect('interactions');},notify});
 function inspect(value){inspectorMode=value;$('inspector-empty').hidden=value==='interactions'||!!selectedLayer();$('layer-inspector-content').hidden=value!=='layer';$('interaction-inspector').hidden=value!=='interactions';$('inspect-layer').setAttribute('aria-pressed',String(value==='layer'));$('inspect-interactions').setAttribute('aria-pressed',String(value==='interactions'));}
 on('inspect-layer','click',()=>inspect('layer'));on('inspect-interactions','click',()=>inspect('interactions'));
 if(window.studioHost){window.studioHost.onExitCreation=()=>creatorSetup.exit();window.studioHost.onNavigate=next=>navigate(next);window.studioHost.onOpenPreset=async id=>{const preset=P.list.find(v=>v.id===id);if(!preset)return;try{await loadProject(()=>preset.createAsync?preset.createAsync():preset.create(),p=>{replace(p,preset.name+' opened. Undo restores your previous design.');navigate('design');setExpanded(false);showShelf('companion');});}catch(e){notify(e.message,true);}};}
 on('mode-edit','click',()=>setMode('edit'));on('mode-test','click',()=>startTest());on('show-keys','change',()=>$('key-guides').hidden=!$('show-keys').checked);on('play-toggle','click',()=>{playing=!playing;renderTransport();});on('restart-preview','click',resetPreview);on('timeline','input',()=>{playing=false;time=Number($('timeline').value);clock=time;clearReactions();renderTransport();paint();});
 on('keyframe-property','change',()=>{const l=selectedLayer();if(l)$('keyframe-value').value=R.layerAt(l,time)[$('keyframe-property').value];});on('add-keyframe','click',()=>{const l=selectedLayer();if(!l||l.locked)return;const property=$('keyframe-property').value,at=Math.round(time*100)/100,value=Number($('keyframe-value').value),easing=$('keyframe-easing').value;mutate(p=>{const layer=p.layers.find(l=>l.id===selected),existing=layer.keyframes.find(k=>k.property===property&&k.time===at);if(existing)Object.assign(existing,{value,easing});else layer.keyframes.push({id:M.uid(),time:at,property,value,easing});},{message:'Keyframe saved at '+at.toFixed(2)+' seconds.'});});
 for(const button of document.querySelectorAll('[data-test-event]')){button.disabled=false;button.addEventListener('click',()=>{emit(button.dataset.testEvent);notify(title(button.dataset.testEvent)+' event sent to the preview.');});}
 frame.addEventListener('keydown',e=>{if(e.isComposing||e.repeat)return;const modifierKey=/^(Control|Alt|Meta)(Left|Right)$/.test(e.code);if((e.ctrlKey||e.metaKey||e.altKey)&&!modifierKey)return;if(mode==='keys'){const index=codes.indexOf(e.code);if(index>=0){e.preventDefault();selectedKeys.has(index)?selectedKeys.delete(index):selectedKeys.add(index);renderKeySelection();}return;}if(mode==='test'){if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Tab'].includes(e.code)&&e.code!=='Tab')e.preventDefault();emit('keyDown',e.code);if(e.code==='CapsLock')emit('caps',e.code);}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code)){const l=selectedLayer();if(!l||l.locked)return;e.preventDefault();const amount=e.shiftKey?10:1;mutate(p=>{const v=p.layers.find(x=>x.id===selected);v.x+=e.code==='ArrowLeft'?-amount:e.code==='ArrowRight'?amount:0;v.y+=e.code==='ArrowUp'?-amount:e.code==='ArrowDown'?amount:0;},{rules:false});}});frame.addEventListener('keyup',e=>{if(mode==='test'&&!e.isComposing&&(!(e.ctrlKey||e.metaKey||e.altKey)||/^(Control|Alt|Meta)(Left|Right)$/.test(e.code)))emit('keyUp',e.code);});
 on('add-rule','click',()=>{const picker=$('effect-picker');picker.hidden=!picker.hidden;$('add-rule').setAttribute('aria-expanded',String(!picker.hidden));if(!picker.hidden)picker.querySelector('button')?.focus();});on('interaction-select-keys','click',()=>{setMode('keys');$('show-keys').checked=true;$('key-guides').hidden=false;frame.scrollIntoView({block:'center',behavior:'instant'});});for(const effect of StudioInteractions.effects){const choice=node('button',{class:'effect-choice',title:effect.description},[node('span',{text:effect.icon,'aria-hidden':'true'}),node('strong',{text:effect.name})]);choice.addEventListener('click',()=>addInteraction(effect.id));$('effect-picker').append(choice);}on('test-in-designer','click',()=>startTest());
 on('preset-search','input',e=>{if(!e.isComposing)renderPresets();});on('preset-search','compositionend',renderPresets);on('preset-category','change',renderPresets);on('clear-search','click',()=>{$('preset-search').value='';renderPresets();$('preset-search').focus();});
 for(const link of document.querySelectorAll('[data-route]'))link.addEventListener('click',e=>{e.preventDefault();navigate(link.dataset.route);});window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)));
 on('export-png','click',()=>task($('export-png'),async()=>{const snapshot=M.clone(project),at=time,reactions=previewEvents(),movement={...motionOptions(),rules:snapshot.rules},base={...toggleBase},capturedGames=R.captureGames?.(ctx),name=safeName();await R.prepareImages(snapshot);const out=document.createElement('canvas');out.width=1920;out.height=550;R.draw(out.getContext('2d'),snapshot,at,reactions,{...movement,toggleBase:base,capturedGames});const blob=await new Promise(resolve=>out.toBlob(resolve,'image/png'));if(!blob)throw Error('The preview could not be exported.');download(blob,name+'.png');notify('Full-resolution PNG exported.');}));
 on('export-unreal','click',()=>task($('export-unreal'),async()=>{const name=safeName();$('export-result').textContent='Preparing source project…';const response=await request('/api/export',{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Request':'export'},body:JSON.stringify(project)});if(!response.ok){const error=await response.json();$('export-result').textContent=error.error||'Source export failed. Try again.';throw Error(error.error||'Source export failed.');}download(await response.blob(),name+'-unreal-source.zip');$('export-result').textContent='Source exported. Open the included README before building in Unreal Editor. Keyboard .pak compatibility is not yet verified.';notify('Unreal source ZIP exported.');}));
 on('inspect-pak','click',()=>$('pak-file').click());on('pak-file','change',()=>{const file=$('pak-file').files[0];$('pak-file').value='';if(!file)return;task($('inspect-pak'),async()=>{if(file.size>128*1024*1024)throw Error('The development inspector accepts .pak files up to 128 MB.');notify('Reading package metadata…');const response=await request('/api/inspect',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Studio-Request':'inspect'},body:file});const report=await response.json();if(!response.ok)throw Error(report.error||'Package inspection failed.');$('pak-report').textContent=JSON.stringify(report,null,2);$('pak-report').hidden=false;notify('Package inspected locally. No files were executed or uploaded to the keyboard.');});});
 on('shortcuts-help','click',()=>chooseDialog('Editor shortcuts','Ctrl + S — save an editable project\nCtrl + Z — undo\nCtrl + Shift + Z — redo\nArrow keys — nudge a selected layer when the canvas is focused\nShift + Arrow — nudge by 10 pixels\nDelete — remove a selected layer outside text fields\n\nTest interactions only captures keys while the canvas is focused.','Got it','Close'));
 document.addEventListener('keydown',e=>{if(e.isComposing||$('studio-dialog').open||$('reaction-presets-dialog')?.open||$('native-build-dialog')?.open)return;const editing=/^(INPUT|TEXTAREA|SELECT)$/.test(e.target.tagName)||e.target.isContentEditable;if((e.ctrlKey||e.metaKey)&&e.code==='KeyS'){e.preventDefault();exportProject();}if(editing)return;if((e.ctrlKey||e.metaKey)&&e.code==='KeyZ'){e.preventDefault();$(e.shiftKey?'redo':'undo').click();}if(e.code==='Delete'&&mode==='edit'&&route==='design')$('delete-layer').click();if(e.code==='Escape')endDrag(true);});
 window.addEventListener('beforeunload',e=>{if(saveTimer)saveDraft();if(unsaved){e.preventDefault();e.returnValue='';}});window.addEventListener('storage',e=>{if((e.key===DRAFT_KEY||e.key===null)&&e.newValue!==draftSnapshot)showDraftConflict();if(e.key===StudioScenes.KEY){try{scenes=StudioScenes.load(localStorage,project);renderScenes();}catch(error){notify(error.message,true);}}});
 on('reload-draft','click',async()=>{try{const snapshot=localStorage.getItem(DRAFT_KEY);await loadProject(()=>{const next=StudioStorage.load(localStorage);if(!next)throw Error('The other tab removed its saved draft. Save your current project as a file.');return next;},next=>{if(localStorage.getItem(DRAFT_KEY)!==snapshot)throw Error('The saved draft changed again while opening. Your current design is safe; try loading the latest draft again.');draftSnapshot=snapshot;draftConflict=false;$('draft-conflict').hidden=true;replace(next,'Latest local draft loaded. Undo restores the scene you were editing.');});}catch(e){notify(e.message,true);}});
 on('save-conflict-copy','click',exportProject);
 let keyboardSkinState=null,skinBusy=false,selectedSceneSlot=0,shelf='xpanel';
 function showShelf(next){shelf=next;for(const name of ['xpanel','companion']){const tab=$('tab-'+name);tab.setAttribute('aria-selected',String(name===next));tab.tabIndex=name===next?0:-1;$(name+'-skins-panel').hidden=name!==next;}}
 for(const name of ['xpanel','companion']){on('tab-'+name,'click',()=>showShelf(name));on('tab-'+name,'keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?'xpanel':e.key==='End'?'companion':name==='xpanel'?'companion':'xpanel';showShelf(next);$('tab-'+next).focus();}});}
 function renderKeyboardSkins(){const state=keyboardSkinState;for(const id of ['keyboard-skins-refresh','keyboard-skin-default','keyboard-skin-set-default'])$(id).disabled=skinBusy||(!state&&id!=='keyboard-skins-refresh');if(!state)return;const active=state.slots.find(v=>v.slot===state.active);$('keyboard-skin-summary').textContent='Active · '+(active?.name||state.active);const list=$('keyboard-skin-slots');list.replaceChildren();for(const item of state.slots){const b=node('button',{class:'skin-slot'+(item.empty?' is-empty':''),'aria-pressed':String(item.slot===state.active),'aria-label':'XPANEL slot '+item.slot+' · '+item.name+(item.isDefault?' · Default':'')},[node('span',{class:'skin-slot-top'},[node('span',{text:'SLOT '+item.slot}),node('span',{class:'skin-slot-marker',text:item.slot===state.active?'● Active':item.isDefault?'★ Default':''})]),node('strong',{text:item.name}),node('small',{text:item.isDefault?'Your default skin':item.empty?'Empty keyboard slot':'Click to apply on keyboard'})]);b.disabled=item.empty||skinBusy;b.addEventListener('click',()=>keyboardSkinAction('select',{slot:item.slot},true));list.append(b);}}
 async function keyboardSkinAction(action,input={},showImage=false){if(!window.studioHost||skinBusy)return;if(showImage)creatorSetup.exit();skinBusy=true;renderKeyboardSkins();$('keyboard-skins-status').textContent=action==='read'?'Reading installed skins…':action==='set-default'?'Saving your preferred default…':'Loading skin on your keyboard…';try{const value=await window.studioHost.send('keyboard-skins',{action,input});keyboardSkinState=value;renderKeyboardSkins();if(showImage){const name=value.slots.find(v=>v.slot===value.active)?.name||'Skin';$('installed-skin-empty').hidden=!!value.thumbnail;$('installed-skin-empty').textContent=name+' is active on your physical keyboard. A preview image is unavailable.';if(value.thumbnail){$('installed-skin-preview').src=value.thumbnail;$('installed-skin-preview').hidden=false;}else $('installed-skin-preview').hidden=true;$('back-to-scene').hidden=false;$('preview-source-label').textContent='XPANEL skin: '+name+' · saved thumbnail';$('preview-kind').textContent='Physical keyboard active';$('selection-box').hidden=true;$('preview-test-status').hidden=true;}$('keyboard-skins-status').textContent='Default: '+value.defaultName+' · Slot '+value.defaultSlot+(showImage?' · Applied on keyboard. The app shows its saved thumbnail, not live video.':'');}catch(e){$('keyboard-skins-status').textContent=e.message;if(!keyboardSkinState)$('keyboard-skin-summary').textContent='Keyboard unavailable';}finally{skinBusy=false;renderKeyboardSkins();}}
 on('keyboard-skins-refresh','click',()=>keyboardSkinAction('read'));on('keyboard-skin-default','click',()=>keyboardSkinAction('default',{},true));on('keyboard-skin-set-default','click',async()=>{if(await chooseDialog('Use this as your default XPANEL skin?','Return to my default will select the active skin. All five XPANEL skin files and the original starting-skin record are kept.','Set default'))await keyboardSkinAction('set-default');});on('back-to-scene','click',()=>{showDesign();setMode('edit');notify('Your Companion design is shown again. The physical keyboard keeps its XPANEL skin.');});
 void keyboardSkinAction('read');
 let scenes=null;try{scenes=StudioScenes.load(localStorage,project);const matching=scenes.slots.findIndex(p=>p?.id===project.id);if(matching>=0)selectedSceneSlot=matching;}catch(e){$('scene-library-status').textContent=e.message;}
 async function openSavedScene(index){projectLoader.cancel();selectedSceneSlot=index;renderScenes();const saved=scenes?.slots[index];if(!saved){$('scene-library-status').textContent='Space '+(index+1)+' selected. Save your current design here.';return;}try{const result=await loadProject(()=>saved,p=>{replace(p,p.name+' selected. The in-app preview is running.');showDesign();setMode('edit');playing=!matchMedia('(prefers-reduced-motion: reduce)').matches;renderTransport();paint();});if(result.status==='loaded')await nativeBuildUI.openForProject(true);}catch(e){notify(e.message,true);}}
 function renderScenes(){if(!scenes)return;window.studioHost?.projectsChanged(scenes);const list=$('companion-scene-slots');list.replaceChildren();for(let i=0;i<5;i++){const p=scenes.slots[i],button=node('button',{class:'skin-slot'+(!p?' is-empty':''),'aria-pressed':String(i===selectedSceneSlot),'aria-label':'Companion project '+(i+1)+' · '+(p?.name||'Empty')},[node('span',{class:'skin-slot-top',text:'PROJECT '+(i+1)}),node('strong',{text:p?.name||'Empty space'}),node('small',{text:p?'Select skin · preview':'Select, then save your design'})]);button.addEventListener('click',()=>void openSavedScene(i));list.append(button);}$('scene-library-status').textContent='Selected: project '+(selectedSceneSlot+1)+' · Select a saved skin to preview and apply its matching build.';}
 function saveScenes(next){try{scenes=StudioScenes.save(localStorage,next);renderScenes();return true;}catch(e){$('scene-library-status').textContent='Could not save projects. '+e.message;return false;}}
 on('scene-save','click',async()=>{if(!scenes)return;const index=selectedSceneSlot,design=M.clone(project),expected=M.clone(scenes.slots[index]);if(expected&&expected.id!==design.id&&!await chooseDialog('Replace this saved project?',expected.name+' will be replaced in this Companion project space. XPANEL skins are unaffected. Export it first if you want another copy.','Replace project'))return;const save=()=>StudioScenes.updateSlot(localStorage,design,index,design,expected);try{scenes=navigator.locks?await navigator.locks.request('centerpiece-companion-scene-library',save):save();renderScenes();$('scene-library-status').textContent=design.name+' saved to project '+(index+1)+'.';notify('Project saved on this PC.');}catch(e){if(e.code==='STUDIO_SCENE_CONFLICT'){try{scenes=StudioScenes.load(localStorage,project);renderScenes();}catch{}}$('scene-library-status').textContent=e.message;notify(e.message,true);}});on('scene-export-backup','click',exportProject);renderScenes();
 if(window.studioHost){
  window.studioHost.onOpenSavedProject=async index=>{try{scenes=StudioScenes.load(localStorage,project);await openSavedScene(index);navigate('design');setExpanded(false);showShelf('companion');}catch(e){notify(e.message,true);}};
  window.studioHost.onNewProject=()=>{replace(M.createProject('Untitled skin'),'New skin project created. Undo restores your previous design.');navigate('design');setExpanded(false);showShelf('companion');};
  window.studioHost.onLibraryAction=async(action,input)=>{if(!Number.isInteger(input?.index)||input.index<0||input.index>4)throw Error('Choose a saved project space.');const candidate=M.validate(input.project),index=input.index;
   const change=()=>{if(!Number.isFinite(input.expiresAt)||Date.now()>=input.expiresAt)throw Error('This library request expired before it could save. Refresh My skins and try again.');const current=StudioScenes.load(localStorage,project);if(action==='archive'){if(JSON.stringify(current.slots[index])!==JSON.stringify(candidate))throw Error('This project changed since the library was opened. Refresh My skins before archiving.');current.slots[index]=null;}else if(action==='restore'){if(current.slots[index]!==null)throw Error('This space now contains another project. Choose a free space.');current.slots[index]=candidate;}else throw Error('Unknown library action.');return StudioScenes.save(localStorage,current);};
   scenes=navigator.locks?await navigator.locks.request('centerpiece-companion-scene-library',change):change();renderScenes();return{saved:true};};
 }
 on('publish-project','click',()=>task($('publish-project'),async()=>{if(!window.studioHost)throw Error('Open Studio inside Companion to submit a skin for community review.');await window.studioHost.send('review-project',M.validate(project));notify('Review draft prepared in My skins. Your design is kept.');}));
 if(window.studioWindow){document.body.classList.add('desktop');document.querySelector('.studio-window').hidden=false;for(const[id,action]of [['window-min','minimize'],['window-max','maximize'],['window-close','close']])on(id,'click',()=>window.studioWindow.control(action));}
 (window.studioHost?request('/src/layout.json'):fetch('../src/layout.json')).then(r=>r.json()).then(data=>{layout=data.keys;StudioSpace.setLayout(layout);options($('placement-key'),[{value:'',label:'Choose a key'},...physical.map((label,i)=>({value:String(i),label:label+' · position '+(i+1)}))]);const svg=$('key-guides');layout.forEach((k,i)=>{const group=document.createElementNS('http://www.w3.org/2000/svg','g'),rect=document.createElementNS(group.namespaceURI,'rect'),text=document.createElementNS(group.namespaceURI,'text'),x=(k.x||0)*1920/1800,y=(k.y||0)*550/500,w=k.width*1920/1800,h=k.height*550/500;for(const[a,v]of Object.entries({x:x+5,y:y+5,width:w-10,height:h-10,rx:7}))rect.setAttribute(a,v);text.setAttribute('x',x+w/2);text.setAttribute('y',y+h/2+6);text.setAttribute('text-anchor','middle');text.textContent=physical[i]||'';group.dataset.keyIndex=String(i);group.append(rect,text);svg.append(group);});}).catch(()=>notify('Key guides could not load; the skin editor is still available.',true));
 void refreshTools();R.prepareImages(project).then(paint).catch(e=>notify(e.message,true));renderAll();navigate(location.hash.slice(1)||'design');notify(loadError||'Local development preview. Choose a preset or start editing any layer.',!!loadError);if(!loaded&&!loadError)saveDraft();requestAnimationFrame(tick);
 // Read-only inspection surface for isolated end-to-end tests; no hardware APIs.
 window.skinStudio={get project(){return M.clone(project);},get selected(){return selected;},get events(){return M.clone(events);},get time(){return time;},get playing(){return playing;}};
})();

