(function(){
 'use strict';
 window.StudioBuildUI={setup({button,project,request,openTools,notify}){
  const el=(tag,props={},children=[])=>{const n=document.createElement(tag);for(const[k,v]of Object.entries(props)){if(k==='text')n.textContent=v;else if(k==='class')n.className=v;else n.setAttribute(k,v);}n.append(...children);return n;};
  const dialog=el('dialog',{id:'native-build-dialog','aria-labelledby':'native-build-heading','aria-describedby':'native-build-description'}),heading=el('h2',{id:'native-build-heading',text:'Build for your keyboard'}),close=el('button',{type:'button',class:'button compact',text:'×','aria-label':'Close keyboard build'});
  const description=el('p',{id:'native-build-description',class:'panel-note',text:'Build a saved copy of this design. Missing Microsoft creator tools can install automatically; Windows may ask for approval. After app updates, missing creator tools install automatically when Unreal 4.27 is detected.'}),name=el('strong',{class:'native-build-name'}),status=el('p',{role:'status',id:'native-build-status'}),steps=el('ol',{class:'native-build-steps','aria-label':'Build progress'}),requirements=el('div',{class:'native-build-requirements'}),error=el('p',{class:'error-text',role:'alert',hidden:''});
  const start=el('button',{type:'button',class:'button primary',text:'Build this skin'}),cancel=el('button',{type:'button',class:'button danger-text',text:'Cancel build',hidden:''}),tools=el('button',{type:'button',class:'button',text:'Set up build tools',hidden:''}),save=el('button',{type:'button',class:'button',text:'Save .pak',hidden:''});
  const install=el('button',{type:'button',class:'button',text:'Install creator tools',hidden:''});
  const result=el('p',{class:'panel-note',hidden:''});dialog.append(el('div',{class:'native-build-heading'},[heading,close]),description,name,requirements,status,steps,error,result,el('div',{class:'dialog-actions'},[tools,install,cancel,save,start]));document.body.append(dialog);
  const stages=[['compile','Prepare creator components'],['generate','Create your scene'],['cook','Build keyboard assets'],['package','Package the skin'],['verify','Check package integrity']];
  let job=null,snapshot=null,checking=false,pollTimer=null,polling=false,origin=null,restoring=false,selectionVersion=0,dependencyTimer=null,dependencyMessage='',previewOnly=false,activateAfterBuild=false;
  const device=window.StudioDeviceTestUI.setup({host:dialog,request,build:()=>job,notify});
  const LAST_BUILD='centerpiece-studio-last-build';
  function remember(){try{if(job?.id)localStorage.setItem(LAST_BUILD,job.id);}catch{}}
  const active=()=>job&&['queued','building'].includes(job.state);
  function draw(){
   remember();device.sync();name.textContent=job?.projectName||snapshot?.name||'';status.textContent=dependencyMessage|| (restoring?'Finding your last build…':checking?'Checking installed build tools…':job?.label||'Ready to build');error.hidden=!job?.error;error.textContent=job?.error?(job.error.message+' ('+job.error.code+')'):'';
   start.hidden=!!active();start.disabled=checking||restoring||previewOnly;start.textContent=previewOnly?'Preview only':job?'Build current design':'Build this skin';cancel.hidden=!active();save.hidden=previewOnly||job?.state!=='ready';result.hidden=previewOnly||job?.state!=='ready';result.textContent='The package passed its build and integrity checks. Visuals and key reactions still need to be tested on the keyboard.';
   button.textContent=active()?'◷ Building skin…':'▶ Use on my keyboard';steps.hidden=!job;steps.replaceChildren();const index=stages.findIndex(s=>s[0]===job?.stage);
   for(const[id,label]of stages){const item=el('li',{text:label}),i=stages.findIndex(s=>s[0]===id);if(job?.state==='ready'||(index>=0&&i<index))item.className='complete';else if(id===job?.stage)item.setAttribute('aria-current','step');steps.append(item);}
  }
  function schedule(){clearTimeout(pollTimer);if(active())pollTimer=setTimeout(poll,1200);}
  let editorReady=null;
  async function finishEditor(){const callback=editorReady;editorReady=null;if(callback){dialog.close();await callback();}}
  async function poll(){if(polling||!active())return;polling=true;try{job=await request('build-status',{id:job.id});draw();if(job.state==='ready'){notify(job.projectName+' built.');if(editorReady)await finishEditor();else if(activateAfterBuild){activateAfterBuild=false;await device.select();}}}catch(e){error.hidden=false;error.textContent=e.message+' Rechecking…';}finally{polling=false;schedule();}}
  async function check(){checking=true;requirements.replaceChildren();tools.hidden=true;draw();try{const report=await request('physical-test',snapshot);previewOnly=report.previewOnly===true;if(previewOnly){job=null;requirements.append(el('p',{class:'panel-note',text:report.previewReason}));return;}const missing=report.requirements.filter(r=>['engine','windows-cpp','windows-sdk','netfx-sdk','source-target'].includes(r.id)&&r.status==='missing');tools.hidden=!missing.some(r=>r.id==='engine'||r.id==='source-target');install.hidden=!missing.some(r=>['windows-cpp','windows-sdk','netfx-sdk'].includes(r.id));for(const r of missing)requirements.append(el('p',{class:'panel-note',text:r.detail}));}catch(e){requirements.append(el('p',{class:'panel-note',text:e.message}));tools.hidden=false;}finally{checking=false;draw();}}
  async function sceneHash(value){const bytes=new TextEncoder().encode(JSON.stringify(window.StudioModel.validate(value),null,2)+'\n');return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');}
  async function recover(){const version=++selectionVersion;restoring=true;draw();try{const hash=await sceneHash(snapshot),found=await request('build-latest',{sceneSha256:hash});if(version!==selectionVersion)return;job=found?.sceneSha256===hash?found:null;schedule();}catch(e){notify('Could not find this skin’s build: '+e.message,true);}finally{if(version===selectionVersion){restoring=false;draw();}}}
  async function openForProject(applySaved=false){if(applySaved)editorReady=null;if(applySaved&&active()){notify('A skin is already building. Wait for it to finish before switching skins.');return;}activateAfterBuild=applySaved;origin=document.activeElement;if(!active())snapshot=window.StudioModel.validate(project());draw();if(!dialog.open)dialog.showModal();close.focus();if(!active()){await check();if(!previewOnly)await recover();}if(applySaved&&!previewOnly){if(job?.state==='ready'){activateAfterBuild=false;await device.select();}else if(tools.hidden&&!checking&&!restoring){start.click();}}}
  button.addEventListener('click',()=>void openForProject(true));button.disabled=false;
  close.addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>origin?.isConnected&&origin.focus({preventScroll:true}));
  tools.addEventListener('click',()=>{dialog.close();openTools();});
  async function beginBuild(){job=await request('build-start',snapshot);requirements.replaceChildren();tools.hidden=true;install.hidden=true;draw();schedule();}
  async function dependencyPoll(){try{const value=await request('dependencies-status',null);dependencyMessage=value.message;draw();if(value.state==='ready'){dependencyMessage='';await beginBuild();checking=false;draw();return;}if(['failed','restart-required'].includes(value.state)){checking=false;install.disabled=false;install.hidden=false;draw();return;}dependencyTimer=setTimeout(dependencyPoll,2000);}catch(e){checking=false;dependencyMessage=e.message;install.disabled=false;draw();}}
  async function installTools(){checking=true;install.disabled=true;dependencyMessage='Preparing Microsoft creator tools…';draw();try{await request('dependencies-install',null);await dependencyPoll();}catch(e){checking=false;dependencyMessage=e.message;install.disabled=false;draw();}}
  install.addEventListener('click',()=>{snapshot=window.StudioModel.validate(project());void installTools();});
  start.addEventListener('click',async()=>{if(checking||restoring||active())return;activateAfterBuild=!editorReady;checking=true;dependencyMessage='';draw();try{snapshot=window.StudioModel.validate(project());const deps=await request('dependencies-check',null);if(deps.engineFound&&!deps.ready){await installTools();return;}await beginBuild();}catch(e){job={state:'failed',label:'Build needs attention',projectName:snapshot.name,error:{code:e.code||'STUDIO_BUILD_START',message:e.message}};}if(!dependencyMessage)checking=false;draw();});
  cancel.addEventListener('click',async()=>{editorReady=null;activateAfterBuild=false;cancel.disabled=true;try{job=await request('build-cancel',{id:job.id});draw();schedule();}catch(e){error.hidden=false;error.textContent=e.message;}finally{cancel.disabled=false;}});
  save.addEventListener('click',async()=>{save.disabled=true;try{const bytes=await request('build-download',{id:job.id,sceneSha256:job.sceneSha256}),url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'})),a=el('a',{href:url,download:(job.projectName||'skin').replace(/[^\p{L}\p{N} _-]/gu,'').slice(0,70)+'.pak'});document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){error.hidden=false;error.textContent=e.message;}finally{save.disabled=false;}});
  async function prepareForEditor(callback){if(active()){notify('A skin is already building. Wait for it to finish.',true);return;}await openForProject(false);if(previewOnly)return;editorReady=callback;activateAfterBuild=false;if(job?.state==='ready')await finishEditor();else if(tools.hidden&&!checking&&!restoring)start.click();}
  return{dialog,openForProject,prepareForEditor};
 }};
})();

