(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./model.js'):root.StudioModel);if(typeof module==='object'&&module.exports)module.exports=api;else root.StudioCollectionPresets=api;})(typeof globalThis!=='undefined'?globalThis:this,function(M){
 'use strict';
 const node=typeof module==='object'&&module.exports,cache=new Map();
 const definitions=[
  ['storm-meadow','Storm meadow','Photorealistic','A real-life grassy meadow beneath rugged mountains and ominous storm clouds. A tornado moves in the distance; rain drifts through the view and distant lightning flickers overhead.','Every key press releases a new branching lightning bolt from a different cloud. All layers and reactions remain editable.',['#172429','#c3d4e0','#e6f1ff'],'lightning',.42,90],
  ['lantern-festival','Lantern festival','Animated','A procession of warm paper lanterns drifts above moonlit temple roofs.','Press any key or click to send gold embers and a gentle gust through the lanterns.',['#11172a','#ee884e','#ffd58a'],'sparkle',2.5,85],
  ['paper-ocean','Paper ocean','Animated','A folded-paper whale sails through six layers of ocean with a fleet of tiny paper boats.','Press any key or click to make the whale rise and blow a sparkling spray.',['#b1d8d5','#e2b775','#d8f2e5'],'burst',2.8,50],
  ['neon-speedway','Neon speedway','Animated','Drive a violet grand tourer toward a striped sunset through a rain-slick neon city.','Press Space for a speed boost; other keys throw neon sparks from the road.',['#110e26','#719ded','#f575b1'],'sparkle',1.6,60],
  ['clockwork-garden','Clockwork garden','Animated','Brass flowers mesh into a living mechanical garden among copper stems and fireflies.','Press any key or click to wind the garden and accelerate its interlocking gears.',['#0c2825','#c9aa6e','#ecd790'],'pulse',3,60],
  ['prism-bloom','Prism bloom','Animated','An illuminated field of faceted mint and amethyst crystal grows from a quiet slate landscape.','Press keys or click near a crystal to make it grow and scatter luminous fragments.',['#141e31','#92dbcc','#b3a0db'],'sparkle',2.8,70],
  ['tidal-observatory','Tidal observatory','Realistic','Sunlight reveals fine caustics and black volcanic stone beneath a clear coastal tidal pool.','Press keys or touch the water to send widening ripples across the pool.',['#103b46','#a3dec9','#edf5dc'],'ripple',3,65],
  ['alpine-reflection','Alpine reflection','Realistic','Photographic snow peaks reflect across a glacial lake in the stillness before sunrise.','Press any key or click to release a drifting gust of fine snow over the lake.',['#102936','#afc6d5','#f0e6e1'],'burst',3.8,45],
  ['storm-window','Storm window','Realistic','Rain slides over glass in front of a cinematic city of teal shadows and warm traffic bokeh.','Press keys or click to clear a circle through the drops. Space adds a brief distant lightning glow.',['#071923','#a5d5e2','#e0b17d'],'ripple',3.4,110],
  ['ember-forge','Ember forge','Realistic','A glowing steel billet rests on a scarred anvil, lit by the warm coals of a working forge.','Press keys or click to strike the steel and throw a fan of falling sparks.',['#1b100d','#ff9c45','#ffe2a0'],'burst',2.6,65],
  ['moon-tranquility','Moon tranquility','Realistic','Crisp lunar regolith and crater shadows stretch beneath a small blue Earth in black space.','Press keys or click the ground to lift a slow cloud of lunar dust.',['#080b0d','#cbc9bc','#f2ecd7'],'burst',4.2,35],
  ['atlas-launch','Atlas · first light','Realistic rocket','A detailed white orbital vehicle stands beside a photographic launch tower at first light.','Press Space or click to ignite the engines, roll smoke across the pad and launch the rocket.',['#5b6b75','#ffb556','#ffe1a7'],'launch',8,70],
  ['lighthouse-watch','Lighthouse watch','Photorealistic','Atlantic swells shimmer below a coastal lighthouse. Its beam sweeps through the sea mist as gulls cross the horizon.','Press any key or click to send ripples through the sea and brighten the beacon.',['#193344','#e7c892','#eaf2df'],'ripple',3.5,80],
  ['redwood-sanctuary','Redwood sanctuary','Photorealistic','Original photographic redwoods, drifting leaves, warm sun shafts, moving stream reflections and floating pollen.','Press any key or click to stir the stream and scatter warm forest light.',['#1b3229','#b7c681','#eae4b4'],'sparkle',3.4,75],
  ['coral-current','Coral current','Photorealistic','A richly textured coral reef hosts a moving school of fish, rising bubbles and wavering underwater light.','Press any key or click to stir the school into a quick upward turn and send bubbles rising.',['#0d4857','#9bd7ca','#dfedd3'],'burst',3.2,85],
  ['sakura-tram','Sakura tram','Animated','A cream tram rolls through a mountain town under flowering cherry trees and a constant drift of petals.','Press any key or click to send a gust through the falling cherry blossoms.',['#526e83','#dfb5c4','#f1d7ce'],'sparkle',3.2,95],
  ['desert-caravan','Desert caravan','Animated','A lantern-lit camel caravan crosses layered desert dunes beneath a crescent moon and twinkling stars.','Press any key or click to lift a wind-driven stream of desert sand.',['#242438','#d4b393','#ecceae'],'burst',3,60],
  ['jellyfish-ballet','Jellyfish ballet','Animated','Translucent jellyfish pulse and drift in a deep ocean, with trailing tentacles and fine suspended particles.','Press any key or click to lift and illuminate the glowing bloom.',['#07132d','#8cd7da','#d4bde9'],'pulse',3.5,80],
  ['solar-orbit','Solar orbit','Animated','Five shaded planets and their moving moons orbit a glowing star. Saturn-like rings turn in the distance.','Press any key or click to launch a bright comet across your solar system.',['#060d20','#ebb87a','#b6e4ed'],'burst',3,90],
  ['rainy-cafe','Rainy café','Animated','Warm pendant lamps illuminate a steaming mug and a resting cat while rain slides past a city window.','Press any key or click to make the steam rise and paint warm light across the desk.',['#273341','#d9b28e','#efd4b3'],'heat',3,65],
  ['aurora-valley','Aurora valley','Animated','Luminous aurora curtains slowly fold above a snow-covered valley and a shimmering dark lake.','Press any key or click to lift and brighten the aurora above the mountains.',['#102b3b','#90d9ba','#bddadf'],'pulse',4,75],
  ['volcanic-drift','Volcanic drift','Animated','Molten rivers flow from a glowing crater while drifting ash and sparks lift into a dusky sky.','Press any key or click to release a burst of bright volcanic embers.',['#332c35','#ed9c53','#ffd197'],'burst',3.2,95],
  ['cloud-courier','Cloud courier','Game','Guide a little airmail plane through sky towers. A complete keyboard game with collisions, score and restart.','Space or Up flaps. Pass towers to score. Press R or Space after a crash to restart.',['#164975','#e5c68b','#fff0c4'],'pulse',.12,40],
  ['prism-breaker','Prism breaker','Game','Clear three rows of luminous prisms with a bouncing ball. Three lives, paddle control, collision scoring and a win state.','Space serves; Left/Right or A/D moves the paddle. Press R to restart.',['#0c1731','#b4e8e0','#f3e3af'],'pulse',.12,40],
  ['dune-runner','Dune runner','Game','A little desert fox runs across a moving dune landscape. Time your jumps over cacti as the pace rises.','Space or Up jumps. Clear cacti to score. Press R or Space after a collision to restart.',['#39284b','#efc195','#f6ddbd'],'pulse',.12,40]
 ];
 function raster(name){if(!node)return'';const fs=require('node:fs'),path=require('node:path'),file=path.join(__dirname,'assets','collection',name);return'data:image/'+(name.endsWith('.jpg')?'jpeg':'png')+';base64,'+fs.readFileSync(file).toString('base64');}
 function build(d,embedded=node){if(d[0]==='storm-meadow'){const p=M.createProject(d[1]);p.id='collection-storm-meadow';p.description=d[3]+' '+d[4];p.duration=120;p.canvas.background='#172429';p.layers=[M.createLayer('image',{id:'meadow-landscape',name:'Dark mountain meadow photograph',image:embedded?raster('storm-meadow-dark.jpg'):'',locked:false}),M.createLayer('plasma',{id:'meadow-cloud-motion',name:'Slow cloud currents',y:0,height:550,color:'#a8b9cb',color2:'#53687c',opacity:.025,speed:.12,size:230,blend:'lighter',seed:923}),M.createLayer('image',{image:embedded?raster('storm-tornado.png'):'',id:'meadow-tornado',name:'Drifting tornado',x:1180,y:-45,width:300,height:450,color:'#172128',color2:'#4b5962',opacity:.65,speed:.65,size:12,seed:138,motion:{type:'drift',speed:.16,distance:70,turn:false}}),M.createLayer('rain',{id:'meadow-rain',name:'Wind-driven rain',color:'#b7c9db',opacity:.3,speed:.8,density:95,size:13,seed:217}),M.createLayer('lightning',{id:'meadow-lightning',name:'Cloud-to-ground lightning',x:0,y:65,width:1920,height:330,color:'#dbeaff',color2:'#8caef2',opacity:1,speed:.75,size:30,seed:739})];p.rules=['keyDown','pointer'].map(trigger=>M.createRule({trigger,key:'any',target:'meadow-lightning',effect:'lightning',color:'#e4efff',strength:1.6,duration:.65}));return M.validate(p);}const [id,name,style,description,interaction,colors,effect,duration,density]=d,p=M.createProject(name);p.id='collection-'+id;p.description=description+' '+interaction;p.duration=style==='Game'?120:id==='atlas-launch'?20:24;p.fps=style==='Game'?60:30;p.canvas.background=colors[0];p.engineTarget='4.27';
  if(embedded&&['Realistic','Realistic rocket','Photorealistic'].includes(style))p.layers.push(M.createLayer('image',{id:id+'-photograph',name:'Photographic environment',image:raster(id+'.jpg'),locked:true,seed:1847}));
  p.layers.push(M.createLayer('collection',{id:id+'-scene',name:style==='Game'?'Playable game':style==='Animated'?'Animated scene':'Interactive atmosphere',text:id,color:colors[1],color2:colors[2],speed:1,density,size:40,reactivity:1,seed:9187,image:embedded&&id==='atlas-launch'?raster('atlas-vehicle-display.png'):''}));
  p.rules=[M.createRule({id:id+'-keyboard',trigger:'keyDown',key:id==='atlas-launch'||style==='Game'?'Space':'any',target:id+'-scene',effect,color:colors[2],duration,strength:style==='Game'?0:.85}),M.createRule({id:id+'-pointer',trigger:'pointer',target:id+'-scene',effect,color:colors[2],duration,strength:style==='Game'?0:.85})];
  if(id==='neon-speedway')p.rules.push(M.createRule({id:id+'-boost',key:'Space',target:id+'-scene',effect:'pulse',color:colors[1],duration:3,strength:1.4}));
  if(id==='storm-window')p.rules.push(M.createRule({id:id+'-lightning',key:'Space',target:id+'-scene',effect:'flash',color:'#bdd4ee',duration:1.1,strength:.2}));
  return M.validate(p);
 }
 async function load(id){if(cache.has(id))return M.clone(cache.get(id));if(!definitions.some(d=>d[0]===id))throw Error('Choose a collection skin from the library.');let value;
  if(node){value=build(definitions.find(d=>d[0]===id));}
  else if(globalThis.studioHost?.send){value=await globalThis.studioHost.send('collection',id);}
  else if(globalThis.companion?.studioRequest){value=await globalThis.companion.studioRequest('collection',id);}
  else{const response=await fetch('/studio/examples/community-collection/'+id+'.cpskin');if(!response.ok)throw Error('This skin project could not be loaded. Try opening it again.');value=await response.json();}
  const project=M.validate(value);if(project.id!=='collection-'+id||(id==='storm-meadow'?!project.layers.some(l=>l.type==='lightning'):!project.layers.some(l=>l.type==='collection'&&l.text===id)))throw Error('The collection skin did not match the selected project.');cache.set(id,project);return M.clone(project);
 }
 const categories={'storm-meadow':'Weather','lantern-festival':'City & machines','paper-ocean':'Ocean & water','neon-speedway':'City & machines','clockwork-garden':'City & machines','prism-bloom':'Abstract','tidal-observatory':'Ocean & water','alpine-reflection':'Nature','storm-window':'Weather','ember-forge':'City & machines','moon-tranquility':'Space','atlas-launch':'Space','lighthouse-watch':'Ocean & water','redwood-sanctuary':'Nature','coral-current':'Ocean & water','sakura-tram':'City & machines','desert-caravan':'Nature','jellyfish-ballet':'Ocean & water','solar-orbit':'Space','rainy-cafe':'Weather','aurora-valley':'Nature','volcanic-drift':'Nature','cloud-courier':'Games','prism-breaker':'Games','dune-runner':'Games'};
 const list=definitions.map(d=>({id:d[0],name:d[1],title:d[1],testSkin:!['storm-meadow','tidal-observatory','cloud-courier','dune-runner','prism-breaker'].includes(d[0]),category:categories[d[0]],tags:[categories[d[0]],'Interactive',...(d[2]==='Game'?['Games']:['Animated']),...(['Realistic','Realistic rocket','Photorealistic'].includes(d[2])?['Photorealistic']:[])],style:d[2],description:d[3],interaction:d[4],colors:[...d[5]],nativeStatus:d[2]==='Game'||definitions.indexOf(d)>=definitions.findIndex(item=>item[0]==='lighthouse-watch')?'browser-project':'source-project',nativeVerified:false,preview:'/studio/examples/community-collection/previews/'+d[0]+'.png',create:()=>cache.has(d[0])?M.clone(cache.get(d[0])):build(d),createAsync:()=>load(d[0])}));
 return{list,load};
});

