(function(){
 'use strict';
 window.StudioDeviceTestUI={setup({host,request,build,notify}){
  const el=(tag,props={},children=[])=>{const n=document.createElement(tag);for(const[k,v]of Object.entries(props)){if(k==='text')n.textContent=v;else if(k==='class')n.className=v;else n.setAttribute(k,v);}n.append(...children);return n;};
  const section=el('section',{class:'native-device-test','aria-label':'Physical keyboard test'}),heading=el('h3',{text:'Display on your keyboard'}),status=el('p',{class:'panel-note',role:'status'}),choices=el('div',{class:'native-slot-choices'}),review=el('p',{class:'panel-note'}),error=el('p',{class:'error-text',role:'alert',hidden:''}),prepare=el('button',{type:'button',class:'button native-test-action',text:'Check keyboard slots'}),apply=el('button',{type:'button',class:'button native-test-action',text:'Upload and test',hidden:''}),restore=el('button',{type:'button',class:'button danger-text',text:'Restore previous skin'});
  section.append(heading,status,choices,review,error,el('div',{class:'dialog-actions'},[restore,prepare,apply]));host.append(section);
  let canRestore=false;
  let job=null,reviewToken=null,confirmation=false,timer=null,busy=false,buildId=null,applyWhenSafe=false;
  const active=()=>job&&['queued','running'].includes(job.state);
  function controls(){prepare.disabled=busy||!!active()||build()?.state!=='ready';apply.disabled=busy||!!active();restore.hidden=!canRestore;restore.disabled=!canRestore||busy||!!active();}
  function sync(){const current=build();section.hidden=current?.state!=='ready'&&!job;if(current?.id!==buildId&&!active()){buildId=current?.id;reviewToken=null;apply.hidden=true;choices.replaceChildren();review.textContent='';status.textContent='Checks the available skin slots before changing your keyboard.';}controls();}
  function show(value){job=value;controls();error.hidden=!job.error;error.textContent=job.error?job.error.message+' ('+job.error.code+')':'';const progress=job.progress;status.textContent=active()?(progress?.totalBytes?'Uploading skin · '+Math.min(100,Math.floor(progress.bytesQueued/progress.totalBytes*100))+'%':job.readOnly?'Checking your keyboard…':'Applying your keyboard skin…'):job.state==='failed'?'The keyboard operation needs attention.':'';
   if(job.state==='ready'&&job.result?.reviewOnly){const r=job.result;reviewToken=r.token;confirmation=r.requiresReplacementReview===true;apply.textContent=r.replacedWithoutBackup?'Replace “'+r.replaces+'” and use skin':confirmation?'Replace slot '+r.slot+' and use skin':'Use skin on keyboard';apply.classList.toggle('danger-text',r.replacedWithoutBackup===true);review.textContent=r.replacedWithoutBackup?'Replace “'+r.replaces+'” in keyboard slot '+r.slot+' with “'+r.name+'”. The overwritten skin cannot be restored by Companion. Your protected default remains available.':confirmation?'Test “'+r.name+'” in slot '+r.slot+'. This replaces the skin currently in that slot using the saved catalog file for restoration. Your default skin stays protected.':'Test “'+r.name+'” in slot '+r.slot+'. Your default skin stays protected.';apply.hidden=false;choices.replaceChildren();status.textContent='Slot checked. Ready for your review.';}
   if(job.result?.slotChoices){const available=job.result.slotChoices.some(slot=>slot.canReviewReplacement);if(available){status.textContent='Choose a slot to review before uploading.';error.hidden=true;}choices.replaceChildren();for(const slot of job.result.slotChoices){const choice=el('button',{type:'button',class:'button compact',text:'Slot '+slot.slot+' · '+(slot.name||slot.fileName||'Saved skin')+(slot.protected?' · protected':'')});choice.disabled=slot.protected===true;choice.addEventListener('click',()=>start('device-prepare',{id:build().id,sceneSha256:build().sceneSha256,slot:slot.slot,replaceWithoutBackup:slot.requiresPermanentReplacement===true}));choices.append(choice);}review.textContent='These five physical slots are shared with XPANEL. Choose one for your Companion skin. You will review the named replacement before anything is overwritten.';}
   if(job.state==='ready'&&job.result?.transportConfirmed){canRestore=true;controls();reviewToken=null;apply.hidden=true;review.textContent='The keyboard acknowledged the skin. Press keys to check its appearance and reactions. '+(job.result.replacedWithoutBackup?'Return to previous skin selects your protected skin; the overwritten file is not recoverable.':'Restore previous skin returns to your saved skin.');restore.textContent=job.result.replacedWithoutBackup?'Return to previous skin':'Restore previous skin';status.textContent='Skin transferred · visual test ready';notify('Skin transferred. Check the physical keyboard and press a few keys.');}
   if(job.state==='ready'&&(job.result?.restored||job.result?.previousSkinSelected)){canRestore=false;controls();reviewToken=null;apply.hidden=true;review.textContent=job.result.restored?'The previous skin was restored.':'Your previous skin is selected. The Companion skin remains in its chosen slot.';status.textContent='Restoration completed';}
   clearTimeout(timer);if(active())timer=setTimeout(poll,800);
   if(job.state==='ready'&&job.result?.reviewOnly&&applyWhenSafe){applyWhenSafe=false;if(!confirmation){const token=reviewToken;queueMicrotask(()=>{if(reviewToken===token)void start('device-execute',{token,confirmReplacement:false});});}}
  }
  async function poll(){try{show(await request('device-status',{id:job.id}));}catch(e){error.hidden=false;error.textContent=e.message;timer=setTimeout(poll,2000);}}
  async function start(action,input){if(busy||active())return;if(action==='device-prepare'){reviewToken=null;apply.hidden=true;review.textContent='';}busy=true;controls();error.hidden=true;try{show(await request(action,input));}catch(e){error.hidden=false;error.textContent=e.message;}finally{busy=false;controls();}}
  prepare.addEventListener('click',()=>{reviewToken=null;apply.hidden=true;const b=build();if(b?.state==='ready')void start('device-prepare',{id:b.id,sceneSha256:b.sceneSha256});});
  apply.addEventListener('click',()=>{if(reviewToken)void start('device-execute',{token:reviewToken,confirmReplacement:confirmation});});restore.addEventListener('click',()=>start('device-restore',{}));sync();return{sync,select:async()=>{if(busy||active()){notify('A keyboard transfer is already in progress. Wait for it to finish before selecting another skin.');return;}const b=build();if(b?.state!=='ready')return;applyWhenSafe=true;reviewToken=null;apply.hidden=true;await start('device-prepare',{id:b.id,sceneSha256:b.sceneSha256});}};
 }};
})();
