(()=>{
 if(window.parent===window||new URLSearchParams(location.search).get('embedded')!=='1')return;
 document.body.classList.add('embedded');const libraryRequests=new Map(),pending=new Map(),target=location.protocol==='file:'?'*':location.origin;
 function send(action,input){return new Promise((resolve,reject)=>{const id=crypto.randomUUID(),timer=setTimeout(()=>{pending.delete(id);reject(Error('The Companion operation timed out. Your draft is safe; try again.'));},30000);pending.set(id,{resolve,reject,timer});parent.postMessage({type:'studio-request',id,action,input},target);});}
 window.studioHost={send,onNavigate:null,projectsChanged:library=>parent.postMessage({type:'studio-projects-changed',library},target),routeChanged:route=>parent.postMessage({type:'studio-route',route},target),request:async(url,options={})=>{
  if(url==='/src/layout.json')return{type:'application/json',body:JSON.stringify(await send('layout',null))};
  if(url==='/api/export')return{type:'application/zip',body:await send('export',JSON.parse(options.body))};
  if(url==='/api/physical-test')return{type:'application/json',body:JSON.stringify(await send('physical-test',JSON.parse(options.body)))};
  if(url==='/api/inspect')return{type:'application/json',body:JSON.stringify(await send('inspect',await options.body.arrayBuffer()))};
  throw Error('Unknown Studio request.');
 }};
 window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==(location.protocol==='file:'?'null':location.origin))return;const d=e.data;if(d?.type==='studio-close-native-editor'){window.StudioEditorDockClose?.();return;}if(d?.type==='studio-exit-creation'){window.studioHost.onExitCreation?.();return;}if(d?.type==='studio-open-saved-project'&&Number.isInteger(d.index)&&d.index>=0&&d.index<5){window.studioHost.onOpenSavedProject?.(d.index);return;}if(d?.type==='studio-new-project'){window.studioHost.onNewProject?.();return;}if(d?.type==='studio-library-action'&&typeof d.id==='string'&&/^[-a-f0-9]{36}$/.test(d.id)&&['archive','restore'].includes(d.action)){if(!libraryRequests.has(d.id)){if(libraryRequests.size>=64)libraryRequests.delete(libraryRequests.keys().next().value);libraryRequests.set(d.id,Promise.resolve().then(()=>window.studioHost.onLibraryAction(d.action,d.input)));}libraryRequests.get(d.id).then(value=>parent.postMessage({type:'studio-library-result',id:d.id,value},target),error=>parent.postMessage({type:'studio-library-result',id:d.id,error:error.message},target));return;}if(d?.type==='studio-open-preset'&&typeof d.id==='string'&&/^[a-z][a-z0-9-]{0,79}$/.test(d.id)){window.studioHost.onOpenPreset?.(d.id);return;}if(d?.type==='studio-navigate'&&['design','presets','export'].includes(d.route)){window.studioHost.onNavigate?.(d.route);return;}if(d?.type!=='studio-response'||!pending.has(d.id))return;const p=pending.get(d.id);pending.delete(d.id);clearTimeout(p.timer);d.error?p.reject(Object.assign(Error(d.error),{code:d.code})):p.resolve(d.value);});
 window.addEventListener('DOMContentLoaded',()=>parent.postMessage({type:'studio-ready'},target));
})();
