(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./model.js'):root.StudioModel);if(typeof module==='object'&&module.exports)module.exports=api;else root.StudioPresets=api;})(typeof globalThis!=='undefined'?globalThis:this,function(M){
 'use strict';
 function make(id,name,category,description,colors,layers,reaction='ripple'){
  return{id,name,category,description,colors:[...colors],create(){
   const p=M.createProject(name);p.description=description;p.canvas.background=colors[0];
   p.layers=layers.map(([type,settings],i)=>M.createLayer(type,{name:settings.name||type.charAt(0).toUpperCase()+type.slice(1),color:colors[1],color2:colors[2]||colors[1],seed:173+i*271,...settings}));
   p.rules=[M.createRule({trigger:'keyDown',effect:reaction,color:colors[2]||colors[1],duration:reaction==='heat'?4:1.8,strength:1.1}),M.createRule({trigger:'pointer',effect:'ripple',color:colors[1],duration:2,strength:.9}),M.createRule({trigger:'beat',effect:'pulse',color:colors[2]||colors[1],duration:.7,strength:.45})];
   return M.validate(p);
  }};
 }
 const list=[
  make('aurora-drift','Aurora drift','Atmospheric','Slow curtains of mint and violet cross a quiet star field. Keys send luminous rings through the sky.',['#050d19','#44e5bf','#9778ff'],[['gradient',{color:'#030913',color2:'#10162f'}],['stars',{density:95,size:1.8,opacity:.68,speed:.25}],['aurora',{density:56,size:90,speed:.55,opacity:.85,blend:'screen'}],['wave',{y:240,height:310,size:25,speed:.35,opacity:.24}]]),
  make('electric-tide','Electric tide','Reactive','Layered cobalt currents break into cyan wave fronts with each key press.',['#031323','#28c6ff','#6779ff'],[['gradient',{color:'#04101f',color2:'#062b44'}],['wave',{size:46,density:70,speed:.9,opacity:.9}],['wave',{y:110,height:400,size:23,density:35,speed:.45,rotation:2,opacity:.55,blend:'screen'}],['particles',{size:3,density:45,speed:.45,opacity:.7}]]),
  make('ember-garden','Ember garden','Reactive','Warm drifting embers over charcoal. Every key leaves a small trail of heat.',['#120b0b','#ff9a45','#ff4a76'],[['gradient',{color:'#160c0e',color2:'#36180d'}],['plasma',{density:35,size:125,speed:.3,opacity:.32}],['fireflies',{density:65,size:5,speed:.8,opacity:.95}],['heatmap',{size:35,opacity:.55}]],'heat'),
  make('lunar-dust','Lunar dust','Atmospheric','Silver stars and restrained blue orbital trails drift across a deep lunar night.',['#060c18','#bfdcff','#648de5'],[['stars',{density:145,size:2.5,speed:.25}],['orbit',{density:65,size:4,speed:.35,opacity:.5}],['particles',{density:35,size:2,speed:.22,opacity:.38}]],'burst'),
  make('neon-circuit','Neon circuit','Reactive','A perspective grid and wandering neon energy form a responsive digital horizon.',['#0c071d','#8f67ff','#37e3df'],[['gradient',{color:'#10051e',color2:'#042432'}],['plasma',{size:80,density:40,speed:.55,opacity:.5,blend:'screen'}],['grid',{density:65,size:30,speed:1,opacity:.6}],['particles',{density:36,size:3,speed:1.3,opacity:.8}]],'flash'),
  make('rain-on-glass','Rain on glass','Atmospheric','Blue rain trails and ripples on a cool glass surface, with gentle key-driven splashes.',['#06131d','#5dc4e3','#b4ddef'],[['gradient',{color:'#081722',color2:'#173949'}],['rain',{density:140,size:19,speed:.95,opacity:.62}],['ripple',{density:25,size:65,speed:.6,y:140,height:410,opacity:.23}],['wave',{size:14,density:35,speed:.3,opacity:.15}]]),
  make('snowlight','Snowlight','Atmospheric','Fine snow falls in front of a soft blue-green glow. Pointer touches leave frozen halos.',['#081924','#bfe8f2','#83b6ef'],[['gradient',{color:'#061923',color2:'#193842'}],['aurora',{color:'#4abcb5',color2:'#629be0',size:45,speed:.2,opacity:.24}],['snow',{density:150,size:4,speed:.5,opacity:.9}],['stars',{density:30,size:1,speed:.15,opacity:.3}]],'burst'),
  make('signal-bloom','Signal bloom','Reactive','Coral and aqua particles move in expanding orbital patterns and erupt on key presses.',['#0d1020','#ff937e','#6ce9d4'],[['gradient',{color:'#130d20',color2:'#04202a'}],['orbit',{density:100,size:5,speed:.65,opacity:.8}],['rings',{size:100,density:30,speed:.45,opacity:.3}],['particles',{density:80,size:3,speed:.5,opacity:.8}]],'burst'),
  make('deep-current','Deep current','Atmospheric','Low emerald currents and fine suspended particles echo a quiet underwater scene.',['#031619','#24bcaa','#91ebd0'],[['gradient',{color:'#03141a',color2:'#06382e'}],['wave',{density:85,size:60,speed:.28,opacity:.6}],['wave',{color:'#115780',color2:'#40cab4',size:18,density:50,speed:.5,opacity:.32,blend:'screen'}],['particles',{density:65,size:2.5,speed:.3,opacity:.65}]]),
  make('solar-flare','Solar flare','Reactive','Hot amber plasma, expanding gold rings and small energetic sparks respond to every key.',['#18080c','#ffc063','#f5545a'],[['gradient',{color:'#19090c',color2:'#48171b'}],['plasma',{density:65,size:175,speed:.65,opacity:.8}],['rings',{size:85,density:55,speed:.55,opacity:.3,blend:'screen'}],['fireflies',{density:65,size:4,speed:1.5,opacity:.9}]],'burst'),
  make('violet-echo','Violet echo','Reactive','Fine overlapping violet circles expand into the dark and answer each key with a luminous echo.',['#0b0719','#b49cff','#eea6d9'],[['gradient',{color:'#090619',color2:'#231238'}],['ripple',{density:65,size:95,speed:.45,opacity:.7}],['rings',{size:40,density:25,speed:.25,opacity:.33}],['stars',{density:75,size:1.4,speed:.6,opacity:.6}]]),
  make('chromatic-flow','Chromatic flow','Reactive','A flowing field of peach, cyan and lilac with bright interference ribbons.',['#0d1221','#6ddddf','#ec9ba8'],[['gradient',{color:'#0c1830',color2:'#2a142c'}],['plasma',{density:75,size:180,speed:.5,opacity:.67}],['wave',{color:'#b7a0ff',color2:'#63dad9',density:85,size:42,speed:.7,opacity:.55,blend:'screen'}]],'pulse'),
  make('firefly-meadow','Firefly meadow','Atmospheric','Tiny gold lights wander over an abstract green meadow, with a warm glow under your fingertips.',['#071912','#dfdf79','#6ed6a0'],[['gradient',{color:'#05150f',color2:'#173820'}],['wave',{size:40,density:45,speed:.2,opacity:.2}],['fireflies',{density:90,size:4.5,speed:.48,opacity:.95}],['particles',{color:'#89bfa1',size:1.7,density:35,speed:.2,opacity:.3}]],'heat'),
  make('midnight-orbit','Midnight orbit','Atmospheric','Azure satellite paths and starlight orbit a quiet center. Click anywhere to disturb the geometry.',['#070c19','#5eacff','#c0a3ff'],[['stars',{density:135,size:1.8,speed:.4,opacity:.75}],['orbit',{density:140,size:4,speed:.6,opacity:.8}],['rings',{density:22,size:60,speed:.3,opacity:.22}]]),
  make('digital-mist','Digital mist','Minimal','A misty teal horizon carries a faint moving grid and fine floating points.',['#071a20','#51c3c4','#96e4d4'],[['gradient',{color:'#071a22',color2:'#163339'}],['plasma',{density:25,size:160,speed:.2,opacity:.3}],['grid',{density:38,size:20,speed:.4,opacity:.28}],['particles',{density:35,size:1.8,speed:.4,opacity:.5}]],'flash'),
  make('rose-quartz','Rose quartz','Atmospheric','Soft rose and lavender curtains with pinpoints of light, designed for a gentle ambient glow.',['#1a101e','#edb0c4','#b9b4f7'],[['gradient',{color:'#150e22',color2:'#3b2032'}],['aurora',{size:95,density:40,speed:.23,opacity:.5}],['stars',{density:72,size:1.6,speed:.35,opacity:.6}],['wave',{size:18,density:25,speed:.4,opacity:.2}]]),
  make('icebreak','Icebreak','Reactive','An icy blue field with a visible key heat map and quick crystal-like bursts.',['#06141f','#84dbff','#d6f6ff'],[['gradient',{color:'#061322',color2:'#123144'}],['heatmap',{density:55,size:32,opacity:.8}],['wave',{density:60,size:30,speed:.48,opacity:.35}],['snow',{density:45,size:2.2,speed:.4,opacity:.42}]],'burst'),
  make('afterglow','Afterglow','Minimal','Saturated red-orange particles hang over a sparse horizon; every press leaves a slow fading trace.',['#160c14','#ff9b79','#d677d1'],[['gradient',{color:'#180c15',color2:'#2c1826'}],['wave',{density:25,size:45,speed:.28,opacity:.3}],['fireflies',{density:35,size:5,speed:.35,opacity:.7}],['ripple',{density:18,size:110,speed:.18,opacity:.25}]],'heat'),
  make('cobalt-focus','Cobalt focus','Minimal','A restrained cobalt grid with small bright stars and precise key flashes.',['#060d19','#4f9ee7','#a0cfeb'],[['gradient',{color:'#040e1e',color2:'#09263a'}],['grid',{density:24,size:25,speed:.25,opacity:.35}],['stars',{density:32,size:1.8,speed:.2,opacity:.58}]],'flash'),
  make('velvet-spectrum','Velvet spectrum','Reactive','Deep violet ribbons cross a warm magenta haze. Rhythmic pulses and key bursts bring it to life.',['#170920','#ff74ca','#886cff'],[['gradient',{color:'#11071f',color2:'#42122f'}],['plasma',{size:130,density:60,speed:.4,opacity:.55}],['wave',{size:50,density:80,speed:.6,opacity:.65,blend:'screen'}],['particles',{density:60,size:3,speed:.7,opacity:.65}]],'burst')
 ];
 const launch=make('ignition','Ignition · orbital launch','Interactive','A silver orbiter on a midnight launchpad. Press Space or click the canvas to ignite, lift off and return.',['#040912','#ffb755','#fa633b'],[['gradient',{color:'#030810',color2:'#12213a'}],['nebula',{color:'#427ccc',color2:'#963c75',speed:.25}],['stars',{density:160,size:1.6,speed:.25,color:'#b7d9ff',color2:'#97cff7'}],['meteors',{density:15,size:15,speed:.25,opacity:.45,color:'#accfff'}],['rocket',{name:'Orbiter & launchpad',color:'#ffbb57',color2:'#ff633b',speed:1,size:60}]]);
 const original=launch.create;launch.create=()=>{const p=original(),rocket=p.layers.find(l=>l.type==='rocket');p.duration=18;p.rules=[M.createRule({key:'Space',target:rocket.id,effect:'launch',duration:7,color:'#ffb755'}),M.createRule({trigger:'pointer',target:rocket.id,effect:'launch',duration:7,color:'#ffb755'}),M.createRule({keys:['KeyW','KeyA','KeyS','KeyD'],effect:'sparkle',duration:1.4,color:'#9edbff',strength:.7})];return M.validate(p);};list.unshift(launch);
 list.push(make('deep-orbit','Deep orbit','Atmospheric','Colored nebulae and meteor trails respond with wide orbital shockwaves.',['#030a14','#5d9de4','#aa76ff'],[['nebula',{speed:.2}],['stars',{density:140,size:2}],['meteors',{density:45,size:38,speed:.5}]],'shockwave'));
 return{list};
});
