(()=>{'use strict';window.StudioUnrealCookUI={mount({request,notify}){
 const $=id=>document.getElementById(id),dialog=document.createElement('dialog');dialog.id='unreal-cook-dialog';dialog.setAttribute('aria-labelledby','unreal-cook-title');
 dialog.innerHTML='<div class="native-build-heading"><h2 id="unreal-cook-title">Build your Unreal edits</h2><button class="button compact" type="button" aria-label="Close Unreal build">×</button></div><p>Save your work in Unreal before building. This uses your edited map, Blueprints and materials. It keeps the original project and does not regenerate the scene.</p><p class="panel-note">Keyboard compatibility depends on its installed runtime. A successful cook does not add new native engine modules to the keyboard.</p><p class="unreal-cook-status" role="status"></p>';
 document.body.append(dialog);let job=null,timer=null,starting=false,opener=null;
 const cancel=document.createElement('button');cancel.className='button';cancel.textContent='Cancel build';cancel.hidden=true;dialog.append(cancel);
 const note=document.createElement('p');note.className='panel-note';note.textContent='Closing this panel keeps the build running. Cancel build stops it.';dialog.append(note);
 const status=dialog.querySelector('[role=status]'),device=StudioDeviceTestUI.setup({host:dialog,request,build:()=>job,notify});dialog.querySelector('button').addEventListener('click',()=>dialog.close());
 async function poll(){try{job=await request('unreal-cook-status',{id:job.id});status.textContent=job.error?.message||job.label;device.sync();cancel.hidden=!['building','queued'].includes(job.state);if(!cancel.hidden)timer=setTimeout(poll,1200);else if(job.state==='ready')await device.select();}catch(error){status.textContent=error.message;}}
 cancel.addEventListener('click',async()=>{cancel.disabled=true;try{await request('unreal-cook-cancel',{id:job.id});status.textContent='Cancelling build… Your saved project is kept.';}catch(error){status.textContent=error.message;}finally{cancel.disabled=false;}});
 dialog.addEventListener('close',()=>opener?.isConnected&&opener.focus());
 $('unreal-cook-start').disabled=false;$('unreal-cook-start').addEventListener('click',async()=>{opener=document.activeElement;if(!dialog.open)dialog.showModal();if(starting||job&&['building','queued'].includes(job.state))return;const id=$('unreal-workspace-list').value;if(!id){status.textContent='Choose a saved Unreal project first.';return;}starting=true;clearTimeout(timer);status.textContent='Preparing your Unreal project…';try{job=await request('unreal-cook-start',{id});device.sync();await poll();}catch(error){status.textContent=error.message;}finally{starting=false;}});
}};})();
