// Editor-only generation of paddle, ball and brick gameplay.
namespace StudioLayerBuilder {
void PrismVariables(Graph& B,const TSharedPtr<FJsonObject>& Layer,const FEdGraphPinType& Float){
 for(const TCHAR* N:{TEXT("GPhase"),TEXT("GScore"),TEXT("GBest"),TEXT("GLeft"),TEXT("GRight"),TEXT("GHit")})B.Variable(N,Float,TEXT("0"));
 B.Variable(TEXT("GPrism"),Float,TEXT("1"));B.Variable(TEXT("GPaddle"),Float,TEXT("960"));B.Variable(TEXT("GBallX"),Float,TEXT("960"));B.Variable(TEXT("GBallY"),Float,TEXT("437"));B.Variable(TEXT("GPreviousY"),Float,TEXT("437"));B.Variable(TEXT("GVx"),Float,TEXT("310"));B.Variable(TEXT("GVy"),Float,TEXT("-275"));B.Variable(TEXT("GLives"),Float,TEXT("3"));B.Variable(TEXT("GRemaining"),Float,TEXT("30"));
 for(int I=0;I<30;I++)B.Variable(*FString::Printf(TEXT("GBrick%d"),I),Float,TEXT("1"));
 const TSharedPtr<FJsonObject>* Keys=nullptr;if(Layer->TryGetObjectField(TEXT("nativeGameKeys"),Keys))for(const TCHAR* Group:{TEXT("action"),TEXT("restart"),TEXT("left"),TEXT("right")}){const TArray<TSharedPtr<FJsonValue>>* Rects=nullptr;if((*Keys)->TryGetArrayField(Group,Rects)&&Rects->Num()){auto R=(*Rects)[0]->AsObject();FString N=FString(TEXT("GTest_"))+Group;B.Variable(*(N+TEXT("X")),Float,FString::SanitizeFloat(Num(R,TEXT("x"),0)+Num(R,TEXT("width"),0)*.5f));B.Variable(*(N+TEXT("Y")),Float,FString::SanitizeFloat(Num(R,TEXT("y"),0)+Num(R,TEXT("height"),0)*.5f));}}
}
UEdGraphPin* PrismReset(Graph& B,UEdGraphPin* E){
 E=B.Set(TEXT("GBest"),B.Math(TEXT("FMax"),B.Get(TEXT("GBest")),B.Get(TEXT("GScore"))),E);
 for(const TCHAR* N:{TEXT("GScore"),TEXT("GLeft"),TEXT("GRight"),TEXT("GHit")})E=B.Set(N,0.f,E);
 E=B.Set(TEXT("GPhase"),1.f,E);E=B.Set(TEXT("GPaddle"),960.f,E);E=B.Set(TEXT("GBallX"),960.f,E);E=B.Set(TEXT("GBallY"),437.f,E);E=B.Set(TEXT("GVx"),310.f,E);E=B.Set(TEXT("GVy"),-275.f,E);E=B.Set(TEXT("GLives"),3.f,E);E=B.Set(TEXT("GRemaining"),30.f,E);
 for(int I=0;I<30;I++)E=B.Set(*FString::Printf(TEXT("GBrick%d"),I),1.f,E);return E;
}
void PrismInput(Graph& B,const TSharedPtr<FJsonObject>& L,V Down,V X,V Y,UEdGraphPin* E){
 auto* S=B.Node<UK2Node_ExecutionSequence>();S->AllocateDefaultPins();S->AddInputPin();B.Connect(E,B.Pin(S,TEXT("execute")));
 for(int I=0;I<2;I++){const TCHAR* Group=I?TEXT("right"):TEXT("left");const TCHAR* N=I?TEXT("GRight"):TEXT("GLeft");auto* Match=B.Branch(GameKeyMatch(B,L,Group,X,Y),S->GetThenPinGivenIndex(I));auto* Press=B.Branch(Down,B.Pin(Match,TEXT("then")));B.Set(N,B.Clamp(Add(B,B.Get(N),1.f),0,2),B.Pin(Press,TEXT("then")));B.Set(N,B.Clamp(Sub(B,B.Get(N),1.f),0,2),B.Pin(Press,TEXT("else")));}
 auto* Press=B.Branch(Down,S->GetThenPinGivenIndex(2));auto* Restart=B.Branch(GameKeyMatch(B,L,TEXT("restart"),X,Y),B.Pin(Press,TEXT("then")));PrismReset(B,B.Pin(Restart,TEXT("then")));auto* Action=B.Branch(GameKeyMatch(B,L,TEXT("action"),X,Y),B.Pin(Restart,TEXT("else")));auto* Ended=B.Branch(GameGreater(B,B.Get(TEXT("GPhase")),1.5f),B.Pin(Action,TEXT("then")));PrismReset(B,B.Pin(Ended,TEXT("then")));B.Set(TEXT("GPhase"),1.f,B.Pin(Ended,TEXT("else")));
}
void PrismTick(Graph& B,UMaterialParameterCollection* C,V Delta,UEdGraphPin* E){
 V DT=B.Clamp(Delta,0,.03333334f);auto* S=B.Node<UK2Node_ExecutionSequence>();S->AllocateDefaultPins();B.Connect(E,B.Pin(S,TEXT("execute")));
 auto* Playing=B.Branch(GameAnd(B,GameGreater(B,B.Get(TEXT("GPhase")),.5f),GameLess(B,B.Get(TEXT("GPhase")),1.5f)),S->GetThenPinGivenIndex(0));E=B.Pin(Playing,TEXT("then"));
 V Left=B.Unary(TEXT("Conv_BoolToFloat"),GameGreater(B,B.Get(TEXT("GLeft")),0.f),TEXT("InBool")),Right=B.Unary(TEXT("Conv_BoolToFloat"),GameGreater(B,B.Get(TEXT("GRight")),0.f),TEXT("InBool"));
 E=B.Set(TEXT("GPaddle"),B.Clamp(Add(B,B.Get(TEXT("GPaddle")),Mul(B,Sub(B,Right,Left),Mul(B,860.f,DT))),104,1816),E);
 E=B.Set(TEXT("GPreviousY"),B.Get(TEXT("GBallY")),E);E=B.Set(TEXT("GBallX"),Add(B,B.Get(TEXT("GBallX")),Mul(B,B.Get(TEXT("GVx")),DT)),E);E=B.Set(TEXT("GBallY"),Add(B,B.Get(TEXT("GBallY")),Mul(B,B.Get(TEXT("GVy")),DT)),E);E=B.Set(TEXT("GHit"),0.f,E);
 auto* Steps=B.Node<UK2Node_ExecutionSequence>();Steps->AllocateDefaultPins();while(Steps->Pins.Num()-1<35)Steps->AddInputPin();B.Connect(E,B.Pin(Steps,TEXT("execute")));
 auto* Wall=B.Branch(GameOr(B,GameLess(B,B.Get(TEXT("GBallX")),26.f),GameGreater(B,B.Get(TEXT("GBallX")),1894.f)),Steps->GetThenPinGivenIndex(0));E=B.Set(TEXT("GBallX"),B.Clamp(B.Get(TEXT("GBallX")),26,1894),B.Pin(Wall,TEXT("then")));B.Set(TEXT("GVx"),Mul(B,B.Get(TEXT("GVx")),-1.f),E);
 auto* Top=B.Branch(GameLess(B,B.Get(TEXT("GBallY")),79.f),Steps->GetThenPinGivenIndex(1));E=B.Set(TEXT("GBallY"),79.f,B.Pin(Top,TEXT("then")));B.Set(TEXT("GVy"),B.Unary(TEXT("Abs"),B.Get(TEXT("GVy"))),E);
 V Paddle=GameAnd(B,GameGreater(B,B.Get(TEXT("GVy")),0.f),GameAnd(B,GameLess(B,B.Get(TEXT("GPreviousY")),456.f),GameAnd(B,GameGreater(B,B.Get(TEXT("GBallY")),447.f),GameLess(B,B.Unary(TEXT("Abs"),Sub(B,B.Get(TEXT("GBallX")),B.Get(TEXT("GPaddle")))),107.f))));
 auto* Bounce=B.Branch(Paddle,Steps->GetThenPinGivenIndex(2));E=B.Set(TEXT("GBallY"),446.f,B.Pin(Bounce,TEXT("then")));E=B.Set(TEXT("GVy"),Mul(B,B.Unary(TEXT("Abs"),B.Get(TEXT("GVy"))),-1.f),E);E=B.Set(TEXT("GVx"),Mul(B,Sub(B,B.Get(TEXT("GBallX")),B.Get(TEXT("GPaddle"))),4.2f),E);auto* Vertical=B.Branch(GameLess(B,B.Unary(TEXT("Abs"),B.Get(TEXT("GVx"))),60.f),E);B.Set(TEXT("GVx"),60.f,B.Pin(Vertical,TEXT("then")));
 for(int I=0;I<30;I++){const float X=170+(I%10)*160,Y=110+(I/10)*56;FString N=FString::Printf(TEXT("GBrick%d"),I);V Alive=GameAnd(B,GameGreater(B,B.Get(*N),.5f),GameLess(B,B.Get(TEXT("GHit")),.5f));auto* Eligible=B.Branch(Alive,Steps->GetThenPinGivenIndex(3+I));V DX=Sub(B,B.Get(TEXT("GBallX")),B.Clamp(B.Get(TEXT("GBallX")),X,X+146)),DY=Sub(B,B.Get(TEXT("GBallY")),B.Clamp(B.Get(TEXT("GBallY")),Y,Y+38));auto* Hit=B.Branch(GameLess(B,Add(B,Mul(B,DX,DX),Mul(B,DY,DY)),100.f),B.Pin(Eligible,TEXT("then")));E=B.Set(*N,0.f,B.Pin(Hit,TEXT("then")));E=B.Set(TEXT("GHit"),1.f,E);E=B.Set(TEXT("GScore"),Add(B,B.Get(TEXT("GScore")),25.f),E);E=B.Set(TEXT("GRemaining"),Sub(B,B.Get(TEXT("GRemaining")),1.f),E);auto* Side=B.Branch(GameAnd(B,GameGreater(B,B.Get(TEXT("GPreviousY")),Y-10),GameLess(B,B.Get(TEXT("GPreviousY")),Y+48)),E);B.Set(TEXT("GVx"),Mul(B,B.Get(TEXT("GVx")),-1.f),B.Pin(Side,TEXT("then")));B.Set(TEXT("GVy"),Mul(B,B.Get(TEXT("GVy")),-1.f),B.Pin(Side,TEXT("else")));}
 auto* Lost=B.Branch(GameGreater(B,B.Get(TEXT("GBallY")),570.f),Steps->GetThenPinGivenIndex(33));E=B.Set(TEXT("GLives"),Sub(B,B.Get(TEXT("GLives")),1.f),B.Pin(Lost,TEXT("then")));auto* Dead=B.Branch(GameLess(B,B.Get(TEXT("GLives")),.5f),E);E=B.Set(TEXT("GPhase"),2.f,B.Pin(Dead,TEXT("then")));B.Set(TEXT("GBest"),B.Math(TEXT("FMax"),B.Get(TEXT("GBest")),B.Get(TEXT("GScore"))),E);E=B.Set(TEXT("GPhase"),0.f,B.Pin(Dead,TEXT("else")));E=B.Set(TEXT("GBallX"),B.Get(TEXT("GPaddle")),E);E=B.Set(TEXT("GBallY"),437.f,E);E=B.Set(TEXT("GVx"),310.f,E);B.Set(TEXT("GVy"),-275.f,E);
 auto* Won=B.Branch(GameLess(B,B.Get(TEXT("GRemaining")),.5f),Steps->GetThenPinGivenIndex(34));E=B.Set(TEXT("GPhase"),3.f,B.Pin(Won,TEXT("then")));B.Set(TEXT("GBest"),B.Math(TEXT("FMax"),B.Get(TEXT("GBest")),B.Get(TEXT("GScore"))),E);
 E=S->GetThenPinGivenIndex(1);auto Publish=[&](const FString& N,V R,V G,V Blue,V A){auto* Color=B.Call(UKismetMathLibrary::StaticClass(),TEXT("MakeColor"));B.Input(Color,TEXT("R"),R);B.Input(Color,TEXT("G"),G);B.Input(Color,TEXT("B"),Blue);B.Input(Color,TEXT("A"),A);auto* Set=B.Call(UKismetMaterialLibrary::StaticClass(),TEXT("SetVectorParameterValue"));B.Pin(Set,TEXT("Collection"))->DefaultObject=C;B.Input(Set,TEXT("ParameterName"),N);B.Input(Set,TEXT("ParameterValue"),B.Pin(Color,TEXT("ReturnValue")));B.Connect(E,B.Pin(Set,TEXT("execute")));E=B.Pin(Set,TEXT("then"));};
 Publish(TEXT("GameState"),B.Get(TEXT("GPhase")),B.Get(TEXT("GScore")),B.Get(TEXT("GPaddle")),B.Get(TEXT("GLives")));Publish(TEXT("GameBall"),B.Get(TEXT("GBallX")),B.Get(TEXT("GBallY")),B.Get(TEXT("GVx")),B.Get(TEXT("GVy")));
 for(int G=0;G<8;G++){V Channels[4];for(int J=0;J<4;J++)Channels[J]=G*4+J<30?B.Get(*FString::Printf(TEXT("GBrick%d"),G*4+J)):V(0.f);Publish(FString::Printf(TEXT("GameBricks%d"),G),Channels[0],Channels[1],Channels[2],Channels[3]);}
}
}
