const zlib = require('node:zlib');
const fonts = Object.freeze({ sans:'Arial', system:'Segoe UI', mono:'Consolas', serif:'Georgia', rounded:'Trebuchet MS', emoji:'Segoe UI Emoji' });
const positions=['top-left','top-center','top-right','center-left','center','center-right','bottom-left','bottom-center','bottom-right'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function color(v,fallback){if(v===undefined)return fallback;if(typeof v!=='string'||!/^#[0-9a-f]{6}$/i.test(v))throw Error('Choose a valid six-digit color.');return v;}
function choice(v,allowed,fallback){if(v===undefined)return fallback;if(!allowed.includes(v))throw Error('Choose a supported appearance option.');return v;}
function number(v,min,max,fallback){if(v===undefined)return fallback;if(!Number.isFinite(v)||v<min||v>max)throw Error(`Choose a number between ${min} and ${max}.`);return v;}
function icon(value=''){
 if(value==='')return '';if(typeof value!=='string'||value.length>180000||!/^data:image\/png;base64,[A-Za-z0-9+/]+={0,2}$/.test(value))throw Error('Choose a PNG icon imported through the image picker.');
 const b=Buffer.from(value.split(',')[1],'base64');if(b.length<45||b.subarray(0,8).toString('hex')!=='89504e470d0a1a0a'||b.toString('ascii',12,16)!=='IHDR')throw Error('The icon is not a valid PNG.');
 const w=b.readUInt32BE(16),h=b.readUInt32BE(20),channels=b[25]===6?4:b[25]===2?3:0;if(!w||!h||w>256||h>256||b[24]!==8||!channels||b[26]||b[27]||b[28])throw Error('Import an icon up to 256 pixels using the image picker.');
 let at=8,end=false,parts=[];while(at+12<=b.length){const n=b.readUInt32BE(at),type=b.toString('ascii',at+4,at+8);if(n>b.length-at-12)throw Error('The icon PNG is incomplete.');if(type==='acTL'||type==='fcTL')throw Error('Use a still image for the icon.');if(type==='IDAT')parts.push(b.subarray(at+8,at+8+n));at+=12+n;if(type==='IEND'){end=true;break;}}
 if(!end||at!==b.length||!parts.length)throw Error('The icon PNG is incomplete.');try{const size=h*(1+w*channels),pixels=zlib.inflateSync(Buffer.concat(parts),{maxOutputLength:size});if(pixels.length!==size)throw Error();for(let y=0;y<h;y++)if(pixels[y*(1+w*channels)]>4)throw Error();}catch{throw Error('The icon could not be decoded. Import it again.');}return value;
}
function textStyle(v={}){return{font:choice(v.font,Object.keys(fonts),'sans'),fontSize:number(v.fontSize,8,72,15),color:color(v.color,'#edf2fa'),align:choice(v.align,['left','center','right'],'left'),vertical:choice(v.vertical,['top','center','bottom'],'top'),bold:v.bold===true,paddingX:number(v.paddingX,0,60,8),paddingY:number(v.paddingY,0,60,10)};}
function visual(v={}){if(typeof v.text!=='undefined'&&(typeof v.text!=='string'||v.text.length>200))throw Error('Custom tile text must be 200 characters or fewer.');return{kind:choice(v.kind,['default','text','emoji','icon'],'default'),text:v.text||'',icon:icon(v.icon),...textStyle({...v,fontSize:v.fontSize??24,align:v.align??'center',vertical:v.vertical??'center',paddingX:v.paddingX??4,paddingY:v.paddingY??4})};}
function defaults(){return{stripBackground:'#111820',slotBackground:'#243040',selectedBackground:'#48607a',widgetBackground:'#111820',border:'#48607a',tileBorder:'#374457',motion:'off',accent:'#48607a',period:12,hint:{mode:'default',text:'',icon:'',font:'sans',fontSize:12,color:'#edf2fa'}};}
function appearance(v={}){const d=defaults(),h=v.hint||{};if(h.text!==undefined&&(typeof h.text!=='string'||h.text.length>80))throw Error('Hint text must be 80 characters or fewer.');return{...Object.fromEntries(['stripBackground','slotBackground','selectedBackground','widgetBackground','border','tileBorder','accent'].map(k=>[k,color(v[k],d[k])])),motion:choice(v.motion,['off','breathe','cycle'],'off'),period:number(v.period,4,60,12),hint:{mode:choice(h.mode,['default','hidden','text','emoji','icon'],'default'),text:h.text||'',icon:icon(h.icon),font:choice(h.font,Object.keys(fonts),'sans'),fontSize:number(h.fontSize,8,32,12),color:color(h.color,'#edf2fa')}};}
function tileAppearance(v={}){return{background:v.background?color(v.background):'',motion:choice(v.motion,['inherit','off','breathe','cycle'],'inherit'),accent:color(v.accent,'#48607a')};}
function mix(a,b,t){return '#'+[1,3,5].map(i=>Math.round(parseInt(a.slice(i,i+2),16)*(1-t)+parseInt(b.slice(i,i+2),16)*t).toString(16).padStart(2,'0')).join('');}
function animated(base,a,time){if(a.motion==='off'||!a.motion)return base;const phase=(Math.floor(time/500)/2)%(a.period||12)/(a.period||12);if(a.motion==='breathe')return mix(base,a.accent,(1-Math.cos(phase*Math.PI*2))/2);const palette=['#c75264','#ba7941','#7b9142','#378f85','#466eb0','#8856aa'],n=phase*palette.length;return mix(palette[Math.floor(n)%palette.length],palette[(Math.floor(n)+1)%palette.length],n%1);}
const graphemes=s=>[...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(s)].map(x=>x.segment);
function textSVG(text,w,h,style){const s=textStyle(style),available=Math.max(1,w-2*s.paddingX),capacity=Math.max(1,Math.floor(available/(s.fontSize*.63))),lines=[];for(const paragraph of String(text).split('\n')){const chars=graphemes(paragraph);if(!chars.length)lines.push('');for(let i=0;i<chars.length;i+=capacity)lines.push(chars.slice(i,i+capacity).join(''));}
 const leading=s.fontSize*1.2,max=Math.max(1,Math.floor((h-2*s.paddingY)/leading)),visible=lines.slice(0,max);if(lines.length>max&&visible.length)visible[visible.length-1]=graphemes(visible.at(-1)).slice(0,Math.max(0,capacity-1)).join('')+'…';
 const x=s.align==='center'?w/2:s.align==='right'?w-s.paddingX:s.paddingX,top=s.vertical==='center'?(h-visible.length*leading)/2:s.vertical==='bottom'?h-s.paddingY-visible.length*leading:s.paddingY;
 return visible.map((line,i)=>`<text x="${x}" y="${top+s.fontSize+i*leading}" text-anchor="${{left:'start',center:'middle',right:'end'}[s.align]}" font-family="${fonts[s.font]}" font-size="${s.fontSize}" font-weight="${s.bold?700:400}" fill="${s.color}">${esc(line)}</text>`).join('');
}
function visualSVG(v,w=80,h=78){if(v.kind==='icon')return v.icon?`<image x="${(w-Math.min(w,h)+8)/2}" y="4" width="${Math.min(w,h)-8}" height="${Math.min(w,h)-8}" href="${v.icon}"/>`:'';return textSVG(v.text,w,h,{...v,font:v.kind==='emoji'?'emoji':v.font});}
function capsSVG(i,on){if(!i.enabled)return '';if(i.style!=='dot')return `<rect x="${i.x}" y="${i.y}" width="${i.width}" height="${i.height}" rx="8" fill="${on?i.on:i.off}" fill-opacity=".48" stroke="${on?i.on:i.off}" stroke-width="4"/>`;if(!on&&!i.dotOff)return '';const r=i.dotSize/2,gap=r+4,pos=i.dotPosition||'top-right';const x=pos.includes('left')?i.x+gap:pos.includes('right')?i.x+i.width-gap:i.x+i.width/2,y=pos.startsWith('top')?i.y+gap:pos.startsWith('bottom')?i.y+i.height-gap:i.y+i.height/2;return `<circle cx="${x}" cy="${y}" r="${r}" fill="${on?i.on:i.off}"/>`;}
function regionalUnit(locale=Intl.DateTimeFormat().resolvedOptions().locale){let region;try{region=new Intl.Locale(locale).maximize().region;}catch{}return ['US','BS','BZ','KY','PW','FM','MH','LR'].includes(region)?'fahrenheit':'celsius';}
const resolvedUnit=u=>u==='auto'?regionalUnit():u;
module.exports={fonts,positions,esc,color,number,choice,icon,textStyle,visual,defaults,appearance,tileAppearance,animated,textSVG,visualSVG,capsSVG,regionalUnit,resolvedUnit};
