let feedSignature='',skinSignature='',queueSignature='',communityIdentity='',savedNameColor='#9bb9ff',nameColorDirty=false,communityFeedBusy=false;
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function renderUpdateStatus(update){
 if(!update)return;
 const status=el('update-status'),action=el('update-action');
 const attention=['available','ready'].includes(update.status),progress=update.status==='downloading';
 status.classList.toggle('update-attention',attention);status.classList.toggle('update-progress',progress);status.classList.toggle('update-error',update.status==='error');
 action.classList.toggle('update-attention',attention);action.setAttribute('aria-describedby','update-status');
 action.textContent=update.status==='available'?'Update available':update.status==='ready'?'Restart & update':progress?'Downloading…':'Check for updates';
 action.disabled=['unconfigured','manual','checking','downloading'].includes(update.status);
 const signature=JSON.stringify([update.status,update.message]);
 if(status.dataset.updateSignature===signature)return;
 status.dataset.updateSignature=signature;
 const label=update.status==='available'?'Update available':update.status==='ready'?'Update ready':progress?'Downloading update':'';
 if(!label){status.textContent=update.message;return;}
 let detail=update.message||'';
 if(update.status==='available')detail=detail.replace(/^Update (\S+) available$/,'Version $1');
 if(update.status==='ready')detail=detail.replace(/^Update ready · /,'');
 if(progress)detail=detail.replace(/^Downloading update · /,'');
 status.replaceChildren(node('strong',label,'update-label'),node('span',detail,'update-detail'));
}
function visibleColor(color){if(!/^#[a-f0-9]{6}$/i.test(color||''))color='#9bb9ff';let rgb=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16));const lum=a=>a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0);while((lum(rgb)+.05)/(.008+.05)<4.5&&rgb.some(v=>v<255))rgb=rgb.map(v=>Math.min(255,v+8));return '#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join('');}
function feed(container,items,empty,signature){const key=JSON.stringify(items);if(key===signature)return signature;container.replaceChildren();if(!Array.isArray(items)||!items.length){container.append(node('p',empty,'empty-feed'));return key;}for(const item of items){const article=node('article',undefined,'community-message');const avatar=node('span',Array.from(item.username)[0]?.toUpperCase()||'C','community-avatar');avatar.setAttribute('aria-hidden','true');const body=node('div'),header=node('div',undefined,'message-meta'),name=node('strong',item.username);name.style.color=visibleColor(item.color||'#9bb9ff');header.append(name);const time=node('time',new Date(item.created*1000).toLocaleString());time.dateTime=new Date(item.created*1000).toISOString();header.append(time,node('span',item.status,'status-label'));body.append(header,node('h3',item.title),node('p',item.body));if(item.kind==='skin'&&item.status==='approved'){const studioProject=String(item.body||'').includes('Editable Skin Studio project (.cpskin).')||/\.cpskin(?:[?#]|$)/i.test(item.skin_url||'');const b=node('button',studioProject?'Download Studio project':'Download skin','button');b.addEventListener('click',()=>task(b,()=>window.companion.communitySkin(item.id)));body.append(b,node('p',studioProject?'Open the .cpskin file in Skin Studio. This is an editable project, not a keyboard .pak.':'Download from the creator’s link, then use XPANEL to install it.','note'));}article.append(avatar,body);container.append(article);}return key;}
function renderCommunity(state){renderUpdateStatus(state.updates);if(!state.community)return;const c=state.community;el('discord-signin').textContent=c.signingIn?'Cancel sign-in':'Sign in with Discord';el('community-status').textContent=c.error||(c.signingIn?'Waiting for Discord approval in your browser. You can keep using the app.':c.user?'Signed in as '+c.user.name:c.configured?'Sign in with Discord to post.':state.localPreview?'Community sign-in and posting are disabled in this local test build. Your live community account is unchanged.':'Community connection is not configured for this build. Contact the maintainer; your keyboard features still work.');for(const id of ['discord-signin','community-refresh'])if(!el(id).hasAttribute('aria-busy'))el(id).disabled=!c.configured;el('discord-signout').hidden=!c.user;el('discord-signout').disabled=!c.user;el('request-submit').disabled=!c.user||deskBusy;const identity=c.user?.id||'';if(identity!==communityIdentity){communityIdentity=identity;nameColorDirty=false;savedNameColor='#9bb9ff';}if(/^#[a-f0-9]{6}$/i.test(c.user?.color||''))savedNameColor=c.user.color;if(!nameColorDirty)el('name-color').value=savedNameColor;el('name-color').disabled=!c.user;el('save-name-color').disabled=!c.user||deskBusy||!nameColorDirty;el('discord-signin').hidden=!!c.user&&!c.signingIn;el('community-status').classList.toggle('error',!!c.error);el('community-status').classList.toggle('connected',!!c.user&&!c.error);if(c.user&&!c.error)el('community-status').textContent='Connected as '+c.user.name+' · Your session is remembered on this PC.';feedSignature=feed(el('feature-feed'),c.features,'No requests yet. Be the first to suggest a feature.',feedSignature);skinSignature=feed(el('skin-feed'),c.skins,'Approved community skins will appear here after owner review.',skinSignature);
 el('moderation-panel').hidden=!c.user?.isAdmin;if(c.user?.isAdmin){const signature=JSON.stringify(c.queue);if(signature!==queueSignature){queueSignature=signature;el('moderation-queue').replaceChildren();for(const item of c.queue){const row=node('article',undefined,'review-row');row.append(node('h3',item.title),node('p',item.username+' · '+item.kind+' · '+item.status),node('p',item.body));if(item.skin_url)row.append(node('p',item.skin_url,'submitted-link'));const select=node('select');select.setAttribute('aria-label','Review status for '+item.title);for(const status of item.kind==='skin'?['approved','declined','hidden']:['open','accepted','declined','hidden'])select.append(option(status,status));select.value=[...select.options].some(o=>o.value===item.status)?item.status:select.options[0].value;const save=node('button','Save review','button');save.addEventListener('click',()=>task(save,async()=>renderCommunity(await window.companion.communityReview(item.id,select.value))));row.append(select,save);el('moderation-queue').append(row);}}}
 el('live-device').classList.toggle('device-online',!!(state.device.keyboard&&state.device.display));el('live-device').classList.toggle('device-offline',!(state.device.keyboard&&state.device.display));el('live-device').textContent=state.localPreview?'Local test build':state.connectionRecovering?'Reconnecting keyboard…':state.device.keyboard&&state.device.display?(state.strip?(state.keyboardReady?'Keyboard ready':'Keyboard connected · Initializing display'):'Keyboard connected · Setup required'):state.device.keyboard?'Display disconnected':'Keyboard disconnected';
}
bind('discord-signin',async()=>{if(deskCurrent?.community?.signingIn){renderCommunity(await window.companion.communityCancelLogin());return;}announce('Complete Discord approval in your browser, then return here.');renderCommunity(await window.companion.communityLogin());});
bind('discord-signout',async()=>renderCommunity(await window.companion.communityLogout()));
bind('community-refresh',async()=>renderCommunity(await window.companion.communityRefresh()));
el('name-color').addEventListener('input',()=>{nameColorDirty=el('name-color').value.toLowerCase()!==savedNameColor.toLowerCase();el('save-name-color').disabled=!deskCurrent?.community?.user||deskBusy||!nameColorDirty;});
bind('save-name-color',async()=>{const color=el('name-color').value,state=await window.companion.communityColor(color);savedNameColor=color;nameColorDirty=false;renderCommunity(state);announce(state.community?.error?'Your name color was saved. '+state.community.error:'Display name color saved.',!!state.community?.error);});
function requestProblem(id,message){const field=el(id);field.setAttribute('aria-invalid','true');el('request-validation').textContent=message;field.focus();throw Error(message);}
const requestValidation=document.createElement('p');requestValidation.id='request-validation';requestValidation.className='note error';requestValidation.setAttribute('role','status');el('request-submit').before(requestValidation);
for(const id of ['request-title','request-body','skin-url','skin-rights']){el(id).setAttribute('aria-describedby','request-validation');el(id).addEventListener('input',()=>{el(id).removeAttribute('aria-invalid');requestValidation.textContent='';});}
bind('request-submit',async()=>{
 const kind=el('request-kind').value,title=el('request-title').value.trim(),body=el('request-body').value.trim();
 if(title.length<3||title.length>100)return requestProblem('request-title','Use 3–100 characters for the title.');
 if(body.length<10||body.length>2000)return requestProblem('request-body','Use 10–2,000 characters to explain your idea.');
 if(kind==='skin'){let url;try{url=new URL(el('skin-url').value.trim());}catch{}if(!url||url.protocol!=='https:'||url.username||url.password)return requestProblem('skin-url','Add an HTTPS download link with no account details.');if(!el('skin-rights').checked)return requestProblem('skin-rights','Confirm that you created the skin or have permission to share it.');}
 const state=await window.companion.communitySubmit({kind,title,body,skinUrl:el('skin-url').value.trim(),ownsRights:el('skin-rights').checked});
 el('request-title').value='';el('request-body').value='';el('skin-url').value='';el('skin-rights').checked=false;requestValidation.textContent='';renderCommunity(state);announce(kind==='skin'?'Skin submitted for review. It appears in Browse community after approval.':'Feature request submitted. Thank you for sharing your idea.');
});
el('request-kind').addEventListener('change',()=>el('skin-submission-fields').hidden=el('request-kind').value!=='skin');
bind('update-action',async()=>{const status=deskCurrent.updates?.status;if(status==='ready')return window.companion.updateInstall();renderCommunity(await (status==='available'?window.companion.updateDownload():window.companion.updateCheck()));});
window.companion.subscribe(renderCommunity);window.companion.getState().then(renderCommunity).catch(()=>{});
setInterval(()=>{if(!document.hidden&&['#community','#skins'].includes(location.hash)&&deskCurrent?.community?.configured&&!deskBusy&&!communityFeedBusy){communityFeedBusy=true;window.companion.communityRefresh().then(renderCommunity).catch(e=>{el('community-status').textContent=e.message;el('community-status').classList.add('error');}).finally(()=>communityFeedBusy=false);}},30000);
