const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{randomBytes,createHash}=require('node:crypto');
const config=require('./distribution.json');
class Community{
 constructor(directory,shell,safeStorage){this.shell=shell;this.safeStorage=safeStorage;this.file=path.join(directory,'community-session.bin');this.token='';this.server=null;this.cancelLogin=null;this.state={configured:false,user:null,features:[],skins:[],queue:[],error:''};try{const u=new URL(config.communityOrigin);if(u.protocol==='https:'&&u.origin===config.communityOrigin&&!u.username&&!u.password){this.origin=u.origin;this.state.configured=true;}}catch{}try{if(safeStorage.isEncryptionAvailable())this.token=safeStorage.decryptString(fs.readFileSync(this.file));}catch{}}
 async request(route,method='GET',data){if(!this.origin)throw Error('Community hosting is not configured in this build yet.');const r=await fetch(this.origin+route,{method,headers:{...(this.token?{Authorization:'Bearer '+this.token}:{}),...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined,redirect:'error',signal:AbortSignal.timeout(12000)});const reader=r.body.getReader();let size=0,chunks=[];try{while(true){const{done,value}=await reader.read();if(done)break;size+=value.length;if(size>1024*1024){await reader.cancel();throw Error('Community response is too large.');}chunks.push(value);}}finally{reader.releaseLock();}let result;try{result=JSON.parse(Buffer.concat(chunks).toString());}catch{throw Error('Community service returned an invalid response.');}if(!r.ok){if(r.status===401)this.clear();throw Error(typeof result.error==='string'?result.error.slice(0,200):'Community request failed.');}return result;}
 clear(){this.token='';this.state.user=null;this.state.queue=[];try{fs.unlinkSync(this.file);}catch{}}
 async refresh(){if(!this.origin)return this.state;try{if(this.token)this.state.user=await this.request('/me');const [features,skins]=await Promise.all([this.request('/feed'),this.request('/feed?kind=skin')]);this.state.features=this.items(features.items);this.state.skins=this.items(skins.items);if(this.state.user?.isAdmin)this.state.queue=this.items((await this.request('/admin/queue')).items);this.state.error='';}catch(e){this.state.error=e.message;}return this.state;}
 items(value){if(!Array.isArray(value)||value.length>100)throw Error('Invalid community feed.');return value.map(i=>{if(!/^[a-f0-9]{64}$/.test(i.id)||typeof i.username!=='string'||typeof i.title!=='string'||typeof i.body!=='string'||!Number.isFinite(i.created))throw Error('Invalid community item.');return{id:i.id,username:i.username.slice(0,80),title:i.title.slice(0,100),body:i.body.slice(0,2000),kind:i.kind,status:String(i.status).slice(0,20),created:i.created,skin_url:typeof i.skin_url==='string'?i.skin_url.slice(0,1000):'',color:/^#[a-f0-9]{6}$/i.test(i.color||'')?i.color:'#9bb9ff'};});}
 async login(){if(!this.origin)throw Error('Community hosting is not configured yet.');if(this.server)throw Error('Discord sign-in is already open in your browser.');const verifier=randomBytes(32).toString('base64url'),state=randomBytes(32).toString('hex'),challenge=createHash('sha256').update(verifier).digest('base64url');
  return new Promise((resolve,reject)=>{let finished=false,timer;const finish=(error)=>{if(finished)return;finished=true;clearTimeout(timer);this.server?.close();this.server?.closeAllConnections();this.server=null;this.cancelLogin=null;error?reject(error):resolve(this.state);};this.cancelLogin=()=>finish(Error('Discord sign-in cancelled.'));
   const server=http.createServer(async(req,res)=>{const port=server.address()?.port;let u;try{u=new URL(req.url,`http://127.0.0.1:${port}`);}catch{res.writeHead(400).end();return;}if(req.method!=='GET'||req.headers.host!==`127.0.0.1:${port}`||u.pathname!=='/callback'||u.searchParams.get('state')!==state||!/^[a-f0-9]{64}$/.test(u.searchParams.get('code')||'')){res.writeHead(400).end('Invalid sign-in response.');return;}if(finished){res.writeHead(410).end();return;}
    try{const result=await this.request('/auth/exchange','POST',{code:u.searchParams.get('code'),verifier});if(!/^[a-f0-9]{64}$/.test(result.token||''))throw Error('Invalid sign-in session.');this.token=result.token;if(this.safeStorage.isEncryptionAvailable())fs.writeFileSync(this.file,this.safeStorage.encryptString(this.token));await this.refresh();res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer'}).end('Discord connected. You can return to Centerpiece Companion.');setTimeout(()=>finish(),100);}catch(e){res.writeHead(400,{'Content-Type':'text/plain'}).end('Sign-in failed. Return to the app and try again.');setTimeout(()=>finish(e),100);}});
   this.server=server;server.on('error',()=>finish(Error('Could not open the local sign-in callback.')));server.listen(0,'127.0.0.1',()=>{const u=new URL(this.origin+'/auth/discord');u.search=new URLSearchParams({challenge,state,port:String(server.address().port)}).toString();this.shell.openExternal(u.href).catch(finish);});timer=setTimeout(()=>finish(Error('Discord sign-in timed out. Try again.')),300000);
  });
 }
 async logout(){if(this.token)await this.request('/logout','POST',{}).catch(()=>{});this.clear();return this.state;}
 async submit(input){if(!this.state.user)throw Error('Sign in with Discord first.');if(!input||!['feature','skin'].includes(input.kind)||typeof input.title!=='string'||input.title.trim().length<3||input.title.length>100||typeof input.body!=='string'||input.body.trim().length<10||input.body.length>2000)throw Error('Use 3–100 characters for the title and 10–2,000 characters for the description.');const result=await this.request('/submit','POST',{kind:input.kind,title:input.title,body:input.body,skinUrl:typeof input.skinUrl==='string'?input.skinUrl:'',ownsRights:input.ownsRights===true});await this.refresh();return{...this.state,submitted:result};}
 async review(id,status){if(!this.state.user?.isAdmin)throw Error('Owner access required.');await this.request('/admin/review','POST',{id,status});return this.refresh();}
 async color(color){if(!/^#[a-f0-9]{6}$/i.test(color))throw Error('Choose a display color.');await this.request('/profile','POST',{color});return this.refresh();}
 async openSkin(id){const item=this.state.skins.find(i=>i.id===id&&i.status==='approved');if(!item)throw Error('Choose an approved skin.');let u;try{u=new URL(item.skin_url);}catch{throw Error('Invalid skin link.');}if(u.protocol!=='https:'||u.username||u.password)throw Error('Invalid skin link.');await this.shell.openExternal(u.href);}
 close(){this.cancelLogin?.();}
}
module.exports={Community};
