let feedSignature='',skinSignature='',queueSignature='';
function node(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function visibleColor(color){let rgb=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16));const lum=a=>a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0);while((lum(rgb)+.05)/(.008+.05)<4.5&&rgb.some(v=>v<255))rgb=rgb.map(v=>Math.min(255,v+8));return '#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join('');}
function feed(container,items,empty,signature){const key=JSON.stringify(items);if(key===signature)return signature;container.replaceChildren();if(!items.length){container.append(node('p',empty,'empty-feed'));return key;}for(const item of items){const article=node('article',undefined,'community-message');const avatar=node('span',Array.from(item.username)[0]?.toUpperCase()||'C','community-avatar');avatar.setAttribute('aria-hidden','true');const body=node('div'),header=node('div',undefined,'message-meta'),name=node('strong',item.username);name.style.color=visibleColor(item.color||'#9bb9ff');header.append(name);const time=node('time',new Date(item.created*1000).toLocaleString());time.dateTime=new Date(item.created*1000).toISOString();header.append(time,node('span',item.status,'status-label'));body.append(header,node('h3',item.title),node('p',item.body));if(item.kind==='skin'&&item.status==='approved'){const b=node('button','Download skin','button');b.addEventListener('click',()=>task(b,()=>window.companion.communitySkin(item.id)));body.append(b,node('p','Download from the creator’s link, then use XPANEL to install it.','note'));}article.append(avatar,body);container.append(article);}return key;}
function renderCommunity(state){if(!state.community)return;const c=state.community;el('discord-signin').textContent=c.signingIn?'Cancel sign-in':'Sign in with Discord';el('community-status').textContent=c.error||(c.signingIn?'Waiting for Discord approval in your browser. You can keep using the app.':c.user?'Signed in as '+c.user.name:c.configured?'Sign in with Discord to post.':'Community hosting is awaiting owner setup. Local keyboard features are ready to use.');for(const id of ['discord-signin','community-refresh'])if(!el(id).hasAttribute('aria-busy'))el(id).disabled=!c.configured;el('discord-signout').hidden=!c.user;el('discord-signout').disabled=!c.user;for(const id of ['read-telemetry','reconnect-keyboard'])if(!el(id).hasAttribute('aria-busy'))el(id).disabled=false;el('request-submit').disabled=!c.user||deskBusy;el('save-name-color').disabled=!c.user||deskBusy;feedSignature=feed(el('feature-feed'),c.features,'No requests yet. Be the first to suggest a feature.',feedSignature);skinSignature=feed(el('skin-feed'),c.skins,'Approved community skins will appear here after owner review.',skinSignature);
 el('moderation-panel').hidden=!c.user?.isAdmin;if(c.user?.isAdmin){const signature=JSON.stringify(c.queue);if(signature!==queueSignature){queueSignature=signature;el('moderation-queue').replaceChildren();for(const item of c.queue){const row=node('article',undefined,'review-row');row.append(node('h3',item.title),node('p',item.username+' · '+item.kind+' · '+item.status),node('p',item.body));if(item.skin_url)row.append(node('p',item.skin_url,'submitted-link'));const select=node('select');select.setAttribute('aria-label','Review status for '+item.title);for(const status of item.kind==='skin'?['approved','declined','hidden']:['open','accepted','declined','hidden'])select.append(option(status,status));const save=node('button','Save review','button');save.addEventListener('click',()=>task(save,async()=>renderCommunity(await window.companion.communityReview(item.id,select.value))));row.append(select,save);el('moderation-queue').append(row);}}}
 const u=state.updates;if(u){el('update-status').textContent=u.message;el('update-action').textContent=u.status==='available'?'Download update':u.status==='ready'?'Restart & update':u.status==='downloading'?'Downloading…':'Check for updates';el('update-action').disabled=['unconfigured','manual','checking','downloading'].includes(u.status);}
 el('live-device').classList.toggle('device-online',!!(state.device.keyboard&&state.device.display));el('live-device').classList.toggle('device-offline',!(state.device.keyboard&&state.device.display));el('live-device').textContent=state.device.keyboard&&state.device.display?'Keyboard connected':state.device.keyboard?'Display disconnected':'Keyboard disconnected';el('live-profile').textContent=state.telemetry?`${state.telemetry.profileName||'Profile '+state.telemetry.profile} · ${new Date(state.telemetry.updatedAt).toLocaleTimeString()}`:'Read device settings to load profile and trigger values.';const selected=state.telemetry?.keys?.[selectedKey];el('live-key-settings').textContent=selected?`${keymap?selectedLayer().keys[selectedKey].name:'Selected key'} · Actuation ${selected.actuation.toFixed(1)} mm · Rapid Trigger ${selected.rapidTrigger?'on':'off'} · Sensitivity ${selected.sensitivity.toFixed(1)} mm`:'Select a key in Keyboard editor to inspect its settings.';el('live-temperature').textContent='Keyboard temperature: not exposed by the supported firmware interface.';
}
bind('discord-signin',async()=>{if(deskCurrent?.community?.signingIn){renderCommunity(await window.companion.communityCancelLogin());return;}announce('Complete Discord approval in your browser, then return here.');renderCommunity(await window.companion.communityLogin());});
bind('discord-signout',async()=>renderCommunity(await window.companion.communityLogout()));
bind('community-refresh',async()=>renderCommunity(await window.companion.communityRefresh()));
bind('save-name-color',async()=>renderCommunity(await window.companion.communityColor(el('name-color').value)));
bind('request-submit',async()=>{const state=await window.companion.communitySubmit({kind:el('request-kind').value,title:el('request-title').value,body:el('request-body').value,skinUrl:el('skin-url').value,ownsRights:el('skin-rights').checked});el('request-title').value='';el('request-body').value='';el('skin-url').value='';el('skin-rights').checked=false;renderCommunity(state);announce('Submitted. Skin links appear publicly only after owner approval.');});
el('request-kind').addEventListener('change',()=>el('skin-submission-fields').hidden=el('request-kind').value!=='skin');
bind('update-action',async()=>{const status=deskCurrent.updates?.status;if(status==='ready')return window.companion.updateInstall();renderCommunity(await (status==='available'?window.companion.updateDownload():window.companion.updateCheck()));});
bind('read-telemetry',async()=>renderCommunity(await window.companion.readTelemetry()));
window.companion.subscribe(renderCommunity);window.companion.getState().then(renderCommunity).catch(()=>{});
setInterval(()=>{if(!document.hidden&&['#community','#skins'].includes(location.hash)&&deskCurrent?.community?.configured&&!deskBusy)window.companion.communityRefresh().then(renderCommunity).catch(()=>{});},30000);

bind('reconnect-keyboard',async()=>renderCommunity(await window.companion.reconnectKeyboard()));

setInterval(()=>{if(!document.hidden&&location.hash==='#keyboard'&&!deskBusy&&deskCurrent?.device?.keyboard)window.companion.readTelemetry().then(renderCommunity).catch(()=>{});},30000);
