/* Shared controls for the desktop app and isolated local test surface. */
(()=>{
 window.widgetPreviewRendered=!!window.companion.previewLayout;
 const fonts={sans:'Arial',system:'Segoe UI',mono:'Consolas',serif:'Georgia',rounded:'Trebuchet MS',emoji:'Segoe UI Emoji'};
 const select=(id,label,items)=>`<label for="${id}">${label}<select id="${id}">${Object.entries(items).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>`;
 const input=(id,label,type='text',extra='')=>`<label for="${id}">${label}<input id="${id}" type="${type}" ${extra}></label>`;
 const styleFields=p=>`<div class="custom-grid">${select(p+'font','Font',fonts)}${input(p+'fontSize','Font size','number','min="8" max="72"')}${input(p+'color','Text color','color')}${select(p+'align','Horizontal position',{left:'Left',center:'Center',right:'Right'})}${select(p+'vertical','Vertical position',{top:'Top',center:'Center',bottom:'Bottom'})}${input(p+'paddingX','Side inset','number','min="0" max="60"')}${input(p+'paddingY','Top / bottom inset','number','min="0" max="60"')}</div><label class="check-row"><input id="${p}bold" type="checkbox"> Bold text</label>`;
 const iconField=(p,label)=>`<label for="${p}file">${label}<input id="${p}file" type="file" accept="image/png,image/jpeg,image/webp" aria-describedby="${p}file-help"></label><small class="note image-size-help" id="${p}file-help">${p==='hint-'?'Hint area: 84 × 34 px · square icon: 26 × 26 px.':'Tile: 80 × 78 px · icon: 70 × 70 px.'} Use a 128 × 128 px image or larger; we fit it automatically. PNG, JPEG or WebP · up to 8 MB.</small><span class="note" id="${p}image-status" role="status">No custom image selected.</span>`;
 const emojis=[['🎮','Game controller'],['✨','Sparkles'],['🚀','Rocket'],['🌙','Moon'],['☀️','Sun'],['🌈','Rainbow'],['💜','Purple heart'],['💚','Green heart'],['🔥','Fire'],['❄️','Snowflake'],['🌊','Wave'],['🌸','Cherry blossom'],['🐱','Cat'],['🐶','Dog'],['🦊','Fox'],['🐟','Fish'],['🎧','Headphones'],['🎵','Music'],['⚡','Lightning'],['💎','Gem'],['⭐','Star'],['🍀','Clover'],['☕','Coffee'],['👾','Space invader']];
 const emojiPicker=p=>`<div class="emoji-chooser" id="${p}emoji-picker"><p class="note">Choose an emoji or paste one into the field from any website.</p><div class="emoji-grid" role="group" aria-label="${p==='hint-'?'Bottom hint':p==='widget-'?'Custom text widget':'Decoration'} emoji choices">${emojis.map(([emoji,name])=>`<button type="button" disabled class="button emoji-choice" data-emoji-target="${p}" data-emoji="${emoji}" aria-label="Insert ${name}" title="${name}">${emoji}</button>`).join('')}</div></div>`;
 const tile=document.createElement('section');tile.className='decoration-editor';tile.hidden=true;tile.innerHTML=`<div class="custom-grid">${select('tile-kind','Decoration content',{text:'Text',emoji:'Emoji',icon:'Image'})}${input('tile-text','Text or emoji','text','maxlength="200" placeholder="Hello, 🎮, ✨…"')}<div id="tile-image-field">${iconField('tile-','Decoration image')}</div></div>${emojiPicker('tile-')}<details><summary>Text appearance</summary>${styleFields('tile-')}</details><div class="custom-grid"><label class="check-row"><input id="tile-custom-bg" type="checkbox"> Custom tile background</label>${input('tile-background','Background color','color')}${select('tile-motion','Color animation',{inherit:'Use strip setting',off:'Still',breathe:'Breathe between colors',cycle:'Color cycle'})}${input('tile-accent','Animation second color','color')}</div>`;
 el('plugin-detail').insertBefore(tile,el('action-help'));document.querySelector('.assignment').after(el('plugin-detail'));
 const look=document.createElement('details');look.className='custom-section strip-appearance';look.innerHTML=`<summary><span class="appearance-symbol" aria-hidden="true">◒</span> Strip colors & bottom hint <small>Colors · animation · personal message</small></summary><p class="note">Defaults match the original companion. Color motion is optional and pauses during plugin navigation for responsive controls.</p><div class="custom-grid">${input('look-stripBackground','Strip background','color')}${input('look-slotBackground','Default tile background','color')}${input('look-selectedBackground','Selected tile','color')}${input('look-widgetBackground','Widget background','color')}${input('look-border','Strip / widget border','color')}${input('look-tileBorder','Tile border','color')}${select('look-motion','Background animation',{off:'Off (default)',breathe:'Breathe between colors',cycle:'Color cycle'})}${input('look-accent','Animation second color','color')}${input('look-period','Cycle length (seconds)','number','min="4" max="60"')}</div><h3>Bottom hint</h3><div class="custom-grid">${select('hint-mode','Show below the tiles',{default:'PLUGINS · L1 + P (default)',hidden:'Hide hint',text:'Custom text',emoji:'Emoji',icon:'Custom icon'})}${input('hint-text','Replacement text / emoji','text','maxlength="80"')}<div id="hint-image-field">${iconField('hint-','Replacement icon')}</div>${select('hint-font','Font',fonts)}${input('hint-fontSize','Font size','number','min="8" max="32"')}${input('hint-color','Text color','color')}</div>${emojiPicker('hint-')}<div class="form-actions"><button id="save-appearance" class="button primary" disabled>Apply strip appearance</button><button id="reset-appearance" class="button" disabled>Restore default colors & hint</button></div>`;el('plugin-detail').after(look);
 const dot=document.createElement('div');dot.className='custom-section';dot.innerHTML=`<div class="custom-grid">${select('caps-style','Indicator style',{fill:'Whole key color (default)',dot:'Small dot'})}${select('caps-dotPosition','Dot placement within Caps Lock',{ 'top-left':'Top left','top-center':'Top center','top-right':'Top right','center-left':'Center left',center:'Center','center-right':'Center right','bottom-left':'Bottom left','bottom-center':'Bottom center','bottom-right':'Bottom right'})}${input('caps-dotSize','Dot diameter','number','min="3" max="30"')}</div><label class="check-row"><input id="caps-dotOff" type="checkbox"> Also show the dot when Caps Lock is off</label>`;el('caps-editor').insertBefore(dot,el('save-indicator'));
 const text=document.createElement('details');text.open=true;text.className='custom-section';text.innerHTML=`<summary>Custom text appearance</summary><p class="note">Choose Custom text as the display to use this area on its own. Move the whole widget with Adjust the display area.</p>${styleFields('text-')}`;el('save-widget').before(text);
 const widgetEmojis=document.createElement('details');widgetEmojis.className='widget-emoji-picker';widgetEmojis.innerHTML=`<summary><span aria-hidden="true">☺</span> Add an emoji <small>Or paste any emoji into Custom text</small></summary>${emojiPicker('widget-')}`;el('widget-text-help').after(widgetEmojis);

 el('weather-unit').prepend(option('auto','Automatic · regional units'));
 const weather=document.createElement('div');weather.className='custom-section';weather.innerHTML=select('widget-unit','Weather temperature units',{auto:'Automatic · regional units',celsius:'°C · Celsius',fahrenheit:'°F · Fahrenheit'})+'<p class="note">Automatic uses your Windows regional locale. Choose °C or °F to override it. This does not read the private Windows Weather app settings.</p><button id="save-weather-unit" class="button" disabled>Save temperature units</button>';el('save-widget').after(weather);
 let tileIcon='',hintIcon='',loaded=false,revision=-1,tileRevision=0;
 const set=(id,value)=>{if(el(id))el(id).value=value;};
 function loadStyle(prefix,v={}){for(const[k,f]of Object.entries({font:'sans',fontSize:15,color:'#edf2fa',align:'left',vertical:'top',paddingX:8,paddingY:10}))set(prefix+k,v[k]??f);el(prefix+'bold').checked=v.bold===true;}
 function readStyle(prefix){return Object.fromEntries(['font','fontSize','color','align','vertical','paddingX','paddingY','bold'].map(k=>[k,k==='bold'?el(prefix+k).checked:['fontSize','paddingX','paddingY'].includes(k)?Number(el(prefix+k).value):el(prefix+k).value]));}
 function loadTile(saved){tileRevision++;const v=saved?.visual||{},a=saved?.appearance||{};set('tile-kind',v.kind&&v.kind!=='default'?v.kind:'text');set('tile-text',v.text||'');tileIcon=v.icon||'';el('tile-image-status').textContent=tileIcon?'Custom image saved locally.':'No custom image selected.';loadStyle('tile-',{fontSize:24,align:'center',vertical:'center',paddingX:4,paddingY:4,...v});el('tile-custom-bg').checked=!!a.background;set('tile-background',a.background||draft?.appearance?.slotBackground||'#243040');set('tile-motion',a.motion||'inherit');set('tile-accent',a.accent||'#48607a');syncContentFields();}
 window.readTileCustomization=()=>selectedPlugin!=='decoration'?(()=>{const saved=draft.slots[selectedPosition];return saved?.plugin===selectedPlugin?{...(saved.visual?{visual:saved.visual}:{}),...(saved.appearance?{appearance:saved.appearance}:{})}:{};})():({visual:{kind:el('tile-kind').value,text:el('tile-text').value,icon:tileIcon,...readStyle('tile-')},appearance:{background:el('tile-custom-bg').checked?el('tile-background').value:'',motion:el('tile-motion').value,accent:el('tile-accent').value}});
 window.readTextCustomization=()=>readStyle('text-');
 function syncContentFields(){const kind=el('tile-kind').value,mode=el('hint-mode').value;el('tile-text').closest('label').hidden=kind==='icon';el('tile-image-field').hidden=kind!=='icon';el('tile-emoji-picker').hidden=kind!=='emoji';el('hint-text').closest('label').hidden=!['text','emoji'].includes(mode);el('hint-image-field').hidden=mode!=='icon';el('hint-emoji-picker').hidden=mode!=='emoji';}
 const priorDetail=drawDetail;drawDetail=function(saved){priorDetail(saved);loadTile(saved);const decoration=selectedPlugin==='decoration';tile.hidden=!decoration;el('slot-action').closest('.form-row').hidden=decoration;el('action-help').hidden=decoration;el('run-slot').hidden=decoration;el('save-slot').textContent=decoration?'Save decoration to keyboard':'Add to keyboard';if(decoration)el('chosen-description').textContent='Fill this position with an emoji, image or text. Decorations have no key action.';};
 const oldSlots=drawSlots;drawSlots=function(){oldSlots();draft.slots.forEach((slot,index)=>{const v=slot?.visual,item=el('strip-mini').children[index];if(!item)return;item.style.background=slot?.appearance?.background||draft.appearance?.slotBackground||'';if(v&&v.kind!=='default'){item.replaceChildren();if(v.kind==='icon'&&v.icon){const img=document.createElement('img');img.src=v.icon;img.alt='Custom icon';item.append(img);}else{item.textContent=v.text;item.style.color=v.color;item.style.fontFamily=fonts[v.font]||fonts.sans;item.style.fontSize='16px';}if(slot.plugin==='decoration')el('slot-list').children[index].querySelector('.slot-plugin-name span').textContent='Decoration';}});};
 function load(state){if(!state.desk)return;if(!loaded||(state.profileRevision||0)!==revision){loaded=true;revision=state.profileRevision||0;const c=state.desk.config,a=c.appearance||{};for(const[k,v]of Object.entries({stripBackground:'#111820',slotBackground:'#243040',selectedBackground:'#48607a',widgetBackground:'#111820',border:'#48607a',tileBorder:'#374457',motion:'off',accent:'#48607a',period:12}))set('look-'+k,a[k]??v);const h=a.hint||{};for(const[k,v]of Object.entries({mode:'default',text:'',font:'sans',fontSize:12,color:'#edf2fa'}))set('hint-'+k,h[k]??v);hintIcon=h.icon||'';syncContentFields();el('hint-image-status').textContent=hintIcon?'Custom image saved locally.':'No custom image selected.';set('caps-style',c.indicator.style||'fill');set('caps-dotPosition',c.indicator.dotPosition||'top-right');set('caps-dotSize',c.indicator.dotSize||8);el('caps-dotOff').checked=c.indicator.dotOff===true;loadStyle('text-',c.widget.textStyle);set('widget-unit',c.weather.unit);loadTile(c.slots[selectedPosition]);drawSlots();}
 for(const id of ['save-appearance','reset-appearance','save-weather-unit'])if(!el(id).hasAttribute('aria-busy'))el(id).disabled=false;if(state.desk.config.slots[selectedPosition]?.plugin==='decoration')el('run-slot').disabled=true;document.querySelector('.library-tools .connection').textContent=state.desk.catalog.length+' options';}
 function lookValue(){const a={};for(const k of ['stripBackground','slotBackground','selectedBackground','widgetBackground','border','tileBorder','motion','accent'])a[k]=el('look-'+k).value;a.period=Number(el('look-period').value);a.hint={mode:el('hint-mode').value,text:el('hint-text').value,icon:hintIcon,font:el('hint-font').value,fontSize:Number(el('hint-fontSize').value),color:el('hint-color').value};return a;}
 bind('save-appearance',()=>configChange(c=>c.appearance=lookValue()));bind('reset-appearance',async()=>{await configChange(c=>{delete c.appearance;});loaded=false;load(deskCurrent);});
 bind('save-weather-unit',async()=>{await configChange(c=>c.weather={...c.weather,unit:el('widget-unit').value});set('weather-unit',el('widget-unit').value);});
 el('weather-unit').addEventListener('change',()=>task(el('weather-unit'),async()=>{await configChange(c=>c.weather={...c.weather,unit:el('weather-unit').value});set('widget-unit',el('weather-unit').value);}));
 for(const id of ['tile-kind','hint-mode'])el(id).addEventListener('change',syncContentFields);
 document.querySelectorAll('[data-emoji-target]').forEach(button=>{button.disabled=false;button.addEventListener('click',()=>{const input=el(button.dataset.emojiTarget+'text');if(deskBusy||input.disabled||input.readOnly){announce('Wait for the current change to finish, then add an emoji.');return;}try{const next=window.CompanionEmojiInput.insert(input.value,button.dataset.emoji,input.selectionStart,input.selectionEnd,input.maxLength);input.value=next.value;input.focus();input.setSelectionRange(next.caret,next.caret);input.dispatchEvent(new Event('input',{bubbles:true}));}catch(error){announce(error.message,true);}});});
 const importRevisions={'tile-':0,'hint-':0};
 for(const prefix of ['tile-','hint-'])el(prefix+'file').addEventListener('change',async()=>{const importRevision=++importRevisions[prefix],position=selectedPosition,plugin=selectedPlugin,tileVersion=tileRevision,file=el(prefix+'file').files[0];el(prefix+'file').value='';if(!file)return;try{if(file.size>8*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Choose a PNG, JPEG or WebP image up to 8 MB.');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>16000000){bitmap.close();throw Error('Choose an image below 16 megapixels.');}const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const ctx=canvas.getContext('2d'),scale=Math.min(128/bitmap.width,128/bitmap.height);ctx.drawImage(bitmap,(128-bitmap.width*scale)/2,(128-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);bitmap.close();const data=canvas.toDataURL('image/png');if(importRevision!==importRevisions[prefix]||(prefix==='tile-'&&(position!==selectedPosition||plugin!==selectedPlugin||tileVersion!==tileRevision)))return;if(prefix==='tile-')tileIcon=data;else hintIcon=data;set(prefix+'kind','icon');set(prefix+'mode','icon');syncContentFields();el(prefix+'image-status').textContent='Image ready. Apply to save it on this PC.';}catch(e){announce(e.message,true);}});

 const mediaPanel=document.createElement('section');mediaPanel.className='media-key-editor';mediaPanel.innerHTML=`<h3>Media key shortcuts</h3><p class="note">Select a key on the keyboard above, choose its media action, then save the binding. Your existing XPANEL media keys already work.</p><div id="media-key-actions" class="media-key-actions" role="group" aria-label="Assign media action"></div><div id="media-icon-editor" hidden><label class="check-row"><input id="media-icon-enabled" type="checkbox"> Show a custom media icon on this key</label><div class="custom-grid">${input('media-icon-color','Icon color','color')}${select('media-icon-style','Icon design',{outline:'Outline · default',solid:'Solid',badge:'Rounded badge'})}${input('media-icon-background','Icon backdrop','color')}</div><button id="save-media-icon" class="button" disabled>Apply icon to keyboard</button><p class="note">Custom icons sit above the current skin. Turn this off to reveal the skin’s original symbol. Icons appear only while the matching media binding is active.</p></div><p id="media-key-status" class="note" role="status"></p>`;el('key-target').closest('.form-row').before(mediaPanel);
 const MI=window.MediaKeyIcons;
 const mediaKeyId=()=>`${Number(el('key-layer').value)}:${selectedKey}`;
 const reservedMediaKey=()=>selectedKey===63||(Number(el('key-layer').value)===1&&[26,55].includes(selectedKey));
 const iconUri=(code,style)=>'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(MI.svg(code,style));
 function mediaStyle(){return{code:Number(el('key-target').value),color:el('media-icon-color').value,style:el('media-icon-style').value,background:el('media-icon-background').value};}
 function mediaForm(fromSaved=false){if(!MI)return;const item=MI.find(el('key-target').value),saved=draft?.keyIcons?.[mediaKeyId()];el('media-icon-editor').hidden=!item;document.querySelectorAll('[data-media-code]').forEach(b=>{b.setAttribute('aria-pressed',String(Number(b.dataset.mediaCode)===item?.code));b.disabled=!keymap||reservedMediaKey();});if(fromSaved){el('media-icon-enabled').checked=!!saved;set('media-icon-color',saved?.color||'#edf2fa');set('media-icon-style',saved?.style||'outline');set('media-icon-background',saved?.background||'#243040');}const actual=selectedLayer()?.keys[selectedKey]?.binding,matched=actual?.behaviorId===50397&&MI.find(actual.param1)?.code===item?.code;el('save-media-icon').disabled=!item||!matched||reservedMediaKey();el('media-key-status').textContent=reservedMediaKey()?'This key stays reserved for Companion navigation.':item&&!matched?'Save the new binding before applying its icon.':'Choose a media action, or use New binding for other keys.';}
 if(MI)for(const item of MI.items){const button=document.createElement('button');button.className='button media-key-choice';button.dataset.mediaCode=item.code;button.disabled=true;const icon=document.createElement('img');icon.src=iconUri(item.code);icon.alt='';button.append(icon,document.createTextNode(item.label));button.addEventListener('click',()=>{set('key-target',item.code);for(const id of ['key-ctrl','key-shift','key-alt'])el(id).checked=false;mediaForm();el('media-icon-enabled').checked=true;el('save-key').focus();announce(`${item.label} selected for ${selectedLayer().keys[selectedKey].name}. Click Save binding to keyboard.`);});el('media-key-actions').append(button);}
 const previousKeyboard=drawKeyboard;drawKeyboard=function(){previousKeyboard();if(!keymap||!MI)return;const layer=selectedLayer();el('keyboard-map').querySelectorAll('.key').forEach((button,position)=>{const binding=layer.keys[position].binding,item=binding.behaviorId===50397?MI.find(binding.param1):null;if(!item)return;const style=draft?.keyIcons?.[`${layer.id}:${position}`],image=document.createElement('img');image.className='media-key-symbol';image.src=iconUri(item.code,style?.code===item.code?style:{});image.alt='';button.replaceChildren(image);});mediaForm(true);};
 el('key-target').addEventListener('change',()=>mediaForm());
 for(const id of ['media-icon-enabled','media-icon-color','media-icon-style','media-icon-background'])el(id).addEventListener('input',()=>{const binding=selectedLayer()?.keys[selectedKey]?.binding;if(binding?.behaviorId!==50397||!MI?.find(binding.param1))return;const button=el('keyboard-map').querySelectorAll('.key')[selectedKey],img=button?.querySelector('img');if(img)img.src=iconUri(binding.param1,el('media-icon-enabled').checked?mediaStyle():{});});
 async function storeMediaIcon(id,style,enabled){await configChange(c=>{c.keyIcons={...(c.keyIcons||{})};if(enabled)c.keyIcons[id]=style;else delete c.keyIcons[id];});}
 bind('save-media-icon',async()=>{if(!keymap||reservedMediaKey())return;const actual=selectedLayer().keys[selectedKey].binding,style=mediaStyle();if(actual.behaviorId!==50397||(actual.param1&0xffffff)!==style.code)throw Error('Save this media binding before applying the icon.');await storeMediaIcon(mediaKeyId(),style,el('media-icon-enabled').checked);drawKeyboard();announce('Media icon saved above your current skin.');});
 let pendingIcon=null;
 el('save-key').addEventListener('click',()=>{pendingIcon=keymap&&MI?.find(el('key-target').value)?{id:mediaKeyId(),style:mediaStyle(),enabled:el('media-icon-enabled').checked}:null;},{capture:true});
 window.saveMediaKeyAppearance=async swap=>{if(swap||!pendingIcon)return;const value=pendingIcon;pendingIcon=null;try{await storeMediaIcon(value.id,value.style,value.enabled);drawKeyboard();}catch(e){throw Error('The media binding was saved, but its icon could not be applied: '+e.message);}};

 const board=document.createElement('section');board.className='custom-preview';board.innerHTML=`<div class="preview-controls"><strong>Keyboard layout preview</strong><label><input id="preview-caps" type="checkbox"> Preview Caps Lock on</label><label>Selection<select id="preview-selection"><option value="idle">None</option><option value="previous">Position 1</option><option value="toggle">Position 2</option><option value="next">Position 3</option><option value="fourth">Position 4</option></select></label><label><input id="preview-motion" type="checkbox"> Animate preview</label></div><img id="custom-layout-image" width="1920" height="550" alt="Rendered keyboard with your plugin tiles, Caps Lock indicator and screen widget"><p id="custom-preview-status" class="preview-caption" role="status">Previewing unsaved appearance choices. Use Apply to save.</p>`;el('desk-feedback').after(board);board.hidden=!['','#library','#keyboard','#widgets'].includes(location.hash);el('preview-motion').checked=!matchMedia('(prefers-reduced-motion: reduce)').matches;
 let previewTimer,previewRunning=false,previewAgain=false,previewGeneration=0;
 function previewConfig(){const c=structuredClone(draft);c.appearance=lookValue();if(location.hash==='#widgets'){c.widget={...c.widget,type:el('widget-type').value,clockSeconds:el('clock-seconds').checked,text:el('widget-text').value,textStyle:readStyle('text-')};for(const k of ['x','y','width','height'])c.widget[k]=Number(el('widget-'+k).value);}if(location.hash==='#keyboard'){const binding=selectedLayer()?.keys[selectedKey]?.binding;if(binding?.behaviorId===50397&&MI?.find(binding.param1)&&(binding.param1&0xffffff)===Number(el('key-target').value)){c.keyIcons={...(c.keyIcons||{})};if(el('media-icon-enabled').checked)c.keyIcons[mediaKeyId()]=mediaStyle();else delete c.keyIcons[mediaKeyId()];}Object.assign(c.indicator,{enabled:el('caps-enabled').checked,style:el('caps-style').value,dotPosition:el('caps-dotPosition').value,dotSize:Number(el('caps-dotSize').value),dotOff:el('caps-dotOff').checked,on:el('caps-on').value,off:el('caps-off').value});for(const k of ['x','y','width','height'])c.indicator[k]=Number(el('caps-'+k).value);}if(!location.hash||location.hash==='#library'){const action=el('slot-action').value,value=el('slot-value').value;if(action&&!(action==='hotkey'&&!value))c.slots[selectedPosition]={plugin:selectedPlugin,action,value,...readTileCustomization()};}return c;}
 async function refreshPreview(){if(!draft||!loaded||!window.companion.previewLayout)return;if(previewRunning){previewAgain=true;return;}previewRunning=true;const generation=previewGeneration;try{const image=await window.companion.previewLayout(previewConfig(),{caps:el('preview-caps').checked,selected:el('preview-selection').value,freeze:!el('preview-motion').checked});if(generation===previewGeneration){el('custom-layout-image').src=image;if(location.hash==='#widgets'&&el('widget-type').value==='off'){if(el('widget-preview').dataset.mode!=='off'){el('widget-preview').replaceChildren(document.createTextNode('Widget off'));el('widget-preview').dataset.mode='off';}}else if(location.hash==='#widgets'){el('widget-preview').dataset.mode='live';const detail=await window.companion.previewLayout(previewConfig(),{caps:el('preview-caps').checked,selected:'idle',freeze:!el('preview-motion').checked,widgetOnly:true});if(generation===previewGeneration){let img=el('widget-preview').querySelector('img.rendered-widget');if(!img){img=document.createElement('img');img.className='rendered-widget';el('widget-preview').replaceChildren(img);}img.width=previewConfig().widget.width;img.height=previewConfig().widget.height;img.src=detail;img.alt='Exact rendered '+el('widget-type').selectedOptions[0].textContent+' widget';}}el('custom-preview-status').textContent='Previewing unsaved appearance choices. Use Apply to save.';}}catch(e){if(generation===previewGeneration)el('custom-preview-status').textContent=e.message;}finally{previewRunning=false;if(previewAgain){previewAgain=false;schedulePreview();}}}
 function schedulePreview(){previewGeneration++;clearTimeout(previewTimer);previewTimer=setTimeout(refreshPreview,180);}
 document.addEventListener('input',schedulePreview);document.addEventListener('change',schedulePreview);document.addEventListener('click',schedulePreview);window.addEventListener('hashchange',()=>{board.hidden=!['','#library','#keyboard','#widgets'].includes(location.hash);schedulePreview();});window.companion.subscribe(schedulePreview);setInterval(()=>{if(!board.hidden&&el('preview-motion').checked&&!document.hidden)refreshPreview();},500);setTimeout(refreshPreview,300);
 window.companion.subscribe(load);window.companion.getState().then(load).catch(e=>announce(e.message,true));
})();
