let deskProfileRevision=0;
let deskCurrent, draft, selectedPosition=0, selectedPlugin='spotify', keymap, selectedKey=32, deskBusy=false;
const el=id=>document.getElementById(id);
function option(value,text){const o=document.createElement('option');o.value=value;o.textContent=text;return o;}
function announce(message,error=false){el('desk-feedback').textContent=message;el('desk-feedback').classList.toggle('error',error);}
async function task(button,fn){if(deskBusy)return;deskBusy=true;button.disabled=true;button.setAttribute('aria-busy','true');announce('Working…');try{await fn();}catch(e){announce(e.message.replace(/^Error invoking remote method '[^']+': (?:Error: )?/,''),true);}finally{deskBusy=false;button.removeAttribute('aria-busy');button.disabled=false;}}
function route(){const page=['library','keyboard','media','connections'].includes(location.hash.slice(1))?location.hash.slice(1):'library';document.querySelectorAll('[data-page]').forEach(s=>s.hidden=s.dataset.page!==page);document.querySelectorAll('.sidebar a').forEach(a=>{if(a.hash==='#'+page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const h=document.querySelector(`[data-page="${page}"] h1`);document.title=h.textContent+' · Centerpiece Companion';h.focus();}
window.addEventListener('hashchange',route);route();
function drawSlots(){
 const list=el('slot-list'),mini=el('strip-mini');list.replaceChildren();mini.replaceChildren();
 draft.slots.forEach((s,i)=>{const p=deskCurrent.desk.catalog.find(p=>p.id===s?.plugin);const b=document.createElement('button');b.className='slot button';b.setAttribute('aria-pressed',String(i===selectedPosition));b.append(document.createTextNode(`Position ${i+1}`));const line=document.createElement('strong');line.textContent=p?.name||'Empty';b.append(line);const a=document.createElement('small');a.textContent=p?.actions.find(a=>a.id===s?.action)?.label||'Choose a plugin';b.append(a);b.addEventListener('click',()=>{selectedPosition=i;selectedPlugin=s?.plugin||'spotify';drawSlots();drawDetail(s);drawLibrary();});list.append(b);
 const tile=document.createElement('div');if(p){const image=document.createElement('img');image.src=`icons/${p.icon}.svg`;image.alt=p.name;tile.append(image);}else tile.textContent='+';mini.append(tile);});
}
function drawLibrary(){const grid=el('plugin-grid');grid.replaceChildren();const query=el('plugin-search').value.trim().toLowerCase(),category=el('category').value;const results=deskCurrent.desk.catalog.filter(p=>(category==='all'||p.category===category)&&`${p.name} ${p.category}`.toLowerCase().includes(query));el('no-results').hidden=!!results.length;el('clear-search').disabled=!query;
 for(const p of results){const b=document.createElement('button');b.className='plugin-tile';b.setAttribute('aria-pressed',String(p.id===selectedPlugin));const img=document.createElement('img');img.src=`icons/${p.icon}.svg`;img.alt='';const name=document.createElement('strong');name.textContent=p.name;const type=document.createElement('small');type.textContent=p.id==='obs'?'OBS connection':p.id==='spotify'?'Local music':p.id==='media'?'Windows controls':p.url?'Launcher + shortcut':'Configure action';b.append(img,name,type);b.addEventListener('click',()=>{selectedPlugin=p.id;drawDetail();drawLibrary();el('slot-action').focus();});grid.append(b);}}
function drawDetail(saved){const p=deskCurrent.desk.catalog.find(p=>p.id===selectedPlugin);el('chosen-name').textContent=p.name;el('chosen-position').textContent=`Position ${selectedPosition+1}`;el('chosen-description').textContent='Choose what this logo does when you activate it.';el('slot-action').replaceChildren(...p.actions.map(a=>option(a.id,a.label)));if(saved?.plugin===p.id)el('slot-action').value=saved.action;el('slot-value').value=saved?.plugin===p.id?saved.value||'':'';actionHelp();}
function actionHelp(){const action=el('slot-action').value;const needs=['hotkey','url','app','scene','mute'].includes(action)&&selectedPlugin!=='mic';el('value-label').hidden=!needs;el('pick-app').hidden=action!=='app';el('slot-value').readOnly=action==='app';el('value-label').firstChild.textContent=({hotkey:'Shortcut',url:'Website address',app:'App path',scene:'Exact scene name',mute:'Exact input name'}[action]||'Value');el('slot-value').placeholder=({hotkey:'Ctrl+Shift+F10',url:'https://example.com',scene:'Starting soon',mute:'Mic/Aux'}[action]||'');el('action-help').textContent=action==='hotkey'?'Set this same shortcut in the target app first. Global app shortcuts work in the background; other shortcuts need that app focused.':selectedPlugin==='obs'?'Connect OBS first. This action uses OBS directly.':action==='open'?'Opens the service. This does not control its stream, chat or account.':'The action runs only when you select it.';}
function renderDesk(state){deskCurrent=state;if(!state.desk)return;if((state.profileRevision||0)!==deskProfileRevision){deskProfileRevision=state.profileRevision;draft=null;}if(!draft){draft=structuredClone(state.desk.config);el('category').append(...[...new Set(state.desk.catalog.map(p=>p.category))].map(c=>option(c,c)));drawSlots();drawLibrary();drawDetail(draft.slots[0]);const i=draft.indicator;el('caps-enabled').checked=i.enabled;for(const k of ['on','off','x','y','width','height'])el('caps-'+k).value=i[k];}
 el('caps-state').textContent=state.desk.locks.caps?'Caps Lock on':'Caps Lock off';el('obs-status').textContent=state.desk.obsConnected?'OBS connected':'Not connected';for(const id of ['save-slot','remove-slot','run-slot','read-keyboard','save-indicator','connect-obs','pick-app'])if(!el(id).hasAttribute('aria-busy'))el(id).disabled=false;document.querySelectorAll('[data-system]').forEach(b=>b.disabled=false);}
el('plugin-search').addEventListener('input',drawLibrary);el('category').addEventListener('change',drawLibrary);el('clear-search').addEventListener('click',()=>{el('plugin-search').value='';drawLibrary();el('plugin-search').focus();});el('slot-action').addEventListener('change',actionHelp);
async function saveDesk(next){const state=await window.companion.saveDesk(next);renderDesk(state);draft=structuredClone(state.desk.config);drawSlots();announce(state.error||state.feedback,!!state.error);}
el('save-slot').addEventListener('click',()=>task(el('save-slot'),async()=>{const next=structuredClone(draft);next.slots[selectedPosition]={plugin:selectedPlugin,action:el('slot-action').value,value:el('slot-value').value};await saveDesk(next);}));
el('remove-slot').addEventListener('click',()=>task(el('remove-slot'),async()=>{const next=structuredClone(draft);next.slots[selectedPosition]=null;await saveDesk(next);}));
el('run-slot').addEventListener('click',()=>task(el('run-slot'),async()=>{const state=await window.companion.runSlot(selectedPosition);announce(state.error||state.feedback,!!state.error);}));
el('pick-app').addEventListener('click',()=>task(el('pick-app'),async()=>{const path=await window.companion.pickApp();if(path)el('slot-value').value=path;announce(path?'App selected. Add it to a position to save.':'App selection cancelled.');}));
el('save-indicator').addEventListener('click',()=>task(el('save-indicator'),async()=>{const next=structuredClone(draft);next.indicator.enabled=el('caps-enabled').checked;for(const k of ['on','off'])next.indicator[k]=el('caps-'+k).value;for(const k of ['x','y','width','height'])next.indicator[k]=Number(el('caps-'+k).value);await saveDesk(next);}));
el('connect-obs').addEventListener('click',()=>task(el('connect-obs'),async()=>{const state=await window.companion.connectObs(el('obs-password').value,Number(el('obs-port').value));if(state.desk.obsConnected)el('obs-password').value='';announce(state.error||state.feedback,!!state.error);}));
document.querySelectorAll('[data-system]').forEach(b=>b.addEventListener('click',()=>task(b,async()=>{await window.companion.mediaKey(b.dataset.system);announce('Windows media control sent.');})));
function selectedLayer(){return keymap?.layers.find(l=>l.id===Number(el('key-layer').value));}
function drawKeyboard(){const layer=selectedLayer();if(!layer)return;el('keyboard-map').replaceChildren();for(const [start,end]of [[0,16],[16,32],[32,45],[45,58],[58,68]]){const row=document.createElement('div');row.className='keyboard-row';for(const key of layer.keys.slice(start,end)){const b=document.createElement('button');b.className='key';b.textContent=key.name;b.title=`${key.name}: ${key.label}`;b.setAttribute('aria-pressed',String(key.position===selectedKey));b.addEventListener('click',()=>{selectedKey=key.position;drawKeyboard();});row.append(b);}el('keyboard-map').append(row);}
 const key=layer.keys[selectedKey];el('key-heading').textContent=key.name;el('key-current').textContent='Currently: '+key.label;const reserved=selectedKey===63||(layer.id===1&&[26,55].includes(selectedKey));el('save-key').disabled=reserved;el('swap-key').disabled=reserved;el('swap-target').replaceChildren(...layer.keys.filter(k=>k.position!==selectedKey&&k.position!==63&&!(layer.id===1&&[26,55].includes(k.position))).map(k=>option(k.position,k.name)));el('key-target').replaceChildren(...keymap.choices.map(c=>option(c.value,c.label)));const code=key.binding.param1||0;el('key-target').value=String(code&0xffffff);for(const[k,bit]of [['ctrl',1],['shift',2],['alt',4]])el('key-'+k).checked=!!((code>>>24)&bit);}
el('read-keyboard').addEventListener('click',()=>task(el('read-keyboard'),async()=>{keymap=await window.companion.readKeymap();drawKeyboard();el('key-status').textContent='Live bindings loaded. Select any key below.';announce('Keyboard bindings loaded.');}));el('key-layer').addEventListener('change',drawKeyboard);
async function changeKey(swap){keymap=await window.companion.changeKey({layer:Number(el('key-layer').value),position:selectedKey,value:Number(el('key-target').value),mods:(el('key-ctrl').checked?1:0)|(el('key-shift').checked?2:0)|(el('key-alt').checked?4:0),swap:swap?Number(el('swap-target').value):null});drawKeyboard();announce('Saved and read back from the keyboard. Your skin is unchanged.');}
el('save-key').addEventListener('click',()=>task(el('save-key'),()=>changeKey(false)));el('swap-key').addEventListener('click',()=>task(el('swap-key'),()=>changeKey(true)));
window.companion.subscribe(renderDesk);window.companion.getState().then(renderDesk).catch(e=>announce(e.message,true));
