const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const validSlot=slot=>Number.isInteger(slot)&&slot>=1&&slot<=5;
function identity(meta){if(!meta||meta.empty===true||typeof meta.fileID!=='string'||!meta.fileID)return null;return meta.fileID;}
class KeyboardSkins{
 constructor(directory,connect=()=>new(require('./som.cjs').Som)()){this.directory=path.join(directory,'keyboard-skins');this.connect=connect;this.busy=false;this.thumbnails=new Map();}
 current(s){return s.wait((c,p)=>c===48&&p.length===1&&validSlot(p[0])?p[0]:undefined,()=>s.send(48),5000);}
 details(s,slot){return s.wait((c,p)=>{if(c!==8||p[0]!==slot)return;const value=p.length>1?JSON.parse(p.subarray(1).toString('utf8').replace(/\0+$/,'')):{empty:true};if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Invalid skin information from keyboard.');return value;},()=>s.send(8,Buffer.from([slot])),5000);}
 async thumbnail(s,slot){const chunks=new Map();let expected;const data=await s.wait((c,p)=>{if(c!==7||p[0]!==slot||p.length<5)return;const index=p.readUInt16LE(1),total=p.readUInt16LE(3);if(!index&&!total)return null;if(total>2048||index>=total||expected!==undefined&&expected!==total)throw Error('Invalid skin thumbnail.');expected=total;chunks.set(index,Buffer.from(p.subarray(5)));if(chunks.size===total)return Buffer.concat(Array.from({length:total},(_,i)=>chunks.get(i)));},()=>s.send(7,Buffer.from([slot])),1800);if(!data)return null;const sharp=require('sharp'),png=await sharp(data,{limitInputPixels:4000000}).resize(1920,550,{fit:'fill'}).png().toBuffer();return 'data:image/png;base64,'+png.toString('base64');}
 async settle(s,target){const deadline=Date.now()+15000;let active;do{active=await this.current(s);if(active===target)return active;await new Promise(resolve=>setTimeout(resolve,350));}while(Date.now()<deadline);throw Error("The keyboard accepted the selection but did not finish loading skin slot "+target+". Try again after its current skin has loaded.");}
 async action(action,input={}){if(this.busy)throw Error('A keyboard skin operation is already running. Try again shortly.');if(!['read','select','default','set-default'].includes(action))throw Error('Choose a keyboard skin action.');this.busy=true;let s;
  try{s=this.connect();if(!s.identity)throw Error('The keyboard could not be identified. No default or skin was changed.');
   const file=path.join(this.directory,crypto.createHash('sha256').update(s.identity).digest('hex')+'.json');
   const current=await this.current(s),meta=await this.details(s,current);let saved;
   const persist=value=>{fs.mkdirSync(this.directory,{recursive:true});const temporary=file+'.'+crypto.randomUUID()+'.tmp';try{fs.writeFileSync(temporary,JSON.stringify(value,null,2),{flag:'wx'});fs.renameSync(temporary,file);}catch(error){try{fs.unlinkSync(temporary);}catch{}throw error;}};
   if(fs.existsSync(file)){try{saved=JSON.parse(fs.readFileSync(file,'utf8'));if(!validSlot(saved.default?.slot)||!identity(saved.default.meta)||!validSlot(saved.original?.slot)||!identity(saved.original.meta)||saved.selected&&(!validSlot(saved.selected.slot)||!identity(saved.selected.meta)))throw Error();}catch{throw Error('The default-skin record could not be read. Existing data was preserved; no skin was changed.');}}
   else{if(!identity(meta))throw Error('The active skin has no stable identifier. Default capture is unavailable; no skin was changed.');saved={original:{slot:current,meta},default:{slot:current,meta},selected:{slot:current,meta}};persist(saved);}
   let active=current;
   if(action==='set-default'){if(!identity(meta))throw Error('This skin cannot be saved as a default.');saved={...saved,default:{slot:current,meta}};persist(saved);}
   if(action==='select'||action==='default'){
    const target=action==='default'?saved.default.slot:input.slot;if(!validSlot(target))throw Error('Choose keyboard slot 1–5.');const targetMeta=await this.details(s,target);if(!identity(targetMeta))throw Error('This keyboard slot is empty. Install a compatible skin in XPANEL first.');
    if(action==='default'&&identity(targetMeta)!==identity(saved.default.meta))throw Error('The default slot was replaced outside Companion. Reinstall your saved default skin before returning to it.');
    if(target!==current){try{await s.wait((c,p)=>{if(c!==48||!p.length||p[0]!==target)return;if(p.length>1){const length=p.length>=4?p.readUInt16LE(2):0;const detail=p[1]===1&&length&&p.length>=4+length?p.subarray(4,4+length).toString('utf8').replace(/[\x00-\x1f]/g,' ').slice(0,240):p[1]===2?'The slot is empty.':'The skin may still be loading. Wait and try again.';throw Error('Keyboard could not activate slot '+target+': '+detail);}return true;},()=>s.send(48,Buffer.from([target])),10000);active=await this.settle(s,target);await new Promise(resolve=>setTimeout(resolve,1500));active=await this.settle(s,target);}catch(error){try{const previous=await this.details(s,current);if(identity(previous)===identity(meta)&&await this.current(s)!==current){s.send(48,Buffer.from([current]));await this.settle(s,current);}}catch{throw Error(error.message+' Returning to the previous skin could not be confirmed. Use Refresh to check the active slot.');}throw error;}}
   }
   if(action==='select'||action==='default'){const selectedMeta=await this.details(s,active);if(identity(selectedMeta)){saved={...saved,selected:{slot:active,meta:selectedMeta}};try{persist(saved);}catch{throw Error('The keyboard skin changed, but Companion could not remember the selection on this PC. Your default skin record was preserved. Check disk space and folder permissions.');}}}
   const slots=[];for(let slot=1;slot<=5;slot++){const m=await this.details(s,slot);slots.push({slot,name:typeof m.fileName==='string'?m.fileName.slice(0,120):'Empty',empty:!identity(m),isDefault:slot===saved.default.slot&&identity(m)===identity(saved.default.meta)});}
   const thumbnailKey=identity(await this.details(s,active));let thumbnail=this.thumbnails.get(thumbnailKey)||null;if(!this.thumbnails.has(thumbnailKey)){try{thumbnail=await this.thumbnail(s,active);}catch{}if(this.thumbnails.size>=5)this.thumbnails.clear();this.thumbnails.set(thumbnailKey,thumbnail);}
   return{thumbnail,active,slots,defaultSlot:saved.default.slot,defaultName:saved.default.meta.fileName||'Default skin',originalSlot:saved.original.slot,lastSelectedSlot:saved.selected?.slot??null,lastSelectedName:saved.selected?.meta?.fileName||null,selectionMatches:!!saved.selected&&active===saved.selected.slot&&thumbnailKey===identity(saved.selected.meta),canUpload:false};
  }finally{s?.close();this.busy=false;}
 }
}
module.exports={KeyboardSkins,validSlot,identity};
