const os=require('node:os'),fs=require('node:fs'),path=require('node:path'),{execFile}=require('node:child_process');
async function json(url){const response=await fetch(url,{signal:AbortSignal.timeout(8000),redirect:'error'});if(!response.ok)throw Error('Service unavailable. Try again later.');const reader=response.body.getReader();let count=0,chunks=[];try{while(true){const{done,value}=await reader.read();if(done)break;count+=value.length;if(count>1024*1024){await reader.cancel();throw Error('Service response exceeded its limit.');}chunks.push(value);}}finally{reader.releaseLock();}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
function conditions(code){return code===0?['Sunny','sun']:code<4?['Cloudy','cloud']:code<49?['Fog','cloud']:code<68?['Rain','rain']:code<78?['Snow','snow']:code<83?['Showers','rain']:code<87?['Snow','snow']:['Thunderstorm','storm'];}
function safeLocation(v){if(!v||!Number.isFinite(v.latitude)||v.latitude<-90||v.latitude>90||!Number.isFinite(v.longitude)||v.longitude<-180||v.longitude>180||typeof v.name!=='string'||v.name.length>120)throw Error('Choose a valid location.');return{latitude:v.latitude,longitude:v.longitude,name:v.name};}
class LiveData{
 constructor(system){this.system=system;this.state={weather:null,weatherError:'Choose Windows location or a city in Connections.',cpuLoad:null,cpuTemp:null,gpuTemp:null,sensorError:'Temperature sensors are not connected.',mic:null};this.weatherSettings={location:null,unit:'fahrenheit'};this.lastWeather=0;this.lastSensors=0;this.cpu=os.cpus();this.busy=false;this.weatherBusy=false;this.lhm=false;}
 async search(city){if(typeof city!=='string'||city.trim().length<2||city.length>100)throw Error('Enter at least two characters for a city.');const r=await json('https://geocoding-api.open-meteo.com/v1/search?count=6&language=en&name='+encodeURIComponent(city.trim()));return(r.results||[]).map(p=>safeLocation({latitude:p.latitude,longitude:p.longitude,name:[p.name,p.admin1,p.country].filter(Boolean).join(', ').slice(0,120)}));}
 async weather(force=false){if(this.weatherBusy||!this.weatherSettings.location||(!force&&Date.now()-this.lastWeather<600000))return;this.weatherBusy=true;this.lastWeather=Date.now();const requested=JSON.stringify(this.weatherSettings);const l=this.weatherSettings.location,u=this.weatherSettings.unit;if(this.state.weather&&(this.state.weather.location!==l.name||this.state.weather.unit!==(u==='fahrenheit'?'°F':'°C')))this.state.weather=null;try{const r=await json(`https://api.open-meteo.com/v1/forecast?latitude=${l.latitude}&longitude=${l.longitude}&current=temperature_2m,weather_code&temperature_unit=${u}`);if(!Number.isFinite(r.current?.temperature_2m)||!Number.isFinite(r.current.weather_code))throw Error('Weather service returned no current reading.');if(JSON.stringify(this.weatherSettings)!==requested)return;const[label,icon]=conditions(r.current.weather_code);this.state.weather={temperature:Math.round(r.current.temperature_2m),unit:u==='fahrenheit'?'°F':'°C',label,icon,location:l.name,updatedAt:Date.now()};this.state.weatherError='';}catch(e){this.state.weatherError=e.message;this.lastWeather=Date.now()-540000;}finally{this.weatherBusy=false;if(JSON.stringify(this.weatherSettings)!==requested)this.lastWeather=0;}}
 async sample(){if(this.busy)return;this.busy=true;try{const next=os.cpus();let idle=0,total=0;next.forEach((c,i)=>{const old=this.cpu[i];if(!old)return;for(const k of Object.keys(c.times)){const n=c.times[k]-old.times[k];total+=n;if(k==='idle')idle+=n;}});this.cpu=next;this.state.cpuLoad=total>0?Math.max(0,Math.min(100,Math.round((1-idle/total)*100))):null;
  try{this.state.mic=await this.system.request('mic-status');}catch{this.state.mic=null;}
  if(Date.now()-this.lastSensors>5000){this.lastSensors=Date.now();this.state.cpuTemp=null;this.state.gpuTemp=null;
   if(this.lhm){try{const tree=await json('http://127.0.0.1:8085/data.json');let visited=0;const walk=(node,ancestors='',depth=0)=>{if(!node||typeof node!=='object'||depth>40||++visited>10000)return;const label=ancestors+' '+String(node.Text||'');const value=Number.parseFloat(String(node.Value||'').replace(',','.'));if(/temperatures/i.test(ancestors)&&Number.isFinite(value)&&/°?C/.test(String(node.Value))){if(/gpu/i.test(label))this.state.gpuTemp??=Math.round(value);else if(/cpu|package|core/i.test(label))this.state.cpuTemp=Math.max(this.state.cpuTemp??-100,Math.round(value));}for(const n of Array.isArray(node.Children)?node.Children:[])walk(n,label,depth+1);};walk(tree);}catch(e){this.state.sensorError='Libre Hardware Monitor is unavailable on this PC.';}}
   const executable=path.join(process.env.SystemRoot||'C:/Windows','System32','nvidia-smi.exe');if(fs.existsSync(executable))try{const value=await new Promise((resolve,reject)=>execFile(executable,['--query-gpu=temperature.gpu','--format=csv,noheader,nounits'],{windowsHide:true,timeout:3000,maxBuffer:4096},(err,out)=>err?reject(err):resolve(Number.parseFloat(out))));if(Number.isFinite(value))this.state.gpuTemp=value;}catch{}
   this.state.sensorError=this.state.cpuTemp!==null||this.state.gpuTemp!==null?'':'No temperature sensor is available. Connect Libre Hardware Monitor for CPU/AMD readings.';
  }await this.weather();
 }finally{this.busy=false;}}
}
module.exports={LiveData,conditions,safeLocation,json};
