const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('companion', {
  setStartup:enabled=>ipcRenderer.invoke('set-startup',enabled),
  xpanelRefresh:()=>ipcRenderer.invoke('xpanel-refresh'),
  xpanelDownload:id=>ipcRenderer.invoke('xpanel-download',id),
  communityRefresh:()=>ipcRenderer.invoke('community-refresh'),
  communityLogin:()=>ipcRenderer.invoke('community-login'),
  communityCancelLogin:()=>ipcRenderer.invoke('community-cancel-login'),
  communityLogout:()=>ipcRenderer.invoke('community-logout'),
  communitySubmit:input=>ipcRenderer.invoke('community-submit',input),
  communityReview:(id,status)=>ipcRenderer.invoke('community-review',id,status),
  communityColor:color=>ipcRenderer.invoke('community-color',color),
  communitySkin:id=>ipcRenderer.invoke('community-skin',id),
  updateCheck:()=>ipcRenderer.invoke('update-check'),
  updateDownload:()=>ipcRenderer.invoke('update-download'),
  updateInstall:()=>ipcRenderer.invoke('update-install'),
  getState: () => ipcRenderer.invoke('get-state'),
  action: (plugin, action) => ipcRenderer.invoke('action', plugin, action),
  shortcuts: enabled => ipcRenderer.invoke('shortcuts', enabled),
  pluginMode: () => ipcRenderer.invoke('plugin-mode'),
  saveDesk: config => ipcRenderer.invoke('save-desk',config),
  runSlot: index => ipcRenderer.invoke('run-slot',index),
  mediaKey: action => ipcRenderer.invoke('media-key',action),
  pickApp: () => ipcRenderer.invoke('pick-app'),
  listLanguages:()=>ipcRenderer.invoke('list-languages'),
  setLanguage:id=>ipcRenderer.invoke('set-language',id),
  languageSettings:()=>ipcRenderer.invoke('language-settings'),
  reconnectKeyboard:()=>ipcRenderer.invoke('reconnect-keyboard'),
  windowControl:action=>ipcRenderer.invoke('window-control',action),
  subscribeWindow:callback=>{const listener=(_e,value)=>callback(value);ipcRenderer.on('window-state',listener);return()=>ipcRenderer.removeListener('window-state',listener);},
  readTelemetry:()=>ipcRenderer.invoke('read-telemetry'),
  readKeymap: () => ipcRenderer.invoke('read-keymap'),
  captureKey: enabled => ipcRenderer.invoke('capture-key',enabled),
  subscribeKey: callback => {const listener=(_e,p)=>callback(p);ipcRenderer.on('selected-key',listener);return()=>ipcRenderer.removeListener('selected-key',listener);},
  searchCity: city => ipcRenderer.invoke('search-city',city),
  windowsLocation: () => ipcRenderer.invoke('windows-location'),
  setWeather: (location,unit) => ipcRenderer.invoke('set-weather',location,unit),
  connectTwitch: channel => ipcRenderer.invoke('connect-twitch',channel),
  cancelTwitch:()=>ipcRenderer.invoke('cancel-twitch'),
  disconnectService: name => ipcRenderer.invoke('disconnect-service',name),
  setupKeyboard: () => ipcRenderer.invoke('setup-keyboard'),
  restoreKeyboard: () => ipcRenderer.invoke('restore-keyboard'),
  changeKey: data => ipcRenderer.invoke('change-key',data),
  connectObs: (password,port) => ipcRenderer.invoke('connect-obs',password,port),
  inspectDevice: () => ipcRenderer.invoke('inspect-device'),
  subscribe: callback => { const listener = (_event, state) => callback(state); ipcRenderer.on('state', listener); return () => ipcRenderer.removeListener('state', listener); }
});
