const fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto');
// Profiles intentionally store display choices only; never connections or keymaps.
function snapshot(config){return structuredClone({slots:config.slots,widget:{type:config.widget.type,text:config.widget.text},widgetOrder:config.widgetOrder,timerMinutes:config.timerMinutes});}
function merge(config,saved){return {...config,slots:saved.slots,widget:{...config.widget,...saved.widget},widgetOrder:saved.widgetOrder,timerMinutes:saved.timerMinutes};}
function appName(value){if(typeof value!=='string'||value.length>100||!value.endsWith('.exe')||/[\\/:*?"<>|\x00-\x1f]/.test(value))throw Error('Choose an app executable, for example obs64.exe.');return value.toLowerCase();}
class Profiles {
 constructor(directory,workspace,apply,allowed=()=>true){this.file=path.join(directory,'profiles.json');this.workspace=workspace;this.apply=apply;this.allowed=allowed;this.data={enabled:false,items:[],base:null};this.active=null;this.candidate=null;this.samples=0;this.busy=false;this.error='';this.revision=0;
  try{const value=JSON.parse(fs.readFileSync(this.file,'utf8'));if(!Array.isArray(value.items)||value.items.length>20)throw Error('Invalid profiles');this.data.items=value.items.map(p=>{if(typeof p.id!=='string'||typeof p.name!=='string'||p.name.length>40)throw Error('Invalid profile');return{id:p.id,name:p.name,app:p.app?appName(p.app):'',snapshot:snapshot(workspace.validate(merge(workspace.config,p.snapshot)))};});this.data.base=value.base?snapshot(workspace.validate(merge(workspace.config,value.base))):null;this.data.enabled=value.enabled===true&&!!this.data.base;}catch{}this.persisted=structuredClone(this.data);
 }
 persist(){try{fs.mkdirSync(path.dirname(this.file),{recursive:true});fs.writeFileSync(this.file+'.tmp',JSON.stringify(this.data,null,2));fs.renameSync(this.file+'.tmp',this.file);this.revision++;this.persisted=structuredClone(this.data);}catch(e){this.data=structuredClone(this.persisted);throw e;}}
 view(){return{enabled:this.data.enabled,active:this.active,items:this.data.items.map(({snapshot,...p})=>p),error:this.error,revision:this.revision};}
 find(id){const p=this.data.items.find(p=>p.id===id);if(!p)throw Error('Choose a saved profile.');return p;}
 save(name,id){if(this.busy)throw Error('Wait for the current profile to finish.');if(typeof name!=='string'||!name.trim()||name.trim().length>40)throw Error('Name your profile using 1–40 characters.');name=name.trim();if(this.data.items.some(p=>p.id!==id&&p.name.toLowerCase()===name.toLowerCase()))throw Error('That profile name is already used.');let p=id?this.find(id):null;if(!p){if(this.data.items.length>=20)throw Error('You can save up to 20 profiles.');p={id:randomUUID(),app:''};this.data.items.push(p);}Object.assign(p,{name,snapshot:snapshot(this.workspace.config)});this.persist();return p.id;}
 link(id,executable){if(this.busy)throw Error('Wait for the current profile to finish.');const p=this.find(id),name=executable?appName(executable):'';if(name&&this.data.items.some(p=>p.id!==id&&p.app===name))throw Error('That app already has a profile. Remove its other link first.');p.app=name;this.candidate=null;this.persist();}
 remove(id){if(this.busy)throw Error('Wait for the current profile to finish.');this.find(id);this.data.items=this.data.items.filter(p=>p.id!==id);this.persist();}
 enable(value){if(typeof value!=='boolean')throw Error('Invalid automatic profile setting.');if(this.busy)throw Error('Wait for the current profile to finish.');if(value&&!this.data.enabled)this.data.base=snapshot(this.workspace.config);this.data.enabled=value;this.active=null;this.candidate=null;this.persist();}
 async load(id){if(this.busy)throw Error('Wait for the current profile to finish.');const saved=id==='default'?this.data.base:this.find(id).snapshot;if(!saved)throw Error('Enable automatic profiles once to save a default layout.');this.enable(false);this.busy=true;try{await this.apply(merge(this.workspace.config,saved),false);this.active=id;this.error='';}finally{this.busy=false;}}
 async tick(executable){if(!this.data.enabled||this.busy||!this.allowed())return;const selected=this.data.items.find(p=>p.app&&p.app===String(executable).toLowerCase()),id=selected?.id||'default';if(this.candidate!==id){this.candidate=id;this.samples=1;return;}if(++this.samples<2||this.active===id)return;
  this.busy=true;try{if(!this.allowed())return;const applied=await this.apply(merge(this.workspace.config,selected?.snapshot||this.data.base),true);if(applied===false)return;this.active=id;this.error='';}catch(e){this.error=e.message;this.data.enabled=false;this.persist();}finally{this.busy=false;}
 }
}
module.exports={Profiles,snapshot,merge,appName};
