function formatCountdown(seconds){seconds=Math.max(0,Math.ceil(seconds||0));return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');}
let captureTimer,releaseLoaded=false,cityRevision=0,widgetRevision=0;
function releaseRoute(){const pages=['library','keyboard','widgets','profiles','media','connections','community','skins'];const page=pages.includes(location.hash.slice(1))?location.hash.slice(1):'library';document.querySelectorAll('[data-page]').forEach(s=>s.hidden=s.dataset.page!==page);document.querySelectorAll('.sidebar a').forEach(a=>{a.hash==='#'+page?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current');});const h=document.querySelector(`[data-page="${page}"] h1`);document.title=h.textContent+' · Centerpiece Companion';h.focus();if(page!=='keyboard'){window.companion.captureKey(false);stopCapture();}else if(!keymap&&deskCurrent&&!deskBusy){task(el('read-keyboard'),async()=>{keymap=await window.companion.readKeymap();drawKeyboard();el('key-status').textContent='Live bindings loaded. Select a key.';announce('');});}}
window.removeEventListener('hashchange',route);window.addEventListener('hashchange',releaseRoute);releaseRoute();
const oldDrawKeyboard=drawKeyboard;
drawKeyboard=function(){oldDrawKeyboard();if(!keymap)return;const map=el('keyboard-map');const buttons=[...map.querySelectorAll('.key')];map.replaceChildren();map.classList.add('physical-board');buttons.forEach((button,index)=>{const k=keymap.layout.keys[index];button.style.left=((k.x||0)/1800*100)+'%';button.style.top=((k.y||0)/500*100)+'%';button.style.width=(k.width/1800*100)+'%';button.style.height=(k.height/500*100)+'%';button.textContent=languageLabel(selectedLayer().keys[index].label,deskCurrent.desk.language);button.setAttribute('aria-label',`${selectedLayer().keys[index].name}, assigned ${selectedLayer().keys[index].label}`);map.append(button);});const strip=document.createElement('div');strip.className='board-strip';strip.setAttribute('aria-hidden','true');for(const s of draft.slots){const p=deskCurrent.desk.catalog.find(p=>p.id===s?.plugin);const tile=document.createElement('div');if(p){const img=document.createElement('img');img.src=`icons/${p.icon}.svg`;img.alt='';tile.append(img);}else tile.textContent='+';strip.append(tile);}map.append(strip);const widget=document.createElement('button');widget.className='board-widget';widget.textContent='Screen widget';widget.addEventListener('click',()=>{location.hash='widgets';});map.append(widget);};
function stopCapture(){clearTimeout(captureTimer);el('capture-key').textContent='Press a key to select';el('capture-key').setAttribute('aria-pressed','false');}
el('capture-key').addEventListener('click',()=>task(el('capture-key'),async()=>{if(!keymap){keymap=await window.companion.readKeymap();drawKeyboard();}await window.companion.captureKey(true);el('capture-key').textContent='Press a key now…';el('capture-key').setAttribute('aria-pressed','true');announce('Listening for one physical key for 10 seconds. Nothing is recorded.');captureTimer=setTimeout(()=>{stopCapture();announce('Key selection timed out. Try again.');},10000);}));
window.companion.subscribeKey(position=>{stopCapture();selectedKey=position;drawKeyboard();announce('Selected '+selectedLayer().keys[position].name+'.');});
async function configChange(change){const next=structuredClone(draft);change(next);await saveDesk(next);}
function bind(id,fn){el(id).addEventListener('click',()=>task(el(id),fn));}
bind('save-layer',()=>configChange(c=>c.layerColor=el('layer-match').checked?'':el('layer-color').value));
bind('save-widget',async()=>{const widget={type:el('widget-type').value,text:el('widget-text').value};for(const k of ['x','y','width','height'])widget[k]=Number(el('widget-'+k).value);const state=await window.companion.saveWidget(widget);draft=structuredClone(state.desk.config);renderRelease(state);announce(state.error||state.feedback,!!state.error);});
bind('save-sensors',()=>configChange(c=>c.sensors=el('enable-lhm').checked));
async function chooseWeather(location){const state=await window.companion.setWeather(location,el('weather-unit').value);draft=structuredClone(state.desk.config);renderRelease(state);await saveDesk(draft);announce(state.desk.live.weatherError||'Weather location saved on this PC.',!!state.desk.live.weatherError);}
bind('windows-location',async()=>chooseWeather(await window.companion.windowsLocation()));
bind('find-city',async()=>{const revision=++cityRevision;const results=await window.companion.searchCity(el('city-search').value);if(revision!==cityRevision)return;el('city-results').replaceChildren();if(!results.length){announce('No matching city. Try adding a country or region.');return;}for(const result of results){const button=document.createElement('button');button.className='button';button.textContent=result.name;button.addEventListener('click',()=>task(button,()=>chooseWeather(result)));el('city-results').append(button);}announce('Choose the matching location below.');});
el('city-search').addEventListener('input',()=>{cityRevision++;el('city-results').replaceChildren();});
bind('connect-twitch',async()=>{if(deskCurrent?.desk?.chat?.auth?.pending){renderRelease(await window.companion.cancelTwitch());return;}renderRelease(await window.companion.connectTwitch(el('twitch-channel').value.trim()));announce('Approve Twitch in your browser. You can keep using the companion.');});
for(const name of ['obs','twitch'])bind('disconnect-'+name,async()=>{renderRelease(await window.companion.disconnectService(name));announce('Disconnected '+name+'.');});
bind('setup-device',async()=>{const state=await setupUIAction(()=>window.companion.setupKeyboard());if(!state)return;renderRelease(state);announce(state.feedback);if(state.setupRecovery)window.dispatchEvent(new CustomEvent('setup-review-ready',{detail:state.setupRecovery}));});
bind('restore-device',async()=>{const state=await window.companion.restoreKeyboard();renderRelease(state);announce(state.feedback);});
function renderRelease(state){if(!state.desk)return;deskCurrent=state;if((state.widgetRevision||0)!==widgetRevision){widgetRevision=state.widgetRevision;draft.widget=structuredClone(state.desk.config.widget);el('widget-type').value=draft.widget.type;el('widget-text').value=draft.widget.text;for(const k of ['x','y','width','height'])el('widget-'+k).value=draft.widget[k];}el('setup-banner').hidden=!!state.strip;for(const id of ['load-languages','apply-language','windows-languages','capture-key','save-layer','save-widget','save-sensors','windows-location','find-city','connect-twitch','disconnect-twitch','disconnect-obs','setup-device','restore-device'])if(!el(id).hasAttribute('aria-busy'))el(id).disabled=false;el('restore-device').disabled=!state.strip||!!state.setupRunning;el('setup-device').disabled=!!state.setupRunning||el('setup-device').hasAttribute('aria-busy');
 if(!releaseLoaded){releaseLoaded=true;const c=state.desk.config;if(![...el('keyboard-language').options].some(o=>o.value===c.languageId))el('keyboard-language').append(option(c.languageId,state.desk.language?.name||'Saved Windows layout'));el('keyboard-language').value=c.languageId;el('layer-match').checked=!c.layerColor;el('layer-color').value=c.layerColor||c.indicator.on;el('widget-type').value=c.widget.type;el('widget-text').value=c.widget.text;for(const k of ['x','y','width','height'])el('widget-'+k).value=c.widget[k];el('weather-unit').value=c.weather.unit;el('enable-lhm').checked=c.sensors;}
 const live=state.desk.live;el('weather-status').textContent=live.weather?`${live.weather.temperature}${live.weather.unit} · ${live.weather.label}`:live.weatherError;el('sensor-status').textContent=`CPU ${live.cpuLoad??'—'}% · CPU temperature ${live.cpuTemp??'—'}°C · GPU ${live.gpuTemp??'—'}°C. ${live.sensorError}`;el('twitch-status').textContent=state.desk.chat.auth?.status||'Not connected';el('connect-twitch').textContent=state.desk.chat.auth?.pending?'Cancel connection':'Connect with Twitch';if(!el('twitch-channel').value&&state.desk.chat.auth?.channel)el('twitch-channel').value=state.desk.chat.auth.channel;
 const preview=el('widget-preview');const type=el('widget-type').value;const heading=document.createElement('strong'),detail=document.createElement('span');heading.textContent=type==='spotify'?(state.media.title||'Open Spotify'):type==='weather'?(live.weather?live.weather.temperature+live.weather.unit:'Choose location'):type==='cpu'?`${live.cpuTemp??live.cpuLoad??'—'}${live.cpuTemp!=null?'°C':'%'}`:type==='gpu'?`${live.gpuTemp??'—'}°C`:type==='timer'?formatCountdown(state.desk.timer?.remaining??1500):type==='obs'?(state.desk.obsStatus?.streaming?'ON AIR':state.desk.obsStatus?.recording?'RECORDING':state.desk.obsStatus?.connected?'OBS READY':'Connect OBS'):type==='twitch'?'TWITCH CHAT':type==='text'?el('widget-text').value:type==='off'?'Widget off':new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});detail.textContent=type==='spotify'?(state.media.artist||''):type==='twitch'?state.desk.chat.message:'Detail display preview';const previewKey=JSON.stringify([type,heading.textContent,detail.textContent,type==='spotify'?state.media.art:'',type==='weather'?live.weather?.icon:'']);if(preview.dataset.previewKey!==previewKey){preview.dataset.previewKey=previewKey;preview.replaceChildren(heading,detail);if(type==='weather'){const weather=document.createElement('span');weather.className='weather-motion '+(live.weather?.icon||'cloud');weather.setAttribute('aria-hidden','true');weather.textContent=({sun:'☀',cloud:'☁',rain:'☁',snow:'☁',storm:'ϟ'})[live.weather?.icon]||'☁';preview.prepend(weather);}if(type==='spotify'&&/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(state.media.art||'')){const cover=document.createElement('img');cover.src=state.media.art;cover.alt='Album cover';cover.className='widget-art';preview.prepend(cover);}}
}
el('widget-type').addEventListener('change',()=>renderRelease(deskCurrent));el('widget-text').addEventListener('input',()=>{if(el('widget-text').value.trim())el('widget-type').value='text';renderRelease(deskCurrent);});
window.companion.subscribe(renderRelease);window.companion.getState().then(renderRelease).catch(e=>announce(e.message,true));

bind('load-languages',async()=>{const items=await window.companion.listLanguages();el('keyboard-language').replaceChildren(...items.map(i=>option(i.id,i.name)));el('keyboard-language').value=deskCurrent.desk.config.languageId;announce(items.length+' Windows keyboard layouts available.');});
bind('apply-language',async()=>{const state=await window.companion.setLanguage(el('keyboard-language').value);draft=structuredClone(state.desk.config);renderRelease(state);if(keymap)drawKeyboard();announce('Keyboard labels applied. Choose the matching Windows typing language separately.');});
bind('windows-languages',()=>window.companion.languageSettings());
