const fs=require('node:fs'),path=require('node:path');const{Som}=require('./som.cjs');const{Studio}=require('./studio.cjs');
const binding={behaviorId:50397,param1:0x05070013};
async function setup(directory){fs.mkdirSync(directory,{recursive:true});const file=path.join(directory,'hardware.json');const prior=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):null;const s=new Studio();let som;try{
 await require('./studio-response.cjs').requireCleanSetup(s);const map=(await s.request({keymap:{getKeymap:true}})).keymap.getKeymap;
 const base=map.layers.find(l=>(l.id||0)===0),layer=map.layers.find(l=>l.id===1);if(base?.bindings.length!==68||layer?.bindings.length!==68||base.bindings[63].param1!==1)throw Error('This release supports the 68-key Centerpiece Pro layout.');
 som=new Som();if(prior&&prior.serial!==som.serial)throw Error('The saved setup belongs to a different keyboard. Use a separate Windows user profile for this keyboard.');
 if(prior?.verified&&!prior.restored)return prior;
 const current=layer.bindings[26];if(current.behaviorId!==60498&&!(prior&&current.behaviorId===binding.behaviorId&&current.param1===binding.param1))throw Error('L1+P is customized. Restore its stock Plugin Toggle behavior in XPANEL before setup.');
 for(let n=2;n<=10;n++){const bytes=await som.readOverlay(n);if(bytes&&!prior?.ownedSlots?.includes(n))throw Error(`Overlay slot ${n} is occupied. Setup stopped before changing your keyboard. Keep your existing overlays backed up before freeing slots 2–10.`);}
 const backup=prior||{serial:som.serial,keyboardSerial:s.serial,originalSlot:await som.currentSlot(),originalBinding:current,layerId:1,keyPosition:26,ownedSlots:[2,3,4,5,6,7,8,9,10],createdAt:new Date().toISOString()};
 if(!prior)fs.writeFileSync(path.join(directory,'keymap-original.json'),JSON.stringify(map,null,2));fs.writeFileSync(file,JSON.stringify(backup,null,2));
 if((await s.request({keymap:{setLayerBinding:{layerId:1,keyPosition:26,binding}}})).keymap.setLayerBinding!==0)throw Error('Keyboard rejected the plugin key.');
 const saved=(await s.request({keymap:{saveChanges:true}})).keymap.saveChanges;if(!saved||saved.err)throw Error('Keyboard did not save setup.');const after=(await s.request({keymap:{getKeymap:true}})).keymap.getKeymap;layer.bindings[26]=binding;if(JSON.stringify(map)!==JSON.stringify(after))throw Error('Setup readback differed. Read the keyboard in XPANEL before retrying.');
 backup.installedBinding=binding;backup.verified=true;backup.restored=false;fs.writeFileSync(file,JSON.stringify(backup,null,2));return backup;
 }finally{s.close();som?.close();}}
async function restore(directory){await require('./widget-shortcut.cjs').widgetShortcut(directory,true);const file=path.join(directory,'hardware.json'),backup=JSON.parse(fs.readFileSync(file,'utf8'));const s=new Studio();let som;try{som=new Som();if(som.serial!==backup.serial)throw Error('A different keyboard is connected.');if((await s.request({keymap:{checkUnsavedChanges:true}})).keymap.checkUnsavedChanges)throw Error('Save XPANEL edits first.');const map=(await s.request({keymap:{getKeymap:true}})).keymap.getKeymap,b=map.layers.find(l=>l.id===1).bindings[26];if(b.behaviorId!==binding.behaviorId||b.param1!==binding.param1)throw Error('L1+P changed outside this app; restoration stopped.');if((await s.request({keymap:{setLayerBinding:{layerId:1,keyPosition:26,binding:backup.originalBinding}}})).keymap.setLayerBinding!==0)throw Error('Restoration rejected.');const saved=(await s.request({keymap:{saveChanges:true}})).keymap.saveChanges;if(!saved||saved.err)throw Error('Restoration did not save.');map.layers.find(l=>l.id===1).bindings[26]=backup.originalBinding;const after=(await s.request({keymap:{getKeymap:true}})).keymap.getKeymap;if(JSON.stringify(map)!==JSON.stringify(after))throw Error('Restoration readback differed.');await som.activate(backup.originalSlot||0);backup.restored=true;fs.writeFileSync(file,JSON.stringify(backup,null,2));}finally{s.close();som?.close();}}
module.exports={setup,restore};
