(()=>{
 const routes={studio:['design','Skin Studio'],'studio-presets':['presets','Skin library']};
 const nav=document.querySelector('.sidebar nav');
 for(const [route,[,title]] of Object.entries(routes)){const a=document.createElement('a');a.href=`#${route}`;a.textContent=title;nav.append(a);}
 const section=document.createElement('section');section.dataset.page='studio';section.hidden=true;section.className='studio-container';
 const heading=document.createElement('h1');heading.className='studio-accessible-title';heading.tabIndex=-1;heading.textContent='Skin Studio';
 const frame=document.createElement('iframe');frame.id='studio-frame';frame.title='Skin Studio workbench';frame.setAttribute('sandbox','allow-scripts allow-same-origin allow-downloads');section.append(heading,frame);document.querySelector('.shell>main').append(section);
 const origin=location.protocol==='file:'?'null':location.origin,target=origin==='null'?'*':origin;let ready=false,pendingPreset=null,pendingProject=null,pendingNew=false;const libraryActions=new Map();
 const send=route=>{if(ready)frame.contentWindow.postMessage({type:'studio-navigate',route},target);};
 function hubRoute(){if(location.hash==='#profiles')history.replaceState(null,'','#studio');if(location.hash==='#media')history.replaceState(null,'','#keyboard');if(location.hash==='#studio-export')history.replaceState(null,'','#studio');const entry=routes[location.hash.slice(1)];document.body.classList.toggle('studio-active',!!entry);if(!entry){if(ready)frame.contentWindow.postMessage({type:'studio-exit-creation'},target);return releaseRoute();}
  document.querySelectorAll('[data-page]').forEach(s=>s.hidden=s!==section);
  document.querySelectorAll('.sidebar a').forEach(a=>a.hash===location.hash?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current'));
  heading.textContent=entry[1];document.title=entry[1]+' · Centerpiece Companion';
  window.companion.captureKey(false);stopCapture();
  if(!frame.getAttribute('src'))frame.src='../studio/index.html?embedded=1#'+entry[0];else send(entry[0]);
 }
 const active=new Set();let heavyRequest=false;
 window.addEventListener('message',async e=>{
  if(e.source!==frame.contentWindow||e.origin!==origin||!e.data||typeof e.data!=='object')return;
  const m=e.data;
  if(m.type==='studio-ready'){ready=true;const r=routes[location.hash.slice(1)];if(r)send(r[0]);if(pendingPreset){frame.contentWindow.postMessage({type:'studio-open-preset',id:pendingPreset},target);pendingPreset=null;}if(pendingProject!==null){frame.contentWindow.postMessage({type:'studio-open-saved-project',index:pendingProject},target);pendingProject=null;}if(pendingNew){frame.contentWindow.postMessage({type:'studio-new-project'},target);pendingNew=false;}for(const [id,task] of libraryActions)frame.contentWindow.postMessage({type:'studio-library-action',id,action:task.action,input:task.input},target);return;}
  if(m.type==='studio-projects-changed'){try{const safe=StudioScenes.validate(m.library);window.MySkins?.updateProjects(safe);}catch{}return;}
  if(m.type==='studio-library-result'){const task=libraryActions.get(m.id);if(!task)return;libraryActions.delete(m.id);clearTimeout(task.timer);m.error?task.reject(Error(String(m.error).slice(0,500))):task.resolve(m.value);return;}
  if(m.type==='studio-route'){const r=Object.entries(routes).find(([,v])=>v[0]===m.route);if(r&&routes[location.hash.slice(1)]){history.replaceState(null,'','#'+r[0]);heading.textContent=r[1][1];document.title=r[1][1]+' · Centerpiece Companion';document.querySelectorAll('.sidebar a').forEach(a=>a.hash===location.hash?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current'));}return;}
  if(m.type!=='studio-request'||typeof m.id!=='string'||!/^[-a-f0-9]{36}$/.test(m.id)||!['layout','export','inspect','overlay','tools','collection','physical-test','unreal-setup','keyboard-skins','review-project','browse-community','build-start','build-latest','build-status','build-cancel','build-download','photo-start','photo-status','photo-cancel','unreal-create','unreal-list','unreal-capabilities','unreal-dock','unreal-undock','unreal-cook-start','unreal-cook-cancel','unreal-cook-status','unreal-cook-download','unreal-open','dependencies-check','dependencies-status','dependencies-install','device-prepare','device-execute','device-restore','device-status','device-readiness'].includes(m.action)||active.has(m.id))return;
  const reply=value=>frame.contentWindow.postMessage({type:'studio-response',id:m.id,...value},target);
  if(active.size>=6)return reply({error:'Please wait for the current Studio action to finish.'});const heavy=['export','inspect','unreal-create'].includes(m.action);if(heavy&&heavyRequest)return reply({error:'Please wait for the current export or inspection.'});if(heavy)heavyRequest=true;
  active.add(m.id);try{if(m.action==='review-project'){const project=StudioModel.validate(m.input);await window.MySkins.prepareReview(project);reply({value:true});}else if(m.action==='browse-community'){window.MySkins?.showCommunity();reply({value:true});}else if(m.action==='keyboard-skins'){reply({value:await window.companion.keyboardSkins(m.input?.action,m.input?.input)});}else if(m.action==='overlay'){const state=deskCurrent;reply({value:{image:await window.companion.previewLayout(state.desk.config,{overlayOnly:true,caps:state.desk.locks?.caps===true}),sample:state.localPreview===true}});}else if(m.action==='unreal-setup'){await window.companion.openUnrealSetup();reply({value:true});}else if(m.action==='unreal-dock'){const rect=frame.getBoundingClientRect(),b=m.input?.bounds;reply({value:await window.companion.studioRequest(m.action,{id:m.input?.id,bounds:{x:rect.x+b.x,y:rect.y+b.y,width:Math.min(b.width,innerWidth-rect.x-b.x-4),height:Math.min(b.height,innerHeight-rect.y-b.y-4)}})});}else reply({value:await window.companion.studioRequest(m.action,m.input)});}catch(error){reply({error:error.message||'Studio could not finish this action. Your project was kept.',code:/^STUDIO_[A-Z_]+$/.test(error.code||'')?error.code:undefined});}finally{active.delete(m.id);if(heavy)heavyRequest=false;}
 });
 window.addEventListener('studio-open-preset',e=>{const id=e.detail?.id;if(typeof id!=='string'||!/^[a-z][a-z0-9-]{0,79}$/.test(id))return;pendingProject=null;pendingNew=false;pendingPreset=id;location.hash='#studio';hubRoute();if(ready){frame.contentWindow.postMessage({type:'studio-open-preset',id:pendingPreset},target);pendingPreset=null;}});
 function ensureWorkbench(){if(!frame.getAttribute('src'))frame.src='../studio/index.html?embedded=1#design';}
 window.addEventListener('studio-open-saved-project',e=>{const index=e.detail?.index;if(!Number.isInteger(index)||index<0||index>4)return;pendingPreset=null;pendingNew=false;pendingProject=index;location.hash='#studio';hubRoute();if(ready){frame.contentWindow.postMessage({type:'studio-open-saved-project',index},target);pendingProject=null;}});
 window.addEventListener('studio-new-project',()=>{pendingPreset=null;pendingProject=null;pendingNew=true;location.hash='#studio';hubRoute();if(ready){frame.contentWindow.postMessage({type:'studio-new-project'},target);pendingNew=false;}});
 for(const [event,action] of [['studio-archive-saved-project','archive'],['studio-restore-saved-project','restore']])window.addEventListener(event,e=>{
  const detail=e.detail||{};try{if(!Number.isInteger(detail.index)||detail.index<0||detail.index>4)throw Error('Choose a saved project space.');const project=StudioModel.validate(action==='archive'?detail.expectedProject:detail.project),id=crypto.randomUUID(),input={index:detail.index,project,expiresAt:Date.now()+15000};const timer=setTimeout(()=>{libraryActions.delete(id);detail.reject?.(Error('Studio could not confirm the library change in time. Refresh My skins before retrying; any archived backup is kept.'));},15000);libraryActions.set(id,{action,input,timer,resolve:detail.resolve||(()=>{}),reject:detail.reject||(()=>{})});ensureWorkbench();if(ready)frame.contentWindow.postMessage({type:'studio-library-action',id,action,input},target);}catch(error){detail.reject?.(error);}
 });
 window.addEventListener('studio-review-project',e=>{if(e.detail?.project)window.MySkins?.prepareReview(StudioModel.validate(e.detail.project));});
 window.removeEventListener('hashchange',releaseRoute);window.addEventListener('hashchange',hubRoute);hubRoute();
window.addEventListener('hashchange',()=>{if(!['studio','studio-export'].includes(location.hash.slice(1)))frame.contentWindow?.postMessage({type:'studio-close-native-editor'},target);});
})();
