const fs=require('node:fs'),path=require('node:path');
const {EventEmitter}=require('node:events');
const TOKEN=/^[a-zA-Z0-9]{15,512}$/;const REFRESH=/^[!-~]{15,2048}$/;
function channelName(value){if(typeof value!=='string')throw Error('Enter a Twitch channel name or link.');let channel=value.trim();if(/^https?:/i.test(channel)){let u;try{u=new URL(channel);}catch{throw Error('Enter a valid Twitch channel link.');}if(!['twitch.tv','www.twitch.tv','m.twitch.tv'].includes(u.hostname)||u.username||u.password||u.port||!/^\/[a-z0-9_]+\/?$/i.test(u.pathname))throw Error('Use a twitch.tv channel link.');channel=u.pathname.replace(/^\/|\/$/g,'');}channel=channel.replace(/^#/,'').toLowerCase();if(!/^[a-z0-9_]{1,25}$/.test(channel))throw Error('Enter a Twitch channel name or link.');return channel;}
class TwitchConnection extends EventEmitter{
 constructor(directory,shell,safeStorage,chat,clientId,io={}){super();Object.assign(this,{shell,safeStorage,chat,clientId,fetch:io.fetch||global.fetch,sleep:io.sleep||require('node:timers/promises').setTimeout,file:path.join(directory,'twitch-session.bin')});this.session=null;this.controller=null;this.timer=null;this.closed=false;this.checkedAt=0;this.state={pending:false,status:'Not connected',code:'',channel:''};try{if(safeStorage.isEncryptionAvailable()){const saved=JSON.parse(safeStorage.decryptString(fs.readFileSync(this.file)));if(saved.clientId===clientId&&TOKEN.test(saved.accessToken)&&REFRESH.test(saved.refreshToken)&&Number.isFinite(saved.expiresAt)){saved.channel=channelName(saved.channel);this.session=saved;this.state.channel=saved.channel;}}}catch{}}
 changed(){this.emit('change');}
 async request(endpoint,params,signal,token){const r=await this.fetch('https://id.twitch.tv/oauth2/'+endpoint,{method:params?'POST':'GET',headers:params?{'Content-Type':'application/x-www-form-urlencoded'}:{Authorization:'OAuth '+token},body:params?new URLSearchParams(params).toString():undefined,redirect:'error',signal:signal?AbortSignal.any([signal,AbortSignal.timeout(12000)]):AbortSignal.timeout(12000)});const reader=r.body?.getReader();if(!reader)throw Error('Twitch returned an empty response.');let size=0,chunks=[];try{while(true){const{done,value}=await reader.read();if(done)break;size+=value.length;if(size>16384){await reader.cancel();throw Error('Twitch response was too large.');}chunks.push(value);}}finally{reader.releaseLock();}let data;try{data=JSON.parse(Buffer.concat(chunks).toString());}catch{throw Error('Twitch returned an invalid response.');}return{ok:r.ok,status:r.status,data};}
 save(){if(!this.safeStorage.isEncryptionAvailable())throw Error('Windows secure storage is unavailable. Twitch was not saved.');fs.mkdirSync(path.dirname(this.file),{recursive:true});fs.writeFileSync(this.file+'.tmp',this.safeStorage.encryptString(JSON.stringify(this.session)));fs.renameSync(this.file+'.tmp',this.file);}
 accept(data,channel){if(!TOKEN.test(data.access_token)||!REFRESH.test(data.refresh_token)||!Number.isFinite(data.expires_in)||data.expires_in<=0||!Array.isArray(data.scope)||!data.scope.includes('chat:read'))throw Error('Twitch did not grant permission to read chat.');this.session={clientId:this.clientId,accessToken:data.access_token,refreshToken:data.refresh_token,expiresAt:Date.now()+data.expires_in*1000,channel};this.save();}
 async validate(signal){const r=await this.request('validate',null,signal,this.session.accessToken);if(r.status===401){this.clear();this.chat.close();throw Error('Twitch access expired or was revoked. Connect again.');}if(!r.ok)throw Error('Could not check Twitch. Please retry.');if(r.data.client_id!==this.clientId||!Array.isArray(r.data.scopes)||!r.data.scopes.includes('chat:read')||!/^[a-z0-9_]{1,25}$/i.test(r.data.login||'')){this.clear();this.chat.close();throw Error('Twitch returned missing chat permission. Connect again.');}this.session.username=r.data.login;this.checkedAt=Date.now();}
 async refresh(signal){const r=await this.request('token',{client_id:this.clientId,grant_type:'refresh_token',refresh_token:this.session.refreshToken},signal);if(!r.ok){if(r.status===400||r.status===401){this.clear();this.chat.close();}throw Error('Twitch could not renew the connection. Connect again.');}if(signal?.aborted)throw Error('Cancelled');this.accept(r.data,this.session.channel);await this.validate(signal);}
 start(channel){channel=channelName(channel);if(!/^[a-z0-9]{10,64}$/i.test(this.clientId||''))throw Error('Twitch is awaiting the companion owner’s one-time application setup.');if(!this.safeStorage.isEncryptionAvailable())throw Error('Windows secure storage is unavailable.');if(this.controller)throw Error('Twitch is already connecting. Cancel or wait.');this.closed=false;const controller=new AbortController();this.controller=controller;this.state={pending:true,status:'Opening Twitch in your browser…',code:'',channel};this.changed();this.authorize(channel,controller.signal).catch(e=>{if(!controller.signal.aborted)this.state.status=e.message;}).finally(()=>{if(this.controller===controller){this.controller=null;this.state.pending=false;this.state.code='';this.changed();}});}
 async authorize(channel,signal){
  if(this.session){if(this.session.expiresAt<Date.now()+300000)await this.refresh(signal);else await this.validate(signal);if(signal.aborted)throw Error('Cancelled');this.session.channel=channel;this.save();}
  else{const r=await this.request('device',{client_id:this.clientId,scopes:'chat:read'},signal);if(!r.ok)throw Error('Could not start Twitch approval. Check the registered Public client.');const d=r.data;let url;try{url=new URL(d.verification_uri);}catch{throw Error('Invalid Twitch approval link.');}if(url.origin!=='https://www.twitch.tv'||url.pathname!=='/activate'||url.username||url.password||!TOKEN.test(d.device_code)||!/^[A-Z0-9-]{4,20}$/i.test(d.user_code||'')||!Number.isFinite(d.expires_in)||!Number.isFinite(d.interval))throw Error('Invalid Twitch approval response.');if(signal.aborted)throw Error('Cancelled');this.state.code=d.user_code;this.state.status='Approve access in Twitch. Code: '+d.user_code;this.changed();await this.shell.openExternal(url.href);let interval=Math.max(5,d.interval)*1000;const end=Date.now()+Math.min(d.expires_in,1800)*1000;let accepted=false;while(Date.now()<end&&!signal.aborted){await this.sleep(interval,undefined,{signal});const t=await this.request('token',{client_id:this.clientId,scopes:'chat:read',device_code:d.device_code,grant_type:'urn:ietf:params:oauth:grant-type:device_code'},signal);if(signal.aborted)throw Error('Cancelled');if(t.ok){this.accept(t.data,channel);accepted=true;break;}const reason=t.data.message||t.data.error;if(reason==='authorization_pending')continue;if(reason==='slow_down'||t.status===429){interval=Math.min(interval+5000,60000);continue;}throw Error('Twitch approval was declined or expired.');}if(!accepted)throw Error('Twitch approval expired.');await this.validate(signal);}
  if(signal.aborted)throw Error('Cancelled');await this.chat.connect(this.session.username,channel,this.session.accessToken);if(signal.aborted){this.chat.close();throw Error('Cancelled');}this.state.status='Connected to '+channel;this.state.channel=channel;this.watch();
 }
 watch(){clearInterval(this.timer);this.timer=setInterval(()=>this.maintain(),60000);this.timer.unref?.();}
 async maintain(){if(this.closed||this.controller||!this.session)return;const controller=new AbortController();this.controller=controller;try{let refreshed=false;if(this.session.expiresAt<Date.now()+300000){await this.refresh(controller.signal);refreshed=true;}else if(Date.now()-this.checkedAt>=3600000)await this.validate(controller.signal);if(!controller.signal.aborted&&(refreshed||!this.chat.state.connected))await this.chat.connect(this.session.username,this.session.channel,this.session.accessToken);if(!controller.signal.aborted)this.state.status='Connected to '+this.session.channel;}catch{if(!controller.signal.aborted)this.state.status=this.session?'Twitch interrupted. Retrying…':'Connect with Twitch again.';}finally{if(this.controller===controller)this.controller=null;this.changed();}}
 async restore(){if(!this.session)return;this.state.status='Restoring saved Twitch connection…';this.changed();await this.maintain();if(this.session)this.watch();}
 cancel(){this.controller?.abort();this.state.pending=false;this.state.code='';this.state.status=this.chat.state.connected?'Connected to '+this.chat.state.channel:'Connection cancelled.';this.changed();}
 clear(){this.session=null;try{fs.unlinkSync(this.file);}catch{}try{fs.unlinkSync(this.file+'.tmp');}catch{}}
 async disconnect(){const token=this.session?.accessToken;this.close();this.clear();this.state={pending:false,status:'Disconnected',code:'',channel:''};this.changed();if(token)await this.request('revoke',{client_id:this.clientId,token}).catch(()=>{});}
 close(){this.closed=true;clearInterval(this.timer);this.cancel();this.chat.close();}
}
module.exports={TwitchConnection,channelName};
