const fs=require('node:fs'),path=require('node:path');
function readUpdateRoot(bytes,exe){const text=bytes?.subarray(0,2).equals(Buffer.from([255,254]))?bytes.toString('utf16le'):bytes?.toString('utf8')||'';const selected=text.match(/^UpdateRoot=(.+)$/mi)?.[1]?.trim();const root=selected||path.win32.dirname(exe)+'-updates';if(!/^[a-z]:\\/i.test(root)||/[\x00-\x1f]/.test(root))throw Error('Choose a local update folder by running the installer again.');return path.win32.join(path.win32.normalize(root),'.centerpiece-companion-updates');}
function updateStorage(app){const exe=app.getPath('exe');let bytes;try{bytes=fs.readFileSync(path.join(app.getPath('userData'),'update-location.ini'));return readUpdateRoot(bytes,exe);}catch{bytes=undefined;}try{bytes=fs.readFileSync(path.join(path.dirname(exe),'install-locations.ini'));}catch{}return readUpdateRoot(bytes,exe);}
function checkWritable(base){for(const folder of [base,path.join(base,'centerpiece-companion-updater'),path.join(base,'centerpiece-companion-updater','pending'),path.join(base,'temporary')]){fs.mkdirSync(folder,{recursive:true});const probe=path.join(folder,'.write-check-'+require('node:crypto').randomUUID());let fd;try{fd=fs.openSync(probe,'wx');fs.writeSync(fd,'test');}finally{if(fd!==undefined){fs.closeSync(fd);fs.unlinkSync(probe);}}}}
async function chooseWritableStorage(app,current,dialog){try{checkWritable(current);return current;}catch(error){if(!['EACCES','EPERM','EROFS','ENOENT','ENOTDIR'].includes(error.code))throw error;}
 const result=await dialog.showOpenDialog({title:'Choose a writable folder for update downloads',message:'Windows denied access to the saved update folder. Choose a folder you can write to on your preferred drive.',defaultPath:path.dirname(current),properties:['openDirectory','createDirectory']});if(result.canceled||!result.filePaths?.length)return null;
 const selected=result.filePaths[0],base=readUpdateRoot(Buffer.from('UpdateRoot='+selected),app.getPath('exe'));checkWritable(base);fs.writeFileSync(path.join(app.getPath('userData'),'update-location.ini'),'[Storage]\nUpdateRoot='+selected+'\n');return base;
}
function prepareUpdateTemp(base){const temp=path.join(base,'temporary');fs.mkdirSync(temp,{recursive:true});return temp;}
module.exports={readUpdateRoot,updateStorage,prepareUpdateTemp,checkWritable,chooseWritableStorage};
