const appearance=require('./appearance.cjs');
const {positionAt}=require('./playback-clock.cjs');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function weatherIcon(kind,phase=Math.floor(Date.now()/500)%8,windy=false){
 const drift=[-3,-2,0,2,3,2,0,-2][phase%8],shine=[.45,.7,.95,1,.7,.5,.8,1][phase%8],pulse=[6.4,6.9,7.5,7.1,6.5,6.9,7.5,7.1][phase%8];
 const sun=`<g transform="rotate(${phase%8*5-15} 16 16)"><circle cx="16" cy="16" r="${pulse}" fill="#f7c948"/><circle cx="16" cy="16" r="${pulse+2.5}" fill="none" stroke="#ffe58a" stroke-opacity="${shine*.45}" stroke-width="1.5"/><path opacity="${shine}" d="M16 0V5M16 27V32M0 16H5M27 16H32M4 4L8 8M24 24L28 28M4 28L8 24M24 8L28 4" stroke="#f7c948" stroke-width="2.8" stroke-linecap="round"/></g>`;
 const cloud=`<g transform="translate(${drift} 0)"><path d="M6 24C-1 24-1 14 7 14C8 3 23 3 25 14C34 14 34 26 26 26H6Z" fill="#bfd1e7"/><path d="M8 25H25" stroke="#edf6ff" stroke-opacity="${shine*.55}" stroke-width="1.5"/></g>`;
 const fall=[0,3,6,9,12,9,6,3][phase%8];
 const moon=`<path d="M22 4A13 13 0 1 0 27 26A12 12 0 0 1 22 4Z" fill="#e1eaff"/><path opacity="${shine}" d="M29 2V8M26 5H32M6 2V6M4 4H8" stroke="#f7db8e" stroke-width="1.8"/><circle cx="10" cy="11" r="${shine>0.7?1.4:.7}" fill="#fff3bb"/><circle cx="25" cy="14" r="${shine>.8?1.2:.6}" fill="#fff3bb"/>`;
 const wind=`<g transform="translate(${drift*3} 0)" opacity="${shine}"><path d="M2 12H21Q29 12 27 6Q24 1 20 6M4 20H26Q34 20 30 27M1 28H16" fill="none" stroke="#b7e5f7" stroke-width="2" stroke-linecap="round"/></g>`;
 const artwork=kind==='wind'?wind:kind==='moon'?moon:kind==='night-cloud'?moon+`<g transform="translate(6 10) scale(.8)">${cloud}</g>`:kind==='partly'?sun+`<g transform="translate(6 10) scale(.8)">${cloud}</g>`:kind==='fog'?cloud+'<path d="M2 30H30M5 35H27" stroke="#a8b5c9" stroke-width="2"/>':kind==='sun'?sun:cloud+(kind==='snow'?`<g fill="#edf2fa"><circle cx="${9+drift}" cy="${29+fall}" r="1.6"/><circle cx="20" cy="${33-fall}" r="1.6"/><circle cx="${28-drift}" cy="${29+fall}" r="1.6"/></g>`:kind==='rain'?`<path d="M10 ${27+fall}L7 ${32+fall}M20 ${29+fall}L17 ${34+fall}M28 ${27+fall}L25 ${32+fall}" stroke="#69b8ff" stroke-width="2"/>`:kind==='storm'?`<path opacity="${shine}" d="M20 19L13 29H19L15 38L27 25H20Z" fill="#ffd75b"/>`:'');
 return artwork+(windy&&kind!=='wind'?`<g transform="translate(0 18) scale(.7)">${wind}</g>`:'');
}
function timerText(value){const seconds=Math.max(0,Math.ceil(value||0));return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}

function clockReading(data={}){const parts=new Intl.DateTimeFormat(data.locale||undefined,{hour:'2-digit',minute:'2-digit',...(data.clockSeconds?{second:'2-digit'}:{})}).formatToParts(new Date(data.now??Date.now()));const period=parts.find(p=>p.type==='dayPeriod')?.value;return{value:parts.filter(p=>p.type!=='dayPeriod').map(p=>p.value).join('').trim(),label:'LOCAL TIME'+(period?' · '+period:'')};}
function reading(plugin,data={}){const live=data.live||{};switch(plugin){case'calendar':return{value:new Date(data.now??Date.now()).getDate().toString(),label:new Date(data.now??Date.now()).toLocaleDateString(undefined,{weekday:'short',month:'short'})};case'timer':return{value:timerText(data.timer?.remaining??1500),label:data.timer?.finished?'TIME UP':data.timer?.running?'COUNTDOWN':'TIMER PAUSED'};case'weather':{const weather=live.weather,stale=weather&&((data.now??Date.now())-(weather.observedAt||weather.updatedAt||Date.now())>30*60000);return{value:weather&&!stale?weather.temperature+weather.unit:'—',label:stale?'Update needed':live.weatherError&&weather?'Last reading':weather?.label||'Set location',icon:stale?null:weather?.icon,windy:!stale&&weather?.windy};}case'clock':return clockReading(data);case'cpu':return{value:live.cpuTemp!==null&&live.cpuTemp!==undefined?live.cpuTemp+'°C':live.cpuLoad!==null&&live.cpuLoad!==undefined?live.cpuLoad+'%':'—',label:live.cpuTemp!==null&&live.cpuTemp!==undefined?'CPU TEMP':'CPU LOAD'};case'gpu':return{value:live.gpuTemp!==null&&live.gpuTemp!==undefined?live.gpuTemp+'°C':'—',label:live.gpuTemp==null?'No sensor':'GPU TEMP'};case'mic':return{value:live.mic?live.mic.muted?'MUTED':'LIVE':'—',label:'MICROPHONE'};default:return null;}}
function detailSVG(config,data){const w=config.widget;if(!w||w.type==='off')return'';let type=w.type==='follow'?(config.slots[data.selected||0]?.plugin||'clock'):w.type;const x=w.x,y=w.y,width=w.width,height=w.height;let content='';const txt=(text,tx,ty,size=16,color='#edf2fa')=>`<text x="${tx}" y="${ty}" font-family="Arial" font-size="${size}" fill="${color}">${esc(text)}</text>`;
 if(type==='spotify'){const m=data.media||{},art=m.art;const pos=positionAt(m);if(art&&/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(art))content+=`<image x="6" y="7" width="54" height="54" href="${art}"/>`;content+=txt(m.available?(m.title||'Spotify').slice(0,16):'Open Spotify',66,27,12)+txt((m.artist||'').slice(0,18),66,47,10,'#a8b5c9')+`<rect x="8" y="${height-22}" width="${width-16}" height="4" rx="2" fill="#374457"/><rect x="8" y="${height-22}" width="${Math.round(Math.max(0,(width-16)*pos/Math.max(1,m.duration||1)))}" height="4" rx="2" fill="#1db954"/>`+txt(`${Math.floor(pos/60)}:${String(Math.floor(pos%60)).padStart(2,'0')}`,8,height-6,10);
 }else if(type==='obs'){const o=data.obs||{};const label=!o.connected?'Connect OBS':o.error?'Status unavailable':o.streaming?'ON AIR':o.recording?'RECORDING':'OBS READY';content+=txt(label,8,22,13,o.streaming||o.recording?'#ff9aa8':'#a8b5c9')+txt(o.connected&&!o.error?timerText(o.streaming?o.streamSeconds:o.recordSeconds):'—',8,62,30);
 }else if(type==='twitch'){const chat=data.chat;content+=txt('TWITCH CHAT',8,17,11,'#a970ff');const text=chat?.message||'Connect Twitch in the app';for(let i=0;i<3;i++)content+=txt(text.slice(i*25,(i+1)*25),8,35+i*16,11);
 }else if(type==='calendar'){content+=calendarSVG(width,height,new Date(data.now??Date.now()));
 }else if(type==='text'){content+=appearance.textSVG(w.text,width,height,w.textStyle);
 }else{const r=reading(type,{...data,clockSeconds:config.widget?.clockSeconds});if(r){if(r.icon)content+=`<g transform="translate(10 25)">${weatherIcon(r.icon,config.weatherMotion===false?0:undefined,r.windy)}</g>`;content+=txt(r.label,8,17,10,'#a8b5c9')+txt(r.value,r.icon?55:8,61,r.value.length>7?24:32);}else content+=txt('Select a live widget',8,35,14);}
 return `<svg x="${x}" y="${y}" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" overflow="hidden"><rect width="${width}" height="${height}" rx="9" fill="${appearance.appearance(config.appearance).widgetBackground}" stroke="${appearance.appearance(config.appearance).border}"/>${content}</svg>`;
}
function calendarSVG(width,height,date){const year=date.getFullYear(),month=date.getMonth(),today=date.getDate(),offset=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate(),rows=Math.ceil((offset+days)/7),top=height*.35,cellW=width/7,cellH=(height-top-2)/rows;let out=`<text x="${width/2}" y="${height*.13}" text-anchor="middle" font-family="Arial" font-size="${Math.max(9,height*.12)}" fill="#edf2fa">${esc(date.toLocaleDateString(undefined,{weekday:'long'}))}</text><text x="${width/2}" y="${height*.24}" text-anchor="middle" font-family="Arial" font-size="${Math.max(8,height*.09)}" fill="#a8b5c9">${esc(date.toLocaleDateString(undefined,{month:'long',year:'numeric'}))}</text>`;
 for(let d=0;d<7;d++)out+=`<text x="${(d+.5)*cellW}" y="${height*.34}" text-anchor="middle" font-family="Arial" font-size="${Math.max(7,height*.08)}" fill="#a8b5c9">${['M','T','W','T','F','S','S'][d]}</text>`;
 for(let day=1;day<=days;day++){const n=offset+day-1,x=(n%7+.5)*cellW,y=top+Math.floor(n/7)*cellH;if(day===today)out+=`<rect data-today="true" x="${x-cellW*.36}" y="${y}" width="${cellW*.72}" height="${cellH}" rx="2" fill="#c93243"/>`;out+=`<text x="${x}" y="${y+cellH*.78}" text-anchor="middle" font-family="Arial" font-size="${Math.max(7,Math.min(cellH*.8,cellW*.5))}" fill="#edf2fa">${day}</text>`;}return out;}
module.exports={clockReading,esc,weatherIcon,reading,detailSVG,calendarSVG};
