const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function weatherIcon(kind){const sun='<circle cx="16" cy="16" r="7" fill="#f7c948"/><path d="M16 1V5M16 27V31M1 16H5M27 16H31M5 5L8 8M24 24L27 27M5 27L8 24M24 8L27 5" stroke="#f7c948" stroke-width="2"/>';const cloud='<path d="M6 24C-1 24-1 14 7 14C8 3 23 3 25 14C34 14 34 26 26 26H6Z" fill="#bfd1e7"/>';return kind==='sun'?sun:cloud+(kind==='snow'?'<text x="8" y="37" fill="#fff" font-size="16">* *</text>':kind==='rain'?'<path d="M10 29L7 35M20 29L17 35M28 29L25 35" stroke="#69b8ff" stroke-width="3"/>':kind==='storm'?'<path d="M20 19L13 29H19L15 38L27 25H20Z" fill="#ffd75b"/>':'');}
function reading(plugin,data={}){const live=data.live||{};switch(plugin){case'weather':return{value:live.weather?live.weather.temperature+live.weather.unit:'—',label:live.weather?.label||'Set location',icon:live.weather?.icon};case'clock':return{value:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),label:'LOCAL TIME'};case'cpu':return{value:live.cpuTemp!==null&&live.cpuTemp!==undefined?live.cpuTemp+'°C':live.cpuLoad!==null&&live.cpuLoad!==undefined?live.cpuLoad+'%':'—',label:live.cpuTemp!==null&&live.cpuTemp!==undefined?'CPU TEMP':'CPU LOAD'};case'gpu':return{value:live.gpuTemp!==null&&live.gpuTemp!==undefined?live.gpuTemp+'°C':'—',label:live.gpuTemp===null?'No sensor':'GPU TEMP'};case'mic':return{value:live.mic?live.mic.muted?'MUTED':'LIVE':'—',label:'MICROPHONE'};default:return null;}}
function detailSVG(config,data){const w=config.widget;if(!w||w.type==='off')return'';let type=w.type==='follow'?(config.slots[data.selected||0]?.plugin||'clock'):w.type;const x=w.x,y=w.y,width=w.width,height=w.height;let content='';const txt=(text,tx,ty,size=16,color='#edf2fa')=>`<text x="${tx}" y="${ty}" font-family="Arial" font-size="${size}" fill="${color}">${esc(text)}</text>`;
 if(type==='spotify'){const m=data.media||{},art=m.art;const pos=Math.min(m.duration||0,Math.max(0,(m.position||0)+(m.status==='Playing'?Math.max(0,(Date.now()-(m.receivedAt||Date.now()))/1000):0)));if(art&&/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/=]+$/.test(art))content+=`<image x="6" y="7" width="44" height="44" href="${art}"/>`;content+=txt(m.available?(m.title||'Spotify').slice(0,18):'Open Spotify',56,24,13)+txt((m.artist||'').slice(0,20),56,43,10,'#a8b5c9')+`<rect x="8" y="${height-22}" width="${width-16}" height="4" rx="2" fill="#374457"/><rect x="8" y="${height-22}" width="${Math.max(0,(width-16)*pos/Math.max(1,m.duration||1))}" height="4" rx="2" fill="#1db954"/>`+txt(`${Math.floor(pos/60)}:${String(Math.floor(pos%60)).padStart(2,'0')}`,8,height-6,10);
 }else if(type==='twitch'){const chat=data.chat;content+=txt('TWITCH CHAT',8,17,11,'#a970ff');const text=chat?.message||'Connect Twitch in the app';for(let i=0;i<3;i++)content+=txt(text.slice(i*25,(i+1)*25),8,35+i*16,11);
 }else if(type==='text'){for(let i=0;i<3;i++)content+=txt(w.text.slice(i*22,(i+1)*22),8,25+i*22,15);
 }else{const r=reading(type,data);if(r){if(r.icon)content+=`<g transform="translate(10 25)">${weatherIcon(r.icon)}</g>`;content+=txt(r.label,8,17,10,'#a8b5c9')+txt(r.value,r.icon?55:8,61,r.value.length>7?24:32);}else content+=txt('Select a live widget',8,35,14);}
 return `<svg x="${x}" y="${y}" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" overflow="hidden"><rect width="${width}" height="${height}" rx="9" fill="#111820" stroke="#48607a"/>${content}</svg>`;
}
module.exports={esc,weatherIcon,reading,detailSVG};
