const snapshot=require('./xpanel-skins.json');
const ASSETS='https://assets.freethinkerportal.com';
function catalog(registry){if(!Array.isArray(registry.skins)||registry.skins.length>2000)throw Error('Invalid XPANEL catalog.');const seen=new Set();return registry.skins.map(s=>{if(!/^[a-f0-9-]{36}$/i.test(s.fileID)||seen.has(s.fileID)||typeof s.skinName!=='string'||typeof s.creatorName!=='string'||!/^community\/[a-zA-Z0-9_/-]+$/.test(s.skinPath)||s.skinPath.includes('..')||!/^[-\w]+\.(png|jpg|jpeg|webp)$/i.test(s.thumbnailFile||''))throw Error('Unexpected XPANEL skin entry.');seen.add(s.fileID);return{id:s.fileID,title:s.skinName.slice(0,120),creator:s.creatorName.slice(0,100),thumbnail:ASSETS+'/'+s.skinPath+'/'+s.thumbnailFile,source:'XPANEL community',approvedAt:String(s.approvedAt||'').slice(0,40)};});}
class XpanelSkins{
 constructor(shell){this.shell=shell;this.state={items:catalog(snapshot),updatedAt:snapshot.generatedAt,error:''};}
 async refresh(){try{const r=await fetch(ASSETS+'/community/registry.json',{redirect:'error',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('XPANEL catalog is temporarily unavailable.');const text=await limitedText(r,2*1024*1024);const registry=JSON.parse(text);this.state.items=catalog(registry);this.state.updatedAt=String(registry.generatedAt||'');this.state.error='';}catch(e){this.state.error=e.message;}return this.state;}
 async download(id){if(!this.state.items.some(s=>s.id===id))throw Error('Choose a listed XPANEL skin.');const r=await fetch('https://marketplace-upload.ashkon.workers.dev/skins/'+encodeURIComponent(id)+'/download',{redirect:'error',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('XPANEL could not provide this download. Try again later.');const value=JSON.parse(await limitedText(r,16000));let u;try{u=new URL(value.url);}catch{throw Error('Invalid skin download response.');}if(u.protocol!=='https:'||u.username||u.password||![ASSETS,'https://f68b2f1c1c77a854e211cd309275fa45.r2.cloudflarestorage.com'].includes(u.origin))throw Error('Unrecognized XPANEL download host.');await this.shell.openExternal(u.href);}
}
async function limitedText(r,max){const reader=r.body.getReader();let size=0,chunks=[];try{while(true){const{done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw Error('XPANEL response is too large.');}chunks.push(value);}}finally{reader.releaseLock();}return Buffer.concat(chunks).toString('utf8');}
module.exports={XpanelSkins,catalog};
